#!/usr/bin/env python3
"""Back-reaction: amplitude modifies graph topology.

THE IDEA:
  Standard propagation: fixed graph, amplitude flows through it.
  Back-reaction: amplitude at layer N determines edge density at layer N+1.
  High amplitude → more edges → more paths → stronger coupling.

  If this produces BOTH:
    1. Gravity (deflection TOWARD mass) — from field-dependent phase
    2. Absorption near mass (escape < 1) — from topology change

  ...then the complex action S = L(1-f) + i*gamma*L*f EMERGES from
  graph dynamics. Gamma is not a free parameter — it's generated by
  the self-interaction of the propagator with its geometry.

MECHANISM:
  At each layer, compute |psi|^2 at each node. Nodes above a threshold
  get extra edges (extended connectivity). This creates:
  - More paths near high-amplitude regions
  - More phase cancellation (destructive interference from extra paths)
  - Net effect: amplitude suppression in strong-field regions

  This is the discrete analog of "gravity curves spacetime" →
  "curved spacetime traps light."

CONTROLS:
  1. Zero field: back-reaction with no mass. Should be symmetric, no net effect.
  2. Fixed graph: field but no back-reaction. Standard gravity, escape > 1.
  3. Back-reaction + field: if escape < 1, absorption emerged from topology.
"""

from __future__ import annotations

import math
import time
import numpy as np

BETA = 0.8
K = 5.0
MAX_D_PHYS = 3.0
H = 0.5
PHYS_W = 6
PHYS_L = 30
MASS_Z = 3.0
STRENGTH = 0.1

# Back-reaction parameters
BR_THRESHOLD = 0.5   # Fraction of max amplitude above which extra edges added
BR_EXTRA_D = 1       # Extra edge reach (lattice units) for high-amplitude nodes


def _build_offsets(h, max_d_phys):
    max_d = max(1, round(max_d_phys / h))
    offsets = []
    for dy in range(-max_d, max_d + 1):
        for dz in range(-max_d, max_d + 1):
            dyp, dzp = dy * h, dz * h
            L = math.sqrt(h * h + dyp * dyp + dzp * dzp)
            theta = math.atan2(math.sqrt(dyp * dyp + dzp * dzp), h)
            w = math.exp(-BETA * theta * theta)
            offsets.append((dy, dz, L, w * h * h / (L * L)))
    T = sum(wr for _, _, _, wr in offsets)
    return offsets, T


def _build_extended_offsets(h, max_d_phys_ext):
    """Extended edges for back-reaction nodes."""
    max_d = max(1, round(max_d_phys_ext / h))
    max_d_base = max(1, round(MAX_D_PHYS / h))
    offsets = []
    for dy in range(-max_d, max_d + 1):
        for dz in range(-max_d, max_d + 1):
            # Only include edges BEYOND the base set
            if abs(dy) <= max_d_base and abs(dz) <= max_d_base:
                continue
            dyp, dzp = dy * h, dz * h
            L = math.sqrt(h * h + dyp * dyp + dzp * dzp)
            theta = math.atan2(math.sqrt(dyp * dyp + dzp * dzp), h)
            w = math.exp(-BETA * theta * theta)
            offsets.append((dy, dz, L, w * h * h / (L * L)))
    return offsets


def _field(nl, nw, hw, h, s, z_src):
    gl = nl // 3
    iz_s = round(z_src / h)
    sx, sz = gl * h, iz_s * h
    f = np.zeros((nl, nw * nw))
    for layer in range(nl):
        x = layer * h
        idx = 0
        for iy in range(-hw, hw + 1):
            for iz in range(-hw, hw + 1):
                r = math.sqrt((x - sx) ** 2 + (iy * h) ** 2 + (iz * h - sz) ** 2) + 0.1
                f[layer, idx] = s / r
                idx += 1
    return f


def _propagate_backreaction(
    nl, nw, npl, hw, base_offsets, T_base, ext_offsets, field, k,
    br_strength=1.0, br_threshold=0.5,
):
    """Propagate with back-reaction: amplitude modifies edge density.

    At each layer:
    1. Propagate through base edges (standard)
    2. Identify high-amplitude nodes (above threshold * max)
    3. Add extra edge contributions from extended offsets for those nodes
    """
    amps = np.zeros((nl, npl), dtype=np.complex128)
    amps[0, hw * nw + hw] = 1.0

    # Precompute T for extended edges
    T_ext = sum(wr for _, _, _, wr in ext_offsets) if ext_offsets else 0.0
    T_total = T_base + T_ext * br_strength if T_ext > 0 else T_base

    extra_edges_used = 0

    for layer in range(nl - 1):
        sa = amps[layer]
        mx_amp = np.max(np.abs(sa))
        if mx_amp < 1e-300:
            continue

        sf = field[layer]
        df = field[min(layer + 1, nl - 1)]

        # Phase 1: Standard edges (all nodes)
        for dy, dz, L, w_raw in base_offsets:
            ym, yM = max(0, -dy), min(nw, nw - dy)
            zm, zM = max(0, -dz), min(nw, nw - dz)
            if ym >= yM or zm >= zM:
                continue
            yi, zi = np.meshgrid(np.arange(ym, yM), np.arange(zm, zM), indexing='ij')
            si = yi.ravel() * nw + zi.ravel()
            di = (yi.ravel() + dy) * nw + (zi.ravel() + dz)
            ai = sa[si]
            mask = np.abs(ai) > 1e-300
            if not np.any(mask):
                continue
            si_m, di_m, ai_m = si[mask], di[mask], ai[mask]
            lf = 0.5 * (sf[si_m] + df[di_m])
            act = L * (1.0 - lf)
            phase = k * act
            np.add.at(amps[layer + 1], di_m,
                      ai_m * (np.cos(phase) + 1j * np.sin(phase)) * w_raw / T_total)

        # Phase 2: Extended edges (high-amplitude nodes only)
        if ext_offsets and br_strength > 0:
            amp_sq = np.abs(sa) ** 2
            threshold = br_threshold * np.max(amp_sq)
            high_amp_mask = amp_sq > threshold

            if np.any(high_amp_mask):
                extra_edges_used += 1
                for dy, dz, L, w_raw in ext_offsets:
                    ym, yM = max(0, -dy), min(nw, nw - dy)
                    zm, zM = max(0, -dz), min(nw, nw - dz)
                    if ym >= yM or zm >= zM:
                        continue
                    yi, zi = np.meshgrid(np.arange(ym, yM), np.arange(zm, zM), indexing='ij')
                    si = yi.ravel() * nw + zi.ravel()
                    di = (yi.ravel() + dy) * nw + (zi.ravel() + dz)
                    ai = sa[si]
                    # Only high-amplitude source nodes get extra edges
                    mask = high_amp_mask[si] & (np.abs(ai) > 1e-300)
                    if not np.any(mask):
                        continue
                    si_m, di_m, ai_m = si[mask], di[mask], ai[mask]
                    lf = 0.5 * (sf[si_m] + df[di_m])
                    act = L * (1.0 - lf)
                    phase = k * act
                    np.add.at(amps[layer + 1], di_m,
                              ai_m * (np.cos(phase) + 1j * np.sin(phase)) * w_raw * br_strength / T_total)

    return amps, extra_edges_used


def _cz(a, nw, hw, h):
    p = np.abs(a) ** 2
    t = p.sum()
    if t <= 0:
        return 0.0
    zc = np.array([iz * h for _ in range(-hw, hw + 1) for iz in range(-hw, hw + 1)])
    return float(np.dot(p, zc) / t)


def _dp(a):
    return float(np.sum(np.abs(a) ** 2))


def main():
    h = H
    nl = int(PHYS_L / h) + 1
    hw = int(PHYS_W / h)
    nw = 2 * hw + 1
    npl = nw * nw

    base_offsets, T_base = _build_offsets(h, MAX_D_PHYS)
    ext_offsets = _build_extended_offsets(h, MAX_D_PHYS + BR_EXTRA_D * h)

    zero_field = np.zeros((nl, npl))
    grav_field = _field(nl, nw, hw, h, STRENGTH, MASS_Z)

    print("=" * 80)
    print("BACK-REACTION: AMPLITUDE MODIFIES GRAPH TOPOLOGY")
    print(f"  h={h}, W={PHYS_W}, L={PHYS_L}, s={STRENGTH}, z_src={MASS_Z}")
    print(f"  base edges: {len(base_offsets)}, extended edges: {len(ext_offsets)}")
    print(f"  T_base = {T_base:.3f}")
    print("=" * 80)
    print()

    # Control 1: No field, no back-reaction (baseline)
    free_std, _ = _propagate_backreaction(
        nl, nw, npl, hw, base_offsets, T_base, [], zero_field, K, br_strength=0)
    z_free = _cz(free_std[-1], nw, hw, h)
    p_free = _dp(free_std[-1])

    # Control 2: Field, no back-reaction (standard gravity)
    grav_std, _ = _propagate_backreaction(
        nl, nw, npl, hw, base_offsets, T_base, [], grav_field, K, br_strength=0)
    z_grav_std = _cz(grav_std[-1], nw, hw, h)
    p_grav_std = _dp(grav_std[-1])

    print("CONTROLS")
    print(f"  free (no field, no BR):   centroid = {z_free:.6f}")
    print(f"  grav (field, no BR):      centroid = {z_grav_std:.6f}, "
          f"delta = {z_grav_std - z_free:+.6e} TOWARD, "
          f"escape = {p_grav_std / p_free:.4f}")
    print()

    # Sweep back-reaction strength
    br_strengths = [0.0, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0]
    thresholds = [0.5]

    print(f"{'br':>5s} {'thr':>5s} {'delta':>12s} {'dir':>6s} {'escape':>8s} {'br_layers':>10s}")
    print("-" * 55)

    for thr in thresholds:
        for br in br_strengths:
            # With field + back-reaction
            amps, n_br = _propagate_backreaction(
                nl, nw, npl, hw, base_offsets, T_base, ext_offsets,
                grav_field, K, br_strength=br, br_threshold=thr)
            delta = _cz(amps[-1], nw, hw, h) - z_free
            escape = _dp(amps[-1]) / p_free if p_free > 0 else 0
            direction = "TOWARD" if delta > 0 else "AWAY"
            print(f"{br:5.1f} {thr:5.1f} {delta:+12.6e} {direction:>6s} {escape:8.4f} {n_br:10d}")

    # Control 3: Back-reaction WITHOUT field (should be symmetric)
    print()
    print("SYMMETRY CHECK (back-reaction, no field)")
    for br in [1.0, 5.0]:
        amps, n_br = _propagate_backreaction(
            nl, nw, npl, hw, base_offsets, T_base, ext_offsets,
            zero_field, K, br_strength=br, br_threshold=0.5)
        delta = _cz(amps[-1], nw, hw, h) - z_free
        escape = _dp(amps[-1]) / p_free if p_free > 0 else 0
        print(f"  br={br:.1f}: delta = {delta:+.6e}, escape = {escape:.4f}")

    # Key test: does back-reaction produce BOTH gravity and absorption?
    print()
    print("KEY QUESTION")
    print("  If escape < 1 WITH back-reaction but > 1 WITHOUT:")
    print("  → absorption EMERGES from topology change")
    print("  → gamma is not a free parameter, it's generated by the propagator")
    print("  → this is quantum gravity: geometry responds to matter")

    # F~M with back-reaction
    print()
    print("MASS SCALING with back-reaction (br=1.0)")
    strengths_m = [0.001, 0.002, 0.004, 0.008]
    deltas_m = []
    for s in strengths_m:
        f = _field(nl, nw, hw, h, s, MASS_Z)
        a, _ = _propagate_backreaction(
            nl, nw, npl, hw, base_offsets, T_base, ext_offsets,
            f, K, br_strength=1.0, br_threshold=0.5)
        d = _cz(a[-1], nw, hw, h) - z_free
        deltas_m.append(abs(d))
    lx = [math.log(x) for x in strengths_m]
    ly = [math.log(y) for y in deltas_m if y > 1e-300]
    nn = len(ly)
    if nn >= 3:
        mx = sum(lx[:nn]) / nn
        my = sum(ly) / nn
        sxx = sum((x - mx) ** 2 for x in lx[:nn])
        sxy = sum((x - mx) * (y - my) for x, y in zip(lx[:nn], ly))
        fm = sxy / sxx
    else:
        fm = float('nan')
    print(f"  F~M = {fm:.3f}")


if __name__ == "__main__":
    main()
