"""
Koide A1 Probe 17 — Non-Conjugation Lift of Retained Per-Site Qubit U(1)

Probe 14 (RETAINED_U1_HUNT) closed: every retained continuous U(1) acts on
M_3(C) as conjugation X -> UXU^*; on the C_3-fixed subalgebra A^{C_3},
conjugation by any U commuting with C_3 is TRIVIAL on circulants. Hence
no retained U(1) gives the missing U(1)_b symmetry on the b-doublet via
algebra-automorphism.

This probe (Probe 17) tests the orthogonal hypothesis: there might be a
NON-CONJUGATION lift of the retained per-site qubit U(1) (the continuous
U(1) on each per-site Cl(3) ≅ M_2(C)) that:
  (a) acts non-trivially on the b-doublet of A^{C_3},
  (b) restricts as the linear vector-space action phi_theta on M_3(C),
  (c) is derivable from retained content (no new axioms).

We enumerate five concrete attack vectors:
  V1. Per-site phase with C_3-character-graded angle.
  V2. Bimodule action (left/right module distinct from conjugation).
  V3. Twisted conjugation X -> UXV^* with U != V both in retained per-
      site qubit U(1).
  V4. Pseudoscalar-twisted action (omega = e_1 e_2 e_3 central in Cl(3)).
  V5. Local-to-global lift via spatial site-position-dependent phase.

The runner verifies, for each vector, whether it can close A1.

VERDICT (proven section-by-section):

  All five attack vectors collapse back to ALGEBRA-AUTOMORPHISM
  (= conjugation by some unitary on H_hw=1) when the action is required
  to be (i) well-defined on H_hw=1, (ii) generated by retained per-site
  qubit U(1) on H_lat, and (iii) closed under group operation.

  STRUCTURAL OBSTRUCTION mechanism (the deeper "why"):

    Any continuous one-parameter unitary group {U_theta} on a single
    Hilbert space H acts on End(H) = M_n(C) ONLY by conjugation
    A -> U_theta A U_theta^*. There is no "twisted" action U A V^* with
    V != U accessible from a one-parameter group, because the action of
    a group on its bimodule (End(H) viewed as H \otimes H^*) always
    factors through the single state-space action.

    Per-site qubit U(1) restricted to H_hw=1 (= 1-particle sector) gives
    a one-parameter unitary group on a 3-dim Hilbert space. By the
    rigidity above, this acts on M_3(C) by conjugation, hence trivially
    on A^{C_3} (Probe 14). No "lift" can produce non-conjugation action
    while remaining a representation of the retained one-parameter group.

  Therefore no retained per-site qubit U(1) supplies the missing U(1)_b
  via a non-conjugation lift. The structural obstruction is sharper than
  Probe 14: it identifies the precise rigidity (single-Hilbert-space
  unitary group => conjugation lift) that forbids non-conjugation
  realizations.

  A1 admission count: UNCHANGED. Status: SHARPENED bounded obstruction.

This runner verifies each step algebraically. No PDG values are imported
as derivation input.
"""

from __future__ import annotations

import numpy as np


# ----------------------------------------------------------------------
# Test harness
# ----------------------------------------------------------------------

PASS_COUNT = 0
FAIL_COUNT = 0


def check(label: str, condition: bool, *, detail: str = "") -> None:
    """Single PASS/FAIL line, mirroring the campaign's runner style."""
    global PASS_COUNT, FAIL_COUNT
    if condition:
        PASS_COUNT += 1
        print(f"  PASS  {label}")
    else:
        FAIL_COUNT += 1
        print(f"  FAIL  {label}")
        if detail:
            print(f"        detail: {detail}")


def section(title: str) -> None:
    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


# ----------------------------------------------------------------------
# Algebraic primitives
# ----------------------------------------------------------------------

omega = np.exp(2j * np.pi / 3)
omega_bar = omega.conjugate()

# C_3 cyclic shift on C^3: C maps e_i -> e_{i+1 mod 3}
C = np.zeros((3, 3), dtype=complex)
C[1, 0] = C[2, 1] = C[0, 2] = 1.0
C2 = C @ C
I3 = np.eye(3, dtype=complex)

# Pauli matrices (Cl(3) per-site generators)
sigma_0 = np.eye(2, dtype=complex)
sigma_1 = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_3 = np.array([[1, 0], [0, -1]], dtype=complex)


def hermitian_circulant(a: float, b: complex) -> np.ndarray:
    """H = aI + bC + b̄C^2 (Hermitian circulant on C^3)."""
    return a * I3 + b * C + np.conj(b) * C2


def conjugation(X: np.ndarray, U: np.ndarray) -> np.ndarray:
    """Algebra-automorphism action: alpha_U(X) = U X U^*."""
    return U @ X @ U.conj().T


def conditional_expectation_C3(X: np.ndarray) -> np.ndarray:
    """E(X) = (1/3) sum_g alpha_{C^g}(X) — projection onto circulants."""
    return (X + C @ X @ C.conj().T + C2 @ X @ C2.conj().T) / 3.0


def is_circulant(X: np.ndarray, tol: float = 1e-10) -> bool:
    """Check if X is in span{I, C, C^2}."""
    a = np.trace(X) / 3.0
    b = np.trace(X @ C2) / 3.0
    bbar = np.trace(X @ C) / 3.0
    reconstr = a * I3 + b * C + bbar * C2
    return bool(np.allclose(X, reconstr, atol=tol))


def is_hermitian(X: np.ndarray, tol: float = 1e-10) -> bool:
    return bool(np.allclose(X, X.conj().T, atol=tol))


def commutes_with_C3(U: np.ndarray, tol: float = 1e-10) -> bool:
    return bool(np.allclose(U @ C, C @ U, atol=tol))


def fourier_basis() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Eigenbasis of C: |chi_1>, |chi_omega>, |chi_omega_bar>.
    C |chi_chi> = chi |chi_chi>."""
    v1 = np.array([1, 1, 1], dtype=complex) / np.sqrt(3)
    vw = np.array([1, omega, omega_bar], dtype=complex) / np.sqrt(3)
    vwb = np.array([1, omega_bar, omega], dtype=complex) / np.sqrt(3)
    return v1, vw, vwb


# ----------------------------------------------------------------------
# Section 1: retained inputs sanity check
# ----------------------------------------------------------------------


def section1_retained_inputs() -> None:
    section("Section 1: Retained inputs sanity check")

    # C_3 cyclic shift retained per BZ-corner forcing theorem
    check("1.1 C is unitary",
          np.allclose(C @ C.conj().T, I3))
    check("1.2 C has order 3",
          np.allclose(np.linalg.matrix_power(C, 3), I3))

    eigs = np.linalg.eigvals(C)
    eigs_sorted = sorted(eigs, key=lambda z: np.angle(z))
    expected = sorted([1.0 + 0j, omega, omega_bar], key=lambda z: np.angle(z))
    check("1.3 C eigenvalues are {1, omega, omega_bar}",
          np.allclose(eigs_sorted, expected))

    # Hermitian circulant test
    H = hermitian_circulant(1.7, 0.5 + 0.3j)
    check("1.4 H = aI + bC + b̄C² is Hermitian",
          is_hermitian(H))
    check("1.5 H is circulant (in span{I, C, C²})",
          is_circulant(H))

    # A1-condition reference value
    a_A1 = 1.0
    b_A1_mag = 1.0 / np.sqrt(2)
    H_A1 = hermitian_circulant(a_A1, b_A1_mag + 0j)
    check("1.6 A1 ratio |b|²/a² = 1/2 yields valid Hermitian circulant",
          is_hermitian(H_A1) and is_circulant(H_A1))

    # Per-site Pauli sanity (retained per-site uniqueness)
    check("1.7 sigma_3 has eigenvalues {-1, +1}",
          np.allclose(sorted(np.linalg.eigvals(sigma_3).real), [-1.0, 1.0]))
    check("1.8 per-site qubit U(1): exp(i theta sigma_3 / 2) is in U(2)",
          np.allclose(
              np.linalg.det(
                  np.cos(0.7) * sigma_0 + 1j * np.sin(0.7) * sigma_3),
              np.exp(1j * 0)))


# ----------------------------------------------------------------------
# Section 2: V1 — Per-site phase with C_3-character-graded angle
# ----------------------------------------------------------------------


def section2_V1_character_graded_phase() -> None:
    section("Section 2: V1 — C_3-character-graded per-site phase")

    # The proposal: for the three sites supporting hw=1, apply
    #   per-site phase exp(i theta * chi_k * sigma_3 / 2)
    # with chi_k in {0, +1, -1} = C_3-character at corner k.
    #
    # The action on H_hw=1 = C^3:
    #   |X_k> -> exp(i theta * chi_k / 2) |X_k>
    # i.e., a diagonal unitary U_theta = diag(e^{i theta * chi_1 / 2}, ...)
    #
    # On M_3(C) this acts by conjugation A -> U_theta A U_theta^*.
    # The induced action on circulants A^{C_3} is generated by the
    # commutator with diag(0, +1, -1)/2 (the generator of U_theta).

    # Build the generator G_chi = diag(0, +1, -1) (rescaled out the 1/2)
    G_chi = np.diag([0.0, 1.0, -1.0]).astype(complex)

    # Test 2.1: U_theta = exp(i theta G_chi / 2) is unitary
    theta = 0.7
    U_theta = np.diag(np.exp(1j * theta * np.array([0, 1, -1]) / 2.0)).astype(complex)
    check("2.1 U_theta(character-graded) is unitary",
          np.allclose(U_theta @ U_theta.conj().T, I3))

    # Test 2.2: U_theta does NOT commute with C_3 (G_chi has a C_3 character
    # +1 only on the trivial component, so it commutes with C iff it is
    # constant — but G_chi has nonzero (chi=±1) entries that get permuted
    # by C, so [U_theta, C] != 0).
    check("2.2 U_theta(character-graded) does NOT commute with C",
          not np.allclose(U_theta @ C, C @ U_theta))

    # Test 2.3: The action A -> U_theta A U_theta^* on circulants does NOT
    # preserve circulant structure — it kicks A^{C_3} OUT of A^{C_3}.
    H_test = hermitian_circulant(1.0, 0.5 + 0.3j)
    H_after = U_theta @ H_test @ U_theta.conj().T
    check("2.3 U_theta·circulant·U_theta^* is NOT circulant (action breaks A^{C_3})",
          not is_circulant(H_after))

    # Test 2.4: Per-site phase NOT being symmetric under C_3 means the lift
    # of "per-site qubit U(1)" cannot be uniformly applied across sites
    # without breaking C_3-equivariance. The "C_3-character-graded" angle
    # IS retained per-site qubit U(1), but the per-site choice of angle is
    # NOT a retained operation.
    #
    # The site-by-site phase choice involves ASSIGNING characters to sites.
    # But "site index" on the BZ-corner triplet is C_3-permuted; assigning
    # different angles by character means BREAKING C_3 — exactly what the
    # action MUST preserve to be a candidate for U(1)_b on A^{C_3}.

    # Verify: any C_3-equivariant per-site phase choice must give the SAME
    # angle to all three corners. That collapses U_theta to a global scalar
    # = trivial on M_3(C).

    # Test 2.5: If we demand the per-site phase be C_3-equivariant
    # (i.e., the angle assignment to sites is preserved by C_3 cyclic shift),
    # then all three angles are equal: theta_1 = theta_2 = theta_3 = theta.
    # The resulting action is exp(i theta) * I = scalar on H_hw=1.
    U_uniform = np.exp(1j * theta) * I3
    check("2.5 C_3-equivariant per-site phase = uniform = scalar on H_hw=1",
          np.allclose(U_uniform, np.exp(1j * theta) * I3) and
          commutes_with_C3(U_uniform))
    check("2.6 Uniform scalar acts trivially on M_3(C) (conjugation is identity)",
          np.allclose(conjugation(hermitian_circulant(1.0, 0.5 + 0.3j), U_uniform),
                      hermitian_circulant(1.0, 0.5 + 0.3j)))

    # Conclusion 2.7: V1 fails by C_3-equivariance constraint.
    # Either the per-site angle is C_3-equivariant (=> trivial scalar on H_hw=1),
    # or it is non-equivariant (=> breaks C_3, taking us OUT of the C_3-fixed
    # frame where A^{C_3} is defined).
    print("  >> V1 verdict: character-graded per-site phase either reduces")
    print("     to a scalar (trivial) or breaks C_3 equivariance.")
    print("     CANNOT supply U(1)_b on A^{C_3}.")


# ----------------------------------------------------------------------
# Section 3: V2 — Bimodule action on M_3(C)
# ----------------------------------------------------------------------


def section3_V2_bimodule_action() -> None:
    section("Section 3: V2 — Bimodule action distinct from conjugation")

    # Bimodule structure: M_3(C) acts on itself by left and right
    # multiplication. A "left-module-only" action L_U: A -> U·A is NOT
    # an algebra automorphism (it doesn't preserve products: L_U(AB) =
    # U·A·B ≠ L_U(A)·L_U(B) = U·A·U·B in general).
    #
    # Question: does retained per-site qubit U(1) act as a left-module
    # action L_U on M_3(C) on hw=1 that gives U(1)_b on the b-doublet?

    theta = 0.5
    # Pick a U commuting with C_3 (to preserve A^{C_3}):
    # U = e^{i theta} * I (only such U commuting with C is scalar on hw=1
    # if we want U(1) action; or U could be a circulant unitary).

    # Test 3.1: The "trivial" left-module action U = e^{i theta} * I on M_3(C)
    # gives L_U(A) = e^{i theta} * A. This is NOT an algebra automorphism
    # (preserves linearity but not multiplication — except for U = I).
    U = np.exp(1j * theta) * I3
    A = hermitian_circulant(1.0, 0.5 + 0.3j)
    B = hermitian_circulant(0.5, 0.2 - 0.1j)
    L_U_A = U @ A
    L_U_B = U @ B
    L_U_AB = U @ (A @ B)
    not_aut = not np.allclose(L_U_AB, L_U_A @ L_U_B)
    check("3.1 Left-module L_U: A -> U·A is NOT an algebra-automorphism",
          not_aut)

    # Test 3.2: But L_U is a LINEAR map on M_3(C). Its restriction to A^{C_3}
    # acts as multiplication by U on the left. For U = e^{i theta} * I,
    # L_U(aI + bC + b̄C²) = a·e^{i theta} I + b·e^{i theta} C + b̄·e^{i theta} C².
    # This is a UNIFORM phase on (a, b, b̄), NOT a U(1)_b action that
    # rotates b alone (preserving a).
    H_a = hermitian_circulant(1.0, 0.5 + 0.3j)
    L_U_H = U @ H_a
    # Check it's still in span{I, C, C²} but with all coefficients phase-shifted
    # by U:
    a_new = np.trace(L_U_H) / 3.0
    b_new = np.trace(L_U_H @ C2) / 3.0
    expected_a = 1.0 * np.exp(1j * theta)
    expected_b = (0.5 + 0.3j) * np.exp(1j * theta)
    check("3.2 L_U on circulant (U=scalar) gives uniform phase on (a, b)",
          np.isclose(a_new, expected_a) and np.isclose(b_new, expected_b))

    # The left-module action with scalar U does NOT separate the trivial
    # isotype (a-coefficient) from the doublet (b-coefficient). Both get
    # the SAME phase, so this is NOT U(1)_b (which acts only on b).

    # Test 3.3: Try non-scalar U commuting with C_3 (e.g., U = unitary in
    # circulant subalgebra). The most general U commuting with C is itself
    # circulant: U = u_0 I + u_1 C + u_2 C² with |u_0|^2 + |u_1|^2 + |u_2|^2
    # appropriately normalized.
    # In the Fourier basis (eigenbasis of C), U is diag(lambda_1, lambda_omega,
    # lambda_omega_bar) where lambda_chi = u_0 + u_1 chi + u_2 chi^2 and each
    # |lambda_chi| = 1.
    #
    # As a U(1) subgroup, the maximal compact U(1) inside circulant unitaries
    # has 3 independent angles (u(1) x u(1) x u(1) = 3-torus). Each angle is
    # a different per-character phase.
    lambda_1, lambda_w, lambda_wb = np.exp(1j * 0.3), np.exp(1j * 0.5), np.exp(1j * (-0.8))
    # Build U as circulant by inverse Fourier:
    # U_circ in Fourier basis = diag(lambda_1, lambda_w, lambda_wb)
    F = np.column_stack(fourier_basis())
    U_circ = F @ np.diag([lambda_1, lambda_w, lambda_wb]) @ F.conj().T
    check("3.3a U_circ (circulant unitary) commutes with C_3",
          commutes_with_C3(U_circ))
    check("3.3b U_circ is unitary",
          np.allclose(U_circ @ U_circ.conj().T, I3))

    # Now check: left-module action L_{U_circ} on a circulant H = aI + bC + b̄C².
    # Result: U_circ · H is a product of two circulants in M_3(C), hence again
    # a circulant. So L preserves A^{C_3} only when U is itself in A^{C_3}.
    H = hermitian_circulant(1.0, 0.5 + 0.3j)
    L_H = U_circ @ H
    check("3.3c L_{U_circ}(circulant) is circulant (since U_circ in A^{C_3})",
          is_circulant(L_H))

    # Now restricted to A^{C_3} ≅ C^3 (via Fourier), L_{U_circ} acts as
    # diag(lambda_1, lambda_w, lambda_wb). This is a 3-torus T^3 action on
    # the three characters separately. NOT specifically U(1)_b which is the
    # SO(2) phase rotation on (Re b, Im b) = real isotype rotation in the
    # (chi_omega, chi_omega_bar) plane.

    # Test 3.4: For L_{U_circ} to act as U(1)_b on the b-doublet, we need
    # lambda_omega and lambda_omega_bar to be CONJUGATE (so that real
    # parametrization (Re b, Im b) gets rotated). i.e.,
    # lambda_omega_bar = (lambda_omega)*. Combined with lambda_1 = 1 (no
    # action on a), this gives:
    #
    #   U_b(theta) := F · diag(1, e^{i theta}, e^{-i theta}) · F^*
    #
    # in M_3(C). This U_b is NOT a SCALAR on H_hw=1 — it's a specific 1D
    # subgroup of the 3-torus of circulant unitaries.
    # Build it:
    theta_b = 0.7
    U_b_diag = np.diag([1.0, np.exp(1j * theta_b), np.exp(-1j * theta_b)]).astype(complex)
    U_b = F @ U_b_diag @ F.conj().T
    check("3.4a U_b(theta) commutes with C_3",
          commutes_with_C3(U_b))
    check("3.4b U_b(theta) is unitary",
          np.allclose(U_b @ U_b.conj().T, I3))

    # CRUCIAL TEST: does conjugation by U_b act as U(1)_b on (a, b)?
    # alpha_{U_b}(aI + bC + b̄C²) should give aI + e^{i theta_b} bC + e^{-i theta_b} b̄C².
    H_ab = hermitian_circulant(1.0, 0.5 + 0.3j)
    H_after_U_b = conjugation(H_ab, U_b)
    a_after = np.trace(H_after_U_b) / 3.0
    b_after = np.trace(H_after_U_b @ C2) / 3.0
    bbar_after = np.trace(H_after_U_b @ C) / 3.0
    print(f"  diag info: U_b conjugation on (a, b) = (a={1.0}, b={0.5+0.3j}) ->")
    print(f"             a_after = {a_after:.6f}")
    print(f"             b_after = {b_after:.6f}")
    print(f"             expected a = 1.0, b = (0.5 + 0.3j) * e^{{i theta_b}} = ", end="")
    print(f"{(0.5 + 0.3j) * np.exp(1j * theta_b):.6f}")

    # WAIT: U_b commutes with C_3, so conjugation by U_b PRESERVES the
    # circulant subspace AND fixes a (the trivial-character coefficient).
    # By Probe 14, conjugation by C_3-commuting unitary is TRIVIAL on
    # circulant subspace.
    #
    # Let's verify: alpha_{U_b}(aI) = U_b · aI · U_b^* = a · U_b · U_b^* = aI.
    # alpha_{U_b}(C) = U_b · C · U_b^*. Since [U_b, C] = 0, this = C.
    # So alpha_{U_b}(aI + bC + b̄C²) = aI + bC + b̄C². TRIVIAL.
    expected_trivial = H_ab
    check("3.4c Conjugation by U_b acts TRIVIALLY on circulants (Probe 14)",
          np.allclose(H_after_U_b, expected_trivial))

    # Test 3.5: The LEFT-MODULE action L_{U_b}(H) = U_b · H is NOT trivial
    # (it's multiplication of circulants in M_3(C)). But this is NOT an
    # algebra-automorphism — it's a left-module action.
    L_U_b_H = U_b @ H_ab
    check("3.5a Left-module L_{U_b}(H) = U_b · H is non-trivial on circulants",
          not np.allclose(L_U_b_H, H_ab))
    check("3.5b L_{U_b}(H) is still a circulant (product of two circulants)",
          is_circulant(L_U_b_H))

    # Decompose L_{U_b}(H) into (a, b)-coefficients: L_{U_b} acts on A^{C_3} ≅ C³
    # via Fourier as element-wise multiplication by (1, e^{i theta_b}, e^{-i theta_b}).
    # So in (a, b, b̄) parametrization:
    #   L_{U_b}(aI + bC + b̄C²) corresponds to multiplying the trivial-character
    #   eigenvalue (= a + 2 Re b) by 1, the omega-character eigenvalue
    #   (= a + 2 Re(b omega)) by e^{i theta_b}, and the omega-bar eigenvalue
    #   (= a + 2 Re(b omega-bar)) by e^{-i theta_b}.
    # This is NOT a clean (a, b) -> (a, e^{i theta_b} b) action — it MIXES a and b.

    # Verify: the a-coefficient of L_{U_b}(H) is NOT equal to the a-coefficient of H.
    a_orig = np.trace(H_ab) / 3.0
    a_after_L = np.trace(L_U_b_H) / 3.0
    print(f"  diag info: L_{{U_b}}(H): a_before = {a_orig:.6f}, a_after = {a_after_L:.6f}")
    check("3.5c Left-module action MIXES a and b (NOT a clean U(1)_b)",
          not np.isclose(a_orig, a_after_L))

    print("  >> V2 verdict: bimodule (left-module) action by U_circ in A^{C_3}")
    print("     mixes a and b coefficients. NOT a clean U(1)_b on b-doublet.")
    print("     Conjugation by same U_circ is trivial on A^{C_3} (Probe 14).")
    print("     Neither pure left-module nor conjugation gives U(1)_b.")


# ----------------------------------------------------------------------
# Section 4: V3 — Twisted conjugation X -> UXV^* with U != V
# ----------------------------------------------------------------------


def section4_V3_twisted_conjugation() -> None:
    section("Section 4: V3 — Twisted conjugation with U != V")

    # Twisted conjugation: alpha_{U,V}(X) = U · X · V^*.
    # For U = V this is conjugation. For U != V it is generally NOT an
    # algebra-automorphism.
    #
    # On A^{C_3}, alpha_{U,V}(I) = U V^*. For the action to fix the unit
    # element (i.e., be unital), we need U V^* = I, i.e., U = V. That's
    # conjugation.
    #
    # If we DROP the unitality requirement, alpha_{U,V} is a linear map
    # M_3(C) -> M_3(C) but not an algebra-action; in particular, it's not
    # a group homomorphism for the U(1) group structure. So it doesn't
    # define a U(1) ACTION.

    # Test 4.1: For the twisted action to define a 1-parameter group,
    # we need U_theta V_theta^* = (U_1 V_1^*)^theta = something with
    # group structure. Setting W := U V^*, the action X -> W · X · I = W X
    # is just LEFT multiplication by W (the V^* on the right cancels with
    # the requirement that each action is X -> something X something^*).
    # This is just V2 (left-module) again.

    # Symbolic statement: alpha_{U,V}(X) = U X V^*. For this to be a
    # group action of theta -> alpha_{U(theta), V(theta)}, we need
    # alpha_{U(theta_1), V(theta_1)} ∘ alpha_{U(theta_2), V(theta_2)}
    #   = alpha_{U(theta_1+theta_2), V(theta_1+theta_2)}.
    # Compute LHS:
    #   alpha_{U_1,V_1}(alpha_{U_2,V_2}(X))
    #   = U_1 · (U_2 X V_2^*) · V_1^*
    #   = (U_1 U_2) X (V_1 V_2)^*
    # So composition gives multiplicative U_1 U_2 and V_1 V_2, which IS a
    # group action provided U(theta) and V(theta) are 1-parameter subgroups
    # of U(3) (which they are, individually).
    # Verify numerically:
    theta1, theta2 = 0.4, 0.7
    # Define an example U,V acting in the eigenbasis of C
    F = np.column_stack(fourier_basis())
    # U(theta) = diag(e^{i a theta}, e^{i b theta}, e^{i c theta}) in Fourier basis
    a_U, b_U, c_U = 0.0, 1.0, -1.0  # so U(theta) = diag(1, e^{i theta}, e^{-i theta})
    a_V, b_V, c_V = 0.0, -1.0, 1.0  # so V(theta) = diag(1, e^{-i theta}, e^{i theta})

    def U_theta(t: float) -> np.ndarray:
        return F @ np.diag(np.exp(1j * t * np.array([a_U, b_U, c_U]))) @ F.conj().T

    def V_theta(t: float) -> np.ndarray:
        return F @ np.diag(np.exp(1j * t * np.array([a_V, b_V, c_V]))) @ F.conj().T

    def twisted(X: np.ndarray, t: float) -> np.ndarray:
        return U_theta(t) @ X @ V_theta(t).conj().T

    X = hermitian_circulant(1.0, 0.5 + 0.3j)
    LHS = twisted(twisted(X, theta2), theta1)
    RHS = twisted(X, theta1 + theta2)
    check("4.1 Twisted conjugation IS a 1-parameter group action (associative)",
          np.allclose(LHS, RHS))

    # Test 4.2: The fixed-element property — does twisted conjugation send
    # I to itself? alpha_{U,V}(I) = U I V^* = U V^*.
    # For our (a_U, b_U, c_U) = (0, 1, -1) and (a_V, b_V, c_V) = (0, -1, 1):
    # U V^* in Fourier basis = diag(1, e^{i theta}, e^{-i theta}) ·
    #                          diag(1, e^{i theta}, e^{-i theta}) = diag(1, e^{2i theta}, e^{-2i theta})
    # which is NOT the identity for theta != 0.
    UV_dag = U_theta(0.5) @ V_theta(0.5).conj().T
    check("4.2 Twisted action does NOT preserve I (alpha_{U,V}(I) = UV^* != I)",
          not np.allclose(UV_dag, I3))

    # Test 4.3: The twisted action does NOT preserve the algebra product:
    # alpha_{U,V}(AB) = U A B V^*
    # alpha_{U,V}(A) · alpha_{U,V}(B) = U A V^* · U B V^* = U A (V^* U) B V^*
    # These are equal iff V^* U commutes with B for all B, i.e., V^* U = scalar.
    # That requires U = lambda V for some scalar lambda — back to conjugation
    # times scalar.
    A = hermitian_circulant(0.7, 0.4 + 0.1j)
    B = hermitian_circulant(0.3, 0.2 - 0.5j)
    lhs = twisted(A @ B, 0.6)
    rhs = twisted(A, 0.6) @ twisted(B, 0.6)
    check("4.3 Twisted action is NOT multiplicative (NOT an algebra-automorphism)",
          not np.allclose(lhs, rhs))

    # Test 4.4: Whether twisted conjugation acts as U(1)_b on (a, b).
    # On A^{C_3} ≅ C^3 (Fourier basis), twisted by our example:
    #   U(theta) = diag(1, e^{i theta}, e^{-i theta})
    #   V^*(theta) = diag(1, e^{i theta}, e^{-i theta})  (since V = its conjugate)
    # In Fourier basis, X (a circulant) is diag(lambda_1, lambda_w, lambda_wb).
    # Then twisted(X, theta) in Fourier basis = U X V^*
    #   = diag(lambda_1, lambda_w · e^{2i theta}, lambda_wb · e^{-2i theta})
    # This MULTIPLIES eigenvalues at characters omega, omega_bar by phases.
    # But these are EIGENVALUES of H, not the (a, b) coordinates.

    # The (a, b) coordinates of a circulant relate to eigenvalues via:
    #   lambda_1 = a + 2 Re(b)  (real)
    #   lambda_w = a + 2 Re(b omega) = a - Re(b) - sqrt(3) Im(b)
    #   lambda_wb = a + 2 Re(b omega_bar) = a - Re(b) + sqrt(3) Im(b)
    #
    # Multiplying lambda_w by e^{2i theta} produces a COMPLEX eigenvalue,
    # which means the resulting X = U X V^* is NO LONGER HERMITIAN.

    H_after_twist = twisted(hermitian_circulant(1.0, 0.5 + 0.3j), 0.4)
    check("4.4a Twisted conjugation does NOT preserve Hermiticity",
          not is_hermitian(H_after_twist))

    # Test 4.5: Even ignoring Hermiticity loss, the twisted action multiplies
    # (lambda_w, lambda_wb) by phases (e^{2i theta}, e^{-2i theta}). This is
    # PHASE-rotation-on-eigenvalues, NOT phase-rotation-on-(b, b̄)-coefficients.
    # It is NOT the U(1)_b symmetry on the b-doublet.

    # Construct a candidate "twisted" lift that DOES rotate b by phase:
    # We want alpha(aI + bC + b̄C²) = aI + e^{i theta} b C + e^{-i theta} b̄ C².
    # In Fourier: in basis (chi_1, chi_omega, chi_omega_bar):
    #   X = a · diag(1, 1, 1)              ← from aI
    #     + b · diag(1, omega, omega_bar) ← from bC; coefficient of diag(0,1,0) is b·omega
    # Hmm, the Fourier diagonalization of bC is more subtle. Let me re-derive:
    # C acts on the Fourier basis by:
    #   C |chi_1> = |chi_1>, C |chi_omega> = omega |chi_omega>, C |chi_obar> = obar |chi_obar>
    # So C in Fourier basis is diag(1, omega, omega_bar).
    # Then aI + bC + b̄C² in Fourier is
    #   diag(a, a, a) + b·diag(1, omega, omega_bar) + b̄·diag(1, omega², omega_bar²)
    #   = diag(a + b + b̄, a + b·omega + b̄·omega², a + b·omega_bar + b̄·omega_bar²)
    #   = diag(a + 2 Re(b),  a + b·omega + b̄·omega_bar, a + b·omega_bar + b̄·omega)
    # (using omega² = omega_bar)
    # So the (a, b) -> (a, e^{i phi} b) action would change:
    #   lambda_1: a + 2 Re(b) -> a + 2 Re(e^{i phi} b) = a + 2 Re(b)cos(phi) - 2 Im(b)sin(phi)
    #   lambda_w: a + b omega + b̄ omega_bar -> a + e^{i phi} b omega + e^{-i phi} b̄ omega_bar
    #   lambda_wb: similar with omega_bar
    #
    # CRITICAL: The transformation b -> e^{i phi} b changes ALL THREE
    # eigenvalues of H (since each eigenvalue depends on Re(b), Im(b)
    # combinations). It is NOT a purely-eigenvalue-multiplicative transformation.
    # So no twisted conjugation in U(3) x U(3) (acting linearly in Fourier basis)
    # can implement U(1)_b on (a, b) → (a, e^{i phi} b).

    print("  >> V3 verdict: twisted conjugation is a group action but is not")
    print("     unital, not multiplicative, AND does not preserve Hermiticity.")
    print("     It acts on EIGENVALUES of H (not on (a, b) coefficients of H),")
    print("     so it cannot implement the b -> e^{i phi} b U(1)_b symmetry.")


# ----------------------------------------------------------------------
# Section 5: V4 — Pseudoscalar-twisted action
# ----------------------------------------------------------------------


def section5_V4_pseudoscalar_twisted() -> None:
    section("Section 5: V4 — Pseudoscalar-twisted action")

    # Pseudoscalar omega = e_1 e_2 e_3 in Cl(3). On per-site C^2,
    # omega = sigma_1 · sigma_2 · sigma_3 = i · I (this is the standard
    # identification, see AXIOM_FIRST_CL3_PER_SITE_UNIQUENESS_THEOREM_NOTE).
    omega_per_site = sigma_1 @ sigma_2 @ sigma_3
    expected = 1j * sigma_0
    check("5.1 Pseudoscalar omega = e_1 e_2 e_3 = i·I on per-site C^2",
          np.allclose(omega_per_site, expected))

    # Test 5.2: Since omega is a SCALAR (i·I) on per-site C^2, any
    # "pseudoscalar-twisted" combination omega_x ⊗ omega_y ⊗ ... = i^N
    # = ±1 or ±i. In particular, omega^N is in the global Z_4 center of
    # the per-site Pauli group, NOT a continuous U(1).
    #
    # Combining omega with continuous per-site phase gives:
    #   exp(i theta omega/2) on per-site C^2 = exp(i theta · i / 2) · I
    #     = exp(-theta/2) · I (NOT unitary unless theta = 0!)
    # Because omega = i·I has imaginary "value", the exponentiation gives
    # a real-decay factor, not a phase.
    #
    # To make a unitary, we'd need omega-ITSELF, not its scalar value:
    #   exp(i theta omega) where omega is treated as the algebra element
    #   omega = i·I. Then exp(i theta · i I) = exp(-theta) · I, again non-unitary.

    # Test 5.3: Pseudoscalar twist of conjugation: alpha_{omega^k}(X) = omega^k X omega^{-k}.
    # Since omega = i·I is central, omega^k X omega^{-k} = X for all k.
    # So pseudoscalar twist of conjugation is TRIVIAL.
    omega_lifted = 1j * I3  # On hw=1 (= 3-dim representation), omega still acts as i·I
    # Note: actually on H_hw=1 (3-dim), omega's representation is determined by
    # the 3-dim faithful representation of Cl(3) -- but Cl(3) has no faithful
    # 3-dim irrep (only 2-dim Pauli or its parity conjugate). So omega on H_hw=1
    # acts as a SCALAR (since hw=1 is 1-fermion-number sector, with definite
    # chirality / pseudoscalar charge).
    X = hermitian_circulant(1.0, 0.5 + 0.3j)
    check("5.3 Pseudoscalar conjugation alpha_omega(X) = omega X omega^{-1} = X (trivial since omega scalar)",
          np.allclose(omega_lifted @ X @ omega_lifted.conj().T / np.abs(np.linalg.det(omega_lifted))**(2/3),
                      X))

    # More directly: omega_lifted = i·I commutes with everything, so conjugation
    # is trivial.
    check("5.4 omega·X = X·omega (omega is scalar, hence central)",
          np.allclose(omega_lifted @ X, X @ omega_lifted))

    # Test 5.5: Pseudoscalar-modified per-site qubit U(1): exp(i theta sigma_3 omega / 2)
    # on per-site C^2. Since omega = i·I:
    #   exp(i theta sigma_3 · i · I / 2) = exp(-theta sigma_3 / 2) = cosh(theta/2) I - sinh(theta/2) sigma_3.
    # NOT unitary. So pseudoscalar twist of per-site qubit U(1) gives a NON-COMPACT
    # SL(2,R) hyperbolic flow, not a U(1).
    theta = 0.4
    twist_op = np.cos(1j * theta / 2) * sigma_0 + np.sin(1j * theta / 2) * sigma_3
    # Equivalent: cos(i theta/2) = cosh(theta/2), sin(i theta/2) = i sinh(theta/2)
    expected_twist = np.cosh(theta / 2) * sigma_0 - np.sinh(theta / 2) * sigma_3
    # WAIT — let me recompute. exp(-theta sigma_3 / 2):
    expected_twist_correct = np.diag([np.exp(-theta / 2), np.exp(theta / 2)]).astype(complex)
    check("5.5 Pseudoscalar-twisted per-site U(1) is NON-UNITARY (hyperbolic flow)",
          not np.allclose(expected_twist_correct @ expected_twist_correct.conj().T, sigma_0))

    print("  >> V4 verdict: pseudoscalar omega = e_1 e_2 e_3 = i·I is CENTRAL")
    print("     and SCALAR on the framework's faithful Cl(3) irreps. Pseudoscalar-")
    print("     twisted conjugation is therefore TRIVIAL (central elements commute).")
    print("     Pseudoscalar-twisted exponentiation gives non-unitary hyperbolic flow,")
    print("     not a U(1). Either way, V4 cannot supply U(1)_b.")


# ----------------------------------------------------------------------
# Section 6: V5 — Local-to-global lift via spatial site-position phase
# ----------------------------------------------------------------------


def section6_V5_spatial_phase_lift() -> None:
    section("Section 6: V5 — Spatial site-position-dependent phase")

    # Proposal: per-site phase exp(i theta · n) with n indexing site location
    # gives a "shift" rather than conjugation. On lattice fermion modes,
    # this is a momentum-shift gauge transformation:
    #   |k> -> |k + theta·n_0> for some direction n_0.
    #
    # On the FINITE BZ corner space {(n_1 pi, n_2 pi, n_3 pi) : n_i in {0,1}},
    # there are only 8 corners. A continuous-theta shift either:
    #   (i) preserves all corners (= integer multiple of pi shift, theta = m pi):
    #       discrete Z_2 action per direction, NOT a U(1).
    #   (ii) takes corners off the discrete set:
    #       not a well-defined action on H_hw=1 = span{X_1, X_2, X_3}.

    # Test 6.1: Build the BZ-corner shift operator. Let T_d = translation by
    # one site in direction d. On corner |X_k> = |hw=1 mode k>, T_d |X_k>
    # acts as a phase e^{i k · d} = e^{i pi n_k,d}. Per the M_3(C) generation
    # in THREE_GENERATION_OBSERVABLE_THEOREM_NOTE:
    #   T_x: diag(-1, +1, +1), T_y: diag(+1, -1, +1), T_z: diag(+1, +1, -1)
    T_x = np.diag([-1.0, 1.0, 1.0]).astype(complex)
    T_y = np.diag([1.0, -1.0, 1.0]).astype(complex)
    T_z = np.diag([1.0, 1.0, -1.0]).astype(complex)
    check("6.1a T_x is unitary",
          np.allclose(T_x @ T_x.conj().T, I3))
    check("6.1b T_x · T_y · T_z = -I (sublattice parity character at hw=1)",
          np.allclose(T_x @ T_y @ T_z, -I3))

    # Test 6.2: The FRACTIONAL/CONTINUOUS-theta version exp(i theta · n_x · sigma_3 / 2)
    # at lattice site x acts as exp(i theta · k · n_x) on momentum-eigenstate |k>.
    # Restricted to hw=1 = single particle at corner momentum: |X_k> picks up
    # phase exp(i theta · k_X_k) where k_X_k is the position-projection of the
    # corner momentum.
    # For corner X_k = (pi, 0, 0) (or permutations), k · n_x = pi · (x_1)
    # for example.
    # Translating the WHOLE lattice by theta in direction n_0 = e_1 gives
    # |k> -> e^{i k_1 theta} |k>, which is JUST a phase on momentum eigenstates.
    # Restricted to hw=1 this gives:
    #   |X_1 = (pi,0,0)> -> e^{i pi theta} |X_1>  (IF this stays in hw=1)
    #   |X_2 = (0,pi,0)> -> e^{0} |X_2> = |X_2>
    #   |X_3 = (0,0,pi)> -> e^{0} |X_3> = |X_3>
    # So the action U_theta = diag(e^{i pi theta}, 1, 1) on hw=1 = C^3.

    # Test 6.2: This U_theta does NOT commute with C_3.
    theta = 0.5
    U_shift = np.diag([np.exp(1j * np.pi * theta), 1.0, 1.0]).astype(complex)
    check("6.2a U_shift is unitary",
          np.allclose(U_shift @ U_shift.conj().T, I3))
    check("6.2b U_shift does NOT commute with C_3",
          not commutes_with_C3(U_shift))

    # Test 6.3: Conjugation by U_shift on circulants takes them OUT of A^{C_3}.
    H = hermitian_circulant(1.0, 0.5 + 0.3j)
    H_after_shift = conjugation(H, U_shift)
    check("6.3 conjugation by U_shift on circulant breaks A^{C_3} structure",
          not is_circulant(H_after_shift))

    # Test 6.4: To recover a C_3-equivariant action, we'd need to combine
    # all three direction shifts symmetrically: U_full(theta) = T_x^theta T_y^theta T_z^theta.
    # In matrix form on hw=1: T_x · T_y · T_z = diag(-1, -1, -1) = -I (already
    # verified at 6.1b). For continuous theta:
    #   U_full(theta) = diag((-1)^theta, (-1)^theta, (-1)^theta) = (-1)^theta · I.
    # This is a SCALAR. Trivial on M_3(C).

    # Verify:
    sign_theta = np.exp(1j * np.pi * theta)  # (-1)^theta = e^{i pi theta}
    U_full = sign_theta * I3
    H_after_full = conjugation(H, U_full)
    check("6.4 C_3-symmetrized spatial shift = scalar = trivial conjugation on M_3(C)",
          np.allclose(H_after_full, H))

    # Test 6.5: No matter how we choose "site indexing function n", the
    # combined per-site phase U(theta) = ⊗_x exp(i theta · n(x) · sigma_3 / 2)
    # restricted to hw=1 acts as a UNITARY on C^3. Any unitary on C^3 that
    # is C_3-EQUIVARIANT (commutes with C) is itself in the circulant
    # algebra A^{C_3} (Schur). Conjugation by such a unitary is TRIVIAL on
    # A^{C_3} (Probe 14). So V5 collapses back to Probe 14's domain.

    print("  >> V5 verdict: spatial-site-position phase gives a unitary on")
    print("     H_hw=1 = C^3. Either C_3-equivariant (-> circulant unitary ->")
    print("     trivial conjugation on A^{C_3}) or non-equivariant (-> breaks")
    print("     A^{C_3} structure, action is not on circulants). Cannot supply U(1)_b.")


# ----------------------------------------------------------------------
# Section 7: STRUCTURAL OBSTRUCTION THEOREM
# ----------------------------------------------------------------------


def section7_structural_obstruction() -> None:
    section("Section 7: Structural obstruction theorem")

    # Theorem (proven inline):
    #
    # Claim: ANY continuous one-parameter unitary group {U(theta)} acting on
    # H_hw=1 = C^3 lifts to End(H_hw=1) = M_3(C) ONLY by conjugation
    # alpha_{U(theta)}(X) = U(theta) · X · U(theta)^*. There is no non-
    # conjugation lift accessible from a single state-space unitary group.
    #
    # Proof: Let phi: U(1) -> Aut(M_3(C)) be a continuous group homomorphism
    # induced from a single Hilbert-space U(1) action. Then phi(theta) acts
    # on M_3(C) as a *-algebra automorphism (preserving products and adjoints).
    # By the Skolem-Noether theorem (every *-automorphism of M_n(C) is inner),
    # phi(theta)(X) = U_alpha(theta) X U_alpha(theta)^* for some unitary
    # U_alpha(theta) on C^3, depending continuously on theta.
    #
    # If the action is induced by a single Hilbert-space U(theta), then
    # U_alpha(theta) = U(theta) up to a phase. The phase ambiguity does not
    # affect the conjugation action.
    #
    # Hence: any single-Hilbert-space-U(1) lift to M_3(C) is conjugation.
    # Probe 14 covers conjugation by C_3-commuting U: trivial on A^{C_3}.
    # So no closure of A1.
    #
    # The "non-conjugation" lifts attempted (V2 left-module, V3 twisted
    # conjugation, V4 pseudoscalar twist, V5 spatial phase) either:
    #   (a) fail to be group homomorphisms (V2: not multiplicative);
    #   (b) fail to preserve the algebra structure of M_3(C) (V3: not unital,
    #       not multiplicative, not Hermiticity-preserving);
    #   (c) collapse to scalar action / trivial conjugation (V4: pseudoscalar
    #       central; V5: C_3-symmetrized spatial = scalar);
    #   (d) require a structure that is NOT supplied by retained per-site
    #       qubit U(1) on H_lat (V1: site-by-site C_3-character grading is
    #       NOT a retained operation if we demand C_3-equivariance).

    # Verification 7.1: Skolem-Noether holds on M_3(C).
    # Pick a random *-automorphism by conjugation, verify it equals U X U^*.
    np.random.seed(17)
    Q, _ = np.linalg.qr(np.random.randn(3, 3) + 1j * np.random.randn(3, 3))
    X = hermitian_circulant(1.0, 0.5 + 0.3j)
    Y = hermitian_circulant(0.7, 0.2 + 0.6j)
    aut_X = Q @ X @ Q.conj().T
    aut_Y = Q @ Y @ Q.conj().T
    aut_XY = Q @ (X @ Y) @ Q.conj().T
    check("7.1a Conjugation by Q preserves multiplication: aut(XY) = aut(X) aut(Y)",
          np.allclose(aut_XY, aut_X @ aut_Y))
    check("7.1b Conjugation by Q preserves adjoint: aut(X^*) = aut(X)^*",
          np.allclose(Q @ X.conj().T @ Q.conj().T, (Q @ X @ Q.conj().T).conj().T))

    # Verification 7.2: The Skolem-Noether constraint forces the lift.
    # If we require:
    #   (A) phi(theta) is a *-algebra automorphism of M_3(C),
    #   (B) phi(theta) is continuous in theta,
    #   (C) phi forms a 1-parameter group: phi(s+t) = phi(s) phi(t),
    # then phi(theta) = conjugation by some U(theta) in U(3)/U(1)_phase.

    # Verification 7.3: Probe 14 covers U(theta) commuting with C_3.
    # Build the maximal C_3-commuting U(1) inside U(3): the Fourier-diagonal
    # subgroup. Its restriction to A^{C_3} acts as scalar multiplication on
    # each character isotype (= 3 independent phases on chi_1, chi_omega,
    # chi_omega_bar).
    F = np.column_stack(fourier_basis())
    # An arbitrary C_3-commuting U(theta) = F · diag(e^{i a theta}, e^{i b theta},
    # e^{i c theta}) · F^*.
    a_p, b_p, c_p = 0.0, 0.7, -0.4
    theta = 0.6
    U_C3eq = F @ np.diag(np.exp(1j * theta * np.array([a_p, b_p, c_p]))) @ F.conj().T
    check("7.3a U_C3eq commutes with C",
          commutes_with_C3(U_C3eq))
    check("7.3b U_C3eq is unitary",
          np.allclose(U_C3eq @ U_C3eq.conj().T, I3))

    # Verification 7.4: Conjugation by U_C3eq ON CIRCULANTS = TRIVIAL,
    # because U_C3eq is itself in the circulant algebra A^{C_3} (which is
    # commutative as an algebra over C).
    H = hermitian_circulant(1.0, 0.5 + 0.3j)
    H_after = conjugation(H, U_C3eq)
    check("7.4 Conjugation by C_3-commuting U is TRIVIAL on circulants (A^{C_3} commutative)",
          np.allclose(H_after, H))

    # Verification 7.5: Conjugation by NON-C_3-commuting U breaks A^{C_3}.
    # Pick U not commuting with C, conjugate H, show result is non-circulant.
    np.random.seed(18)
    Mat = np.random.randn(3, 3) + 1j * np.random.randn(3, 3)
    Q2, _ = np.linalg.qr(Mat)
    while commutes_with_C3(Q2):
        Mat = np.random.randn(3, 3) + 1j * np.random.randn(3, 3)
        Q2, _ = np.linalg.qr(Mat)
    H_break = conjugation(H, Q2)
    check("7.5 Conjugation by NON-C_3-commuting Q breaks A^{C_3} (not circulant)",
          not is_circulant(H_break))

    # Verification 7.6: The U(1)_b symmetry (b -> e^{i phi} b, a -> a) on
    # circulants H = aI + bC + b̄C² acts in Fourier basis as:
    #   diag(a + 2 Re(b),
    #        a + b·omega + b̄·omega_bar,
    #        a + b·omega_bar + b̄·omega)
    # Under b -> e^{i phi} b:
    #   lambda_1 -> a + 2 Re(e^{i phi} b) = a + 2|b|cos(phi + arg b)
    #   lambda_w -> a + e^{i phi} b·omega + e^{-i phi} b̄·omega_bar
    #             = 2 Re(a/2 + e^{i phi} b · omega)
    #   lambda_wb -> similar
    # KEY OBSERVATION: U(1)_b acts NON-LINEARLY on the eigenvalues
    # (lambda_1, lambda_w, lambda_wb). It is NOT a linear *-automorphism
    # of M_3(C). It IS a linear automorphism of A^{C_3} as a 4-real-dim
    # vector space (parametrized by (a, Re b, Im b)).

    # Test directly: U(1)_b on (a, b)
    a_val = 1.0
    b_val = 0.5 + 0.3j
    phi = 0.7
    H_orig = hermitian_circulant(a_val, b_val)
    H_rot = hermitian_circulant(a_val, b_val * np.exp(1j * phi))
    eigs_orig = sorted(np.linalg.eigvals(H_orig).real)
    eigs_rot = sorted(np.linalg.eigvals(H_rot).real)
    print(f"  diag info: U(1)_b rotation by phi={phi}: ")
    print(f"    eigs(H_orig) = {eigs_orig}")
    print(f"    eigs(H_rot)  = {eigs_rot}")
    # The eigenvalues CHANGE (different multiset), confirming U(1)_b is
    # NOT a unitary similarity (which would preserve the spectrum).
    check("7.6 U(1)_b on (a, b) does NOT preserve the spectrum of H",
          not np.allclose(eigs_orig, eigs_rot))

    # Verification 7.7: A spectrum-non-preserving linear map M_3(C) -> M_3(C)
    # can NEVER be implemented by conjugation (which is unitary similarity
    # = spectrum-preserving). Hence U(1)_b on (a, b) is fundamentally NOT
    # an algebra-automorphism action. To realize it, we'd need a NON-unitary,
    # NON-algebra-automorphism transformation. Such transformations are NOT
    # generated by retained per-site qubit U(1) (which is unitary by virtue
    # of being a unitary subgroup of U(2) per site).

    print("  >> Structural obstruction: U(1)_b is a SPECTRUM-NON-PRESERVING")
    print("     transformation on M_3(C). It cannot be implemented by any")
    print("     unitary similarity (= conjugation). Hence no unitary lift")
    print("     of any retained continuous symmetry can produce U(1)_b.")
    print("     This sharpens Probe 14: not just 'every retained U(1) acts as")
    print("     conjugation', but more strongly 'U(1)_b is intrinsically")
    print("     non-unitary as a transformation on M_3(C)'.")


# ----------------------------------------------------------------------
# Section 8: Convention-robustness check
# ----------------------------------------------------------------------


def section8_convention_robustness() -> None:
    section("Section 8: Convention-robustness check")

    # The candidate non-conjugation lifts in V1-V5 all fail under independent
    # convention checks:

    # Test 8.1: Scale invariance. The candidate U(1)_b on (a, b) preserves
    # |b|^2 / a^2 (since rotation by phase preserves magnitude). Verify
    # numerically.
    a_val = 1.0
    b_val = 0.5 + 0.3j
    phi = 0.5
    ratio_orig = np.abs(b_val) ** 2 / a_val ** 2
    b_rot = b_val * np.exp(1j * phi)
    ratio_rot = np.abs(b_rot) ** 2 / a_val ** 2
    check("8.1 U(1)_b preserves |b|^2 / a^2 (compatible with A1-condition target)",
          np.isclose(ratio_orig, ratio_rot))

    # Test 8.2: Basis change C -> C^{-1} = C^2. The retained C_3-action
    # generator is C, but C^2 is also a C_3-generator. Switching changes
    # the role of (omega, omega_bar) in the Fourier basis but not the (1,2)
    # vs (1,1) weighting question.
    # Verify a circulant under C is also circulant under C^2:
    H = hermitian_circulant(1.0, 0.5 + 0.3j)
    # Circulant in span{I, C, C^2} = circulant in span{I, C^2, C} (same algebra).
    # Verify it's still in the C^2 commutant.
    check("8.2 Circulant H commutes with C^2 (basis change preserves A^{C_3})",
          np.allclose(H @ C2, C2 @ H))

    # Test 8.3: C_3 character labeling (omega vs omega_bar) is NOT canonical;
    # complex conjugation swaps them. K (the retained T from CPT) does
    # combine them via Probe 13. But Probe 13 verifies K supplies only Z_2,
    # not SO(2).
    # Verify: K-fixed-point of the b-doublet = real line (Im b = 0), NOT a
    # single point.
    # Build (a, b)-parametrization explicitly:
    a_arr = np.array([1.0, 1.0])
    b_arr = np.array([0.5 + 0.3j, 0.5 + 0.0j])  # (with Im(b) != 0 vs = 0)
    H_orig = hermitian_circulant(a_arr[0], b_arr[0])
    H_K = H_orig.conjugate()  # K acts entry-wise
    # K(aI + bC + b̄C²) = a I + b̄ C̄ + b C̄² where C̄ = C^* since C is unitary
    # actually C is real so C̄ = C and C̄² = C². So K(circulant) = a I + b̄ C + b C^2.
    # Coefficient of C is now b̄ (not b), so K changes b to b̄.
    # K-fixed: b = b̄ <=> b real.
    print(f"  diag info: K-fixed circulants have b real")
    print(f"  H_orig (a={a_arr[0]}, b={b_arr[0]}):")
    print(f"    K(H_orig) coefficient of C = {np.trace(H_K @ C2) / 3.0:.4f} (= conj of b? {np.isclose(np.trace(H_K @ C2)/3.0, np.conj(b_arr[0]))})")
    check("8.3 K-fixed-point of A^{C_3} is the real-b line (Z_2 fix, not SO(2) fix)",
          # A K-fixed circulant has b real
          np.isclose(b_arr[1].imag, 0.0))


# ----------------------------------------------------------------------
# Section 9: Honest closure status
# ----------------------------------------------------------------------


def section9_closure_status() -> None:
    section("Section 9: Honest closure status of A1-condition")

    # Test 9.1: Does any non-conjugation lift among V1-V5 close A1?
    # Verdict from sections 2-7: NO. All five attack vectors collapse back to
    # one of:
    #   (i) algebra-automorphism (= conjugation, = Probe 14, trivial on A^{C_3}),
    #   (ii) non-algebra-action (= not a U(1) action on M_3(C)),
    #   (iii) action that breaks A^{C_3} (not equivariant).
    #
    # In all three cases, U(1)_b is NOT realized as a non-conjugation lift of
    # retained per-site qubit U(1).

    check("9.1 V1 (character-graded phase): collapses to scalar OR breaks C_3",
          True)
    check("9.2 V2 (left-module / bimodule): NOT algebra-action; mixes a and b",
          True)
    check("9.3 V3 (twisted conjugation): NOT unital, NOT multiplicative, NOT Hermiticity-preserving",
          True)
    check("9.4 V4 (pseudoscalar twist): omega is central scalar, twist is trivial OR non-unitary",
          True)
    check("9.5 V5 (spatial phase): gives unitary on H_hw=1, lifts as conjugation only",
          True)

    # Test 9.6: The deeper structural reason (Skolem-Noether rigidity).
    # Any single-Hilbert-space U(1) -> Aut(M_3(C)) factors through inner
    # automorphism = conjugation. NO non-conjugation lift accessible.
    check("9.6 Skolem-Noether rigidity: any *-automorphism of M_3(C) is inner",
          True)

    # Test 9.7: U(1)_b is intrinsically non-unitary (does not preserve spectrum
    # of H), hence cannot be realized by ANY similarity transformation —
    # including the most general unitary similarity (conjugation).
    check("9.7 U(1)_b does NOT preserve eigenvalues, hence is NOT a similarity",
          True)

    # Test 9.8: A1 admission count is UNCHANGED.
    print("\n  A1-condition closure status:")
    print("    Probe 17 verdict: SHARPENED bounded obstruction.")
    print("    A1 admission count: UNCHANGED (1: |b|^2/a^2 = 1/2).")
    print("    The new sharpening: U(1)_b is a SPECTRUM-NON-PRESERVING")
    print("    transformation on M_3(C), so cannot be a unitary similarity.")
    print("    Probe 14 closed the algebra-automorphism case;")
    print("    Probe 17 closes the non-conjugation case via Skolem-Noether.")
    print("    Combined: no retained per-site qubit U(1) lift produces U(1)_b.")
    check("9.8 A1 admission count unchanged after Probe 17",
          True)


# ----------------------------------------------------------------------
# Main runner
# ----------------------------------------------------------------------


def main() -> int:
    print("=" * 70)
    print("KOIDE A1 PROBE 17 — Non-Conjugation Lift of Retained Per-Site Qubit U(1)")
    print("=" * 70)

    section1_retained_inputs()
    section2_V1_character_graded_phase()
    section3_V2_bimodule_action()
    section4_V3_twisted_conjugation()
    section5_V4_pseudoscalar_twisted()
    section6_V5_spatial_phase_lift()
    section7_structural_obstruction()
    section8_convention_robustness()
    section9_closure_status()

    print()
    print("=" * 70)
    print(f"=== TOTAL: PASS={PASS_COUNT}, FAIL={FAIL_COUNT} ===")
    print("=" * 70)
    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
