#!/usr/bin/env python3
"""
Hamming-Weight Projector Algebra on C^8

Classical math applied:
  - Spectral theorem for self-adjoint operators and the resulting
    orthogonal-projector algebra (standard linear algebra; e.g.
    Reed–Simon, "Methods of Modern Mathematical Physics" vol. I,
    §VII.2).
  - Commuting-idempotents algebra: for a finite set of pairwise
    orthogonal projectors Π_0, …, Π_n summing to I, the span is an
    abelian unital *-algebra isomorphic to C^{n+1} under componentwise
    operations (standard *-algebra theory; Blackadar, "Operator
    Algebras", §I.1).
  - S_3 equivariance of the Hamming-weight function sum(α) on
    α ∈ {0,1}³ (invariant under any permutation of the three bits).

Framework object:
  The four orthogonal projectors Π_k : C^8 → C^8 for k ∈ {0, 1, 2, 3},
  where Π_k is the orthogonal projector onto the hw = k subspace
  V_k = span{|α⟩ : α ∈ {0,1}³, Σ α = k} of the taste cube C^8.

Theorem (Hw-Projector Algebra):
  (1) The four projectors Π_0, Π_1, Π_2, Π_3 are pairwise orthogonal,
      idempotent, and sum to the identity:
         Π_j · Π_k  =  δ_{jk} · Π_j,    Σ_k Π_k  =  I_{C^8}.
      They therefore span a 4-dimensional commutative unital *-algebra
         P  :=  span_C {Π_0, Π_1, Π_2, Π_3}  ⊂  End(C^8),
      isomorphic to C^4 as a *-algebra (one factor per hw level).
  (2) Each Π_k is S_3-invariant (since Hamming weight is invariant
      under axis permutation):
         U(π) · Π_k  =  Π_k · U(π)    for all π ∈ S_3.
      Hence P ⊂ End(C^8)^{S_3}, and is a 4-dim abelian subalgebra
      of the 20-dim S_3-invariant commutant (Batch 3).
  (3) P is Hw-diagonal-exhaustive: P coincides with the full abelian
      subalgebra of End(C^8) generated by the hw projectors, and a
      standard commuting-idempotents argument shows it is maximal
      among hw-grading-preserving commutative subalgebras that are
      ALSO S_3-invariant.
  (4) Compared with the cube-shift elementary-symmetric subalgebra
      A_S^{S_3} (Batch 4, dim 4, Hadamard-diagonal):
         · A_S^{S_3} is Hadamard-diagonal (not hw-diagonal except for
           e_0 = I).
         · P is hw-diagonal (not Hadamard-diagonal except for Π_0 + Π_3
           = hw-parity projector).
         · Both have dim 4 and contain the identity.
      These are two distinct 4-dim abelian subalgebras of the 20-dim
      End(C^8)^{S_3}, each natural for its own structural purpose.

Proof method: direct computation of Π_j · Π_k and Σ Π_k;
verification of S_3-invariance via U(π) Π_k = Π_k U(π) for a
generating set of S_3; dimension rank verification.

Applied rather than invented:
  The algebra of orthogonal spectral projectors of a self-adjoint
  operator is the standard spectral-theorem picture.  We apply it
  here to the Hamming-weight operator H = Σ_μ (I - S_μ)/2 on C^8
  (which takes the four eigenvalues 0, 1, 2, 3), and name the
  resulting spectral-projector algebra P.

Reusability:
  - Canonical abelian subalgebra for any framework argument that
    respects the Hamming-weight grading on the taste cube.
  - Companion to the cube-shift polynomial algebra A_S (Batch 4):
    A_S is the Hadamard-diagonal 8-dim maximal-abelian algebra,
    P is the hw-diagonal 4-dim S_3-invariant abelian subalgebra.
  - Used in the Batch 7 "A_S^{S_3} ∩ P = span{I}" theorem.
"""

from __future__ import annotations

import itertools
import numpy as np

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS_COUNT, FAIL_COUNT
    if condition:
        PASS_COUNT += 1
        status = "PASS"
    else:
        FAIL_COUNT += 1
        status = "FAIL"
    line = f"  [{status}] {name}"
    if detail:
        line += f"  ({detail})"
    print(line)


# ---------------------------------------------------------------------------
# Hw projectors on C^8
# ---------------------------------------------------------------------------

def hw_projector(k: int) -> np.ndarray:
    P = np.zeros((8, 8), dtype=complex)
    for alpha in itertools.product([0, 1], repeat=3):
        if sum(alpha) == k:
            idx = alpha[0] * 4 + alpha[1] * 2 + alpha[2]
            P[idx, idx] = 1.0
    return P


def axis_permutation(perm: tuple) -> np.ndarray:
    U = np.zeros((8, 8), dtype=complex)
    for a in itertools.product([0, 1], repeat=3):
        src = a[0] * 4 + a[1] * 2 + a[2]
        new_a = [0, 0, 0]
        for i in range(3):
            new_a[perm[i]] = a[i]
        dst = new_a[0] * 4 + new_a[1] * 2 + new_a[2]
        U[dst, src] = 1.0
    return U


# ---------------------------------------------------------------------------
# Part 1: Orthogonal idempotents summing to identity
# ---------------------------------------------------------------------------

def part1_orthogonal_idempotents() -> list:
    print("\n" + "=" * 72)
    print("PART 1: Π_0, Π_1, Π_2, Π_3 are pairwise-orthogonal idempotents")
    print("        summing to I (applies spectral theorem for self-adjoint")
    print("        operators)")
    print("=" * 72)

    Pi = [hw_projector(k) for k in range(4)]

    # Hermitian
    for k in range(4):
        check(f"Π_{k} is Hermitian", np.allclose(Pi[k], Pi[k].conj().T))
    # Idempotent
    for k in range(4):
        check(f"Π_{k}² = Π_{k}", np.allclose(Pi[k] @ Pi[k], Pi[k]))
    # Orthogonal
    for j in range(4):
        for k in range(j + 1, 4):
            check(f"Π_{j} · Π_{k} = 0", np.allclose(Pi[j] @ Pi[k], 0))

    # Sum to identity
    total = sum(Pi)
    check("Σ_k Π_k = I", np.allclose(total, np.eye(8)))

    # Rank
    for k in range(4):
        dim_k = int(np.round(np.real(np.trace(Pi[k]))))
        expected = [1, 3, 3, 1][k]
        check(f"rank(Π_{k}) = {expected}", dim_k == expected)

    return Pi


# ---------------------------------------------------------------------------
# Part 2: dim span{Π_k} = 4
# ---------------------------------------------------------------------------

def part2_dimension(Pi: list) -> None:
    print("\n" + "=" * 72)
    print("PART 2: span{Π_0, Π_1, Π_2, Π_3} has dim 4")
    print("=" * 72)

    mats = np.stack([P.reshape(64) for P in Pi], axis=1)
    rank = np.linalg.matrix_rank(mats, tol=1e-10)
    print(f"  rank of {{Π_0, Π_1, Π_2, Π_3}} = {rank}")
    check("dim P = 4", rank == 4)

    # Commutative
    for j in range(4):
        for k in range(j + 1, 4):
            check(f"[Π_{j}, Π_{k}] = 0",
                  np.allclose(Pi[j] @ Pi[k], Pi[k] @ Pi[j]))


# ---------------------------------------------------------------------------
# Part 3: S_3-invariance
# ---------------------------------------------------------------------------

def part3_s3_invariance(Pi: list) -> None:
    print("\n" + "=" * 72)
    print("PART 3: Each Π_k is S_3-invariant")
    print("=" * 72)

    s3 = [
        ((0, 1, 2), "e"),
        ((1, 0, 2), "(12)"),
        ((0, 2, 1), "(23)"),
        ((2, 1, 0), "(13)"),
        ((1, 2, 0), "(123)"),
        ((2, 0, 1), "(132)"),
    ]

    for k in range(4):
        for perm, lbl in s3:
            U = axis_permutation(perm)
            check(f"[U({lbl}), Π_{k}] = 0",
                  np.allclose(U @ Pi[k], Pi[k] @ U))


# ---------------------------------------------------------------------------
# Part 4: P ⊂ End(C^8)^{S_3} strictly
# ---------------------------------------------------------------------------

def part4_inside_s3_commutant(Pi: list) -> None:
    print("\n" + "=" * 72)
    print("PART 4: P is a 4-dim subalgebra of End(C^8)^{S_3} (dim 20)")
    print("=" * 72)

    # Build End(C^8)^{S_3} dim by solving [σ, M] = [τ, M] = 0 on 8x8
    tau = axis_permutation((1, 0, 2))
    sigma = axis_permutation((1, 2, 0))

    n = 8
    bases = []
    for j in range(n):
        for k in range(n):
            M = np.zeros((n, n), dtype=complex)
            M[j, k] = 1.0
            bases.append(M)

    C_mats = []
    for g in [tau, sigma]:
        Cg = np.stack([(g @ M - M @ g).reshape(n * n) for M in bases], axis=1)
        C_mats.append(Cg)
    C = np.vstack(C_mats)
    rank = np.linalg.matrix_rank(C, tol=1e-10)
    s3_dim = n * n - rank
    print(f"  dim End(C^8)^{{S_3}} = {s3_dim}")
    check("S_3-invariant commutant dim = 20 (Batch 3)", s3_dim == 20)
    check("dim P = 4 < 20 = dim End(C^8)^{S_3}", 4 < s3_dim)


# ---------------------------------------------------------------------------
# Part 5: P is hw-diagonal; relation to Hadamard-diagonal A_S^{S_3}
# ---------------------------------------------------------------------------

def part5_hw_vs_hadamard(Pi: list) -> None:
    print("\n" + "=" * 72)
    print("PART 5: P is hw-diagonal, A_S^{S_3} is Hadamard-diagonal")
    print("=" * 72)

    # Each Π_k is hw-diagonal by construction.  Verify: Π_k takes each
    # basis vector |α⟩ to 0 or |α⟩.
    all_hw_diag = True
    for k in range(4):
        for alpha in itertools.product([0, 1], repeat=3):
            idx = alpha[0] * 4 + alpha[1] * 2 + alpha[2]
            v = np.zeros(8, dtype=complex); v[idx] = 1.0
            Pv = Pi[k] @ v
            if not (np.allclose(Pv, 0) or np.allclose(Pv, v)):
                all_hw_diag = False
    check("Each Π_k is diagonal in the hw (computational) basis", all_hw_diag)

    # A_S^{S_3} = span{e_0, e_1, e_2, e_3} with
    # e_k = elementary symmetric polynomial in S_1, S_2, S_3.
    # e_0 = I is hw-diagonal trivially.
    # e_1 = S_1 + S_2 + S_3: acts on |α⟩ by sending it to the sum of
    #   three bit-flipped neighbors, which have hw = hw(α) ± 1.
    #   Hence e_1 is hw-OFF-diagonal.

    sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
    I2 = np.eye(2, dtype=complex)
    S1 = np.kron(np.kron(sigma_x, I2), I2)
    S2 = np.kron(np.kron(I2, sigma_x), I2)
    S3 = np.kron(np.kron(I2, I2), sigma_x)
    e1 = S1 + S2 + S3

    # Check: e_1 maps hw=0 to hw=1 (not hw=0).
    v000 = np.zeros(8, dtype=complex); v000[0] = 1.0  # |000⟩, hw=0
    e1_v000 = e1 @ v000
    # e_1 |000⟩ = |100⟩ + |010⟩ + |001⟩, all hw=1
    hw0_components = Pi[0] @ e1_v000
    hw1_components = Pi[1] @ e1_v000
    check("e_1 sends hw=0 state to hw=1 (so e_1 is hw-off-diagonal)",
          np.allclose(hw0_components, 0) and not np.allclose(hw1_components, 0))


# ---------------------------------------------------------------------------
# Part 6: Theorem statement
# ---------------------------------------------------------------------------

def part6_theorem() -> None:
    print("\n" + "=" * 72)
    print("PART 6: Hw-Projector Algebra Theorem (statement)")
    print("=" * 72)

    print("""
  THEOREM (Hw-Projector Algebra on C^8).  Let Π_k : C^8 → C^8 be the
  orthogonal projector onto the Hamming-weight-k subspace for
  k ∈ {0, 1, 2, 3}.  Then:

  (1) The four projectors satisfy
         Π_j Π_k  =  δ_{jk} Π_j,    Σ_k Π_k  =  I.
      They span a 4-dim commutative unital *-algebra
         P  :=  span_C{Π_0, Π_1, Π_2, Π_3}
      isomorphic to C^4 as a *-algebra (one factor per hw level).

  (2) Each Π_k commutes with every S_3 axis-permutation, so
         P  ⊂  End(C^8)^{S_3}
      and is a 4-dim abelian subalgebra of the 20-dim S_3-invariant
      commutant (Batch 3).

  (3) P is the spectral-projector algebra of the Hamming-weight
      operator H = Σ_μ (I - S_μ) / 2 on C^8 (self-adjoint, eigenvalues
      0, 1, 2, 3).

  (4) Compared with the cube-shift elementary-symmetric subalgebra
      A_S^{S_3} (Batch 4, also dim 4, S_3-invariant, abelian):
         · A_S^{S_3} is Hadamard-diagonal; P is hw-diagonal.
         · Each is "maximal" within its own structural class.
      They are two distinct 4-dim abelian subalgebras of the 20-dim
      End(C^8)^{S_3} that happen to share only the identity line
      (Batch 7, "A_S^{S_3} ∩ P = span{I}" theorem).

  CLASSICAL RESULTS USED.
  - Spectral theorem for self-adjoint operators and the resulting
    orthogonal-projector algebra (Reed–Simon vol. I, §VII.2).
  - Commuting-idempotents algebra (Blackadar, *Operator Algebras*,
    §I.1).
  - S_3-equivariance of the Hamming-weight function under axis
    permutations (combinatorial).

  FRAMEWORK-SPECIFIC STEP.
  - Identification of the Hamming-weight operator H on C^8 = (C²)^⊗³,
    and of its 0/1/2/3-eigenspaces with the 1/3/3/1-dim hw blocks
    of the taste cube.

  PROOF.  (1) is a direct check of Π_j Π_k on the hw-indexed basis.
  (2) follows from the S_3-invariance of the Hamming-weight function
  and hence of each hw subspace.  (3) is the statement of the
  spectral theorem applied to H.  (4) combines the hw-diagonal-ness
  of P with the Hadamard-diagonal-ness of A_S^{S_3} (Batch 4 Part 2).
  QED.

  REUSABILITY.
  - Canonical abelian subalgebra for any framework argument that
    respects the Hamming-weight grading on the taste cube.
  - Companion to A_S (Batch 4, Hadamard-diagonal 8-dim) and A_S^{S_3}
    (Batch 4, Hadamard-diagonal S_3-invariant 4-dim).  P is the
    hw-diagonal S_3-invariant 4-dim analogue.
  - Used directly in the Batch 7 "A_S^{S_3} ∩ P" theorem.
""")


def main() -> int:
    print("=" * 72)
    print("  Hamming-Weight Projector Algebra on C^8")
    print("=" * 72)

    Pi = part1_orthogonal_idempotents()
    part2_dimension(Pi)
    part3_s3_invariance(Pi)
    part4_inside_s3_commutant(Pi)
    part5_hw_vs_hadamard(Pi)
    part6_theorem()

    print("\n" + "=" * 72)
    print(f"  TOTAL: PASS={PASS_COUNT}, FAIL={FAIL_COUNT}")
    print("=" * 72)

    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
