#!/usr/bin/env python3
"""
PR #230 scalar-source response harness certificate.

Validate the production-harness extension for explicit uniform scalar-source
perturbations.  The extension measures dE/ds for a lattice source coordinate
s; it does not convert that slope to physical dE/dh unless a scalar LSZ /
canonical-Higgs normalization theorem later derives kappa_s.
"""

from __future__ import annotations

import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "outputs" / "yt_direct_lattice_correlator_scalar_source_response_smoke_2026-05-01.json"
OUTPUT = ROOT / "outputs" / "yt_scalar_source_response_harness_certificate_2026-05-01.json"

PASS_COUNT = 0
FAIL_COUNT = 0


def report(tag: str, ok: bool, msg: str) -> None:
    global PASS_COUNT, FAIL_COUNT
    if ok:
        PASS_COUNT += 1
        status = "PASS"
    else:
        FAIL_COUNT += 1
        status = "FAIL"
    print(f"  [{status}] {tag}: {msg}")


def main() -> int:
    print("PR #230 scalar-source response harness certificate")
    print("=" * 72)

    data = json.loads(INPUT.read_text(encoding="utf-8"))
    metadata = data.get("metadata", {})
    ensembles = data.get("ensembles", [])
    response_meta = metadata.get("scalar_source_response", {})
    analyses = [
        ensemble.get("scalar_source_response_analysis", {})
        for ensemble in ensembles
        if isinstance(ensemble, dict)
    ]
    enabled_analyses = [
        analysis for analysis in analyses if analysis.get("source_coordinate") != "disabled"
    ]
    slopes = [
        float(analysis.get("slope_dE_ds_lat", float("nan")))
        for analysis in enabled_analyses
    ]
    finite_slopes = [slope for slope in slopes if math.isfinite(slope)]
    energy_fit_counts = [
        len(analysis.get("energy_fits", []))
        for analysis in enabled_analyses
    ]

    report("smoke-certificate-present", INPUT.exists(), str(INPUT.relative_to(ROOT)))
    report("reduced-scope-not-production", metadata.get("phase") == "reduced_scope", f"phase={metadata.get('phase')}")
    report("scalar-source-response-enabled", response_meta.get("enabled") is True, str(response_meta))
    report(
        "source-coordinate-is-additive-lattice-source",
        "m_bare + s" in str(response_meta.get("source_coordinate", "")),
        str(response_meta.get("source_coordinate")),
    )
    report(
        "physical-higgs-normalization-not-derived",
        response_meta.get("physical_higgs_normalization") == "not_derived",
        str(response_meta.get("physical_higgs_normalization")),
    )
    report(
        "source-response-has-three-shifts",
        bool(energy_fit_counts) and min(energy_fit_counts) >= 3,
        f"energy_fit_counts={energy_fit_counts}",
    )
    report("finite-dE-ds-slope-extracted", bool(finite_slopes), f"slopes={finite_slopes}")
    report(
        "not-used-as-physical-yukawa-readout",
        response_meta.get("used_as_physical_yukawa_readout") is False,
        str(response_meta.get("used_as_physical_yukawa_readout")),
    )

    result = {
        "actual_current_surface_status": "bounded-support / scalar source response harness extension",
        "verdict": (
            "The direct-correlator production harness now supports explicit "
            "uniform scalar-source shifts and emits a dE/ds response analysis. "
            "This materially advances the Feynman-Hellmann measurement route: "
            "the observable can be generated by the same harness rather than "
            "only by a synthetic scout.  It is not retained closure because "
            "the source coordinate is the lattice source s, not the canonical "
            "Higgs fluctuation h; kappa_s and any lattice-to-SM matching remain "
            "open imports."
        ),
        "proposal_allowed": False,
        "proposal_allowed_reason": "The harness extracts dE/ds only; kappa_s and production response data remain open.",
        "input_certificate": str(INPUT.relative_to(ROOT)),
        "phase": metadata.get("phase"),
        "source_response_metadata": response_meta,
        "response_summaries": [
            {
                "volume": f"{ensemble.get('spatial_L')}^3x{ensemble.get('time_L')}",
                "selected_mass_parameter": ensemble.get("selected_mass_parameter"),
                "analysis": ensemble.get("scalar_source_response_analysis", {}),
            }
            for ensemble in ensembles
            if isinstance(ensemble, dict)
        ],
        "required_next_steps": [
            "run source-response shifts on production gauge ensembles",
            "derive scalar source-to-canonical-Higgs normalization kappa_s from LSZ/canonical kinetic data",
            "derive any lattice-to-SM response matching rather than setting Z_match = 1",
        ],
        "strict_non_claims": [
            "not production evidence",
            "not a physical y_t derivation",
            "does not use H_unit matrix-element readout",
            "does not use yt_ward_identity as y_t authority",
            "does not use observed top mass or observed y_t as proof selectors",
            "does not set kappa_s, c2, or Z_match to one",
        ],
        "pass_count": PASS_COUNT,
        "fail_count": FAIL_COUNT,
    }
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"\nWrote certificate: {OUTPUT.relative_to(ROOT)}")
    print(f"SUMMARY: PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
