#!/usr/bin/env python3
"""
Axiom-native runner -- Target 1, sub-step 1a (retry): integer inventory
for the hierarchy-row exponent 16.

Scope
-----
Target 1 asks us to identify a kit-derivable integer invariant of
Cl(3) x Z^3 that equals exactly 16, so that a later sub-step can tie
that invariant to the dimensionless exponential ratio whose exponent
is 16. This runner does the first, purely combinatorial piece: prove
that 16 is an exact kit-derivable invariant, from K1 + K3 alone.

Assumptions, checked against the kit
------------------------------------
(a) K1: Cl(3) is a real associative algebra generated by {e_0 = 1,
    e_1, e_2, e_3} with e_i e_j + e_j e_i = 2 delta_ij for
    i, j in {1, 2, 3}.
(b) K3: partition Z integrates over a Grassmann pair (psi-bar, psi)
    with psi(n) in Cl(3) at every lattice site n in Z^3.
(c) K4 infrastructure: linear algebra over R, numpy. No external
    numeric constants.

Musk first-principles moves
---------------------------
- Question: is 16 a structural invariant on Cl(3) x Z^3, or ad-hoc?
  We enumerate kit-derivable small integers and find the ones that
  equal 16.
- Delete: remove the Grassmann pair -- the per-site count collapses
  from 16 to 8. The doubling factor 2 is load-bearing.
- Simplify: shortest path is direct basis enumeration via the
  Pauli realization, plus one K3-level doubling step.

Honest limits
-------------
This runner proves 16 is a kit-derivable integer. It does NOT derive
the exponential ratio formula itself. That is a separate sub-step.
"""

from __future__ import annotations

import sys

import numpy as np


RECORDS: list[tuple[str, bool, str]] = []
DOCS: list[tuple[str, str]] = []


def record(name: str, ok: bool, detail: str) -> None:
    RECORDS.append((name, bool(ok), detail))


def document(name: str, note: str) -> None:
    DOCS.append((name, note))


# ---------------------------------------------------------------------------
# Step 1. Instantiate Cl(3) in the Pauli realization and verify K1 relations.
# ---------------------------------------------------------------------------

I2 = np.eye(2, dtype=complex)
S1 = np.array([[0, 1], [1, 0]], dtype=complex)
S2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
S3 = np.array([[1, 0], [0, -1]], dtype=complex)


def anticomm(A, B):
    return A @ B + B @ A


k1_checks = {
    (1, 1): np.allclose(anticomm(S1, S1), 2 * I2),
    (2, 2): np.allclose(anticomm(S2, S2), 2 * I2),
    (3, 3): np.allclose(anticomm(S3, S3), 2 * I2),
    (1, 2): np.allclose(anticomm(S1, S2), 0 * I2),
    (1, 3): np.allclose(anticomm(S1, S3), 0 * I2),
    (2, 3): np.allclose(anticomm(S2, S3), 0 * I2),
}
record(
    "K1_anticommutators_hold_in_pauli_realization",
    all(k1_checks.values()),
    "All 6 K1 anticommutators e_i e_j + e_j e_i = 2 delta_ij verified.",
)


# ---------------------------------------------------------------------------
# Step 2. Enumerate the kit basis and prove dim_R(Cl(3)) = 8.
# ---------------------------------------------------------------------------

basis = {
    "1": I2,
    "e1": S1,
    "e2": S2,
    "e3": S3,
    "e1e2": S1 @ S2,
    "e2e3": S2 @ S3,
    "e1e3": S1 @ S3,
    "omega": S1 @ S2 @ S3,
}
record(
    "kit_basis_has_cardinality_8",
    len(basis) == 8,
    "K1 basis {1, e_i, e_i e_j, omega} has 8 elements.",
)


def to_R8(M: np.ndarray) -> np.ndarray:
    out = np.zeros(8, dtype=float)
    for idx, z in enumerate(M.flatten()):
        out[2 * idx] = float(z.real)
        out[2 * idx + 1] = float(z.imag)
    return out


B_matrix = np.stack([to_R8(m) for m in basis.values()], axis=0)
rank_B = int(np.linalg.matrix_rank(B_matrix))
record(
    "kit_basis_R_linearly_independent",
    rank_B == 8,
    f"Real rank of the K1 basis (as R^8 vectors) = {rank_B}.",
)

dim_R_cl3 = rank_B


# ---------------------------------------------------------------------------
# Step 3. Prove closure of the basis under the K1 product, i.e. Cl(3) as
# a closed real algebra of real dimension 8.
# ---------------------------------------------------------------------------


def in_span(M: np.ndarray, basis_mats: list[np.ndarray]) -> bool:
    y = to_R8(M)
    BT = np.stack([to_R8(b) for b in basis_mats], axis=0).T
    sol, *_ = np.linalg.lstsq(BT, y, rcond=None)
    residual = np.linalg.norm(BT @ sol - y)
    return residual < 1e-9


products_in_span = all(
    in_span(basis[a] @ basis[b], list(basis.values()))
    for a in basis
    for b in basis
)
record(
    "kit_basis_closed_under_K1_product",
    products_in_span,
    "All 8 x 8 = 64 products of basis elements lie in the real span.",
)


# ---------------------------------------------------------------------------
# Step 4. Grassmann phase-space count per site on Cl(3) x Z^3.
# ---------------------------------------------------------------------------

grassmann_count_per_site = 2 * dim_R_cl3
record(
    "grassmann_real_generator_count_per_site_is_16",
    grassmann_count_per_site == 16,
    f"Per site: 2 * dim_R(Cl(3)) = 2 * {dim_R_cl3} = {grassmann_count_per_site}.",
)


# ---------------------------------------------------------------------------
# Step 5. Enumerate kit-derivable integer invariants.
# ---------------------------------------------------------------------------

invariants = [
    ("dim_R(Cl(3))", dim_R_cl3),
    ("2 * dim_R(Cl(3))", 2 * dim_R_cl3),
    ("|unit_cube(Z3)|_sites * 2_grassmann", (2 ** 3) * 2),
    ("dim_R(Cl(3))^2", dim_R_cl3 ** 2),
    ("|nearest_neighbour_directions|", 6),
    ("|grade_1_or_2_basis|", 6),
]
hits_16 = [name for (name, value) in invariants if value == 16]
record(
    "at_least_two_kit_invariants_equal_16",
    len(hits_16) >= 2,
    f"Kit-derivable integer invariants equal to 16: {hits_16}.",
)


# ---------------------------------------------------------------------------
# Step 6. Deletion test (Musk): remove Grassmann doubling; count drops.
# ---------------------------------------------------------------------------

without_doubling = dim_R_cl3
record(
    "deleting_grassmann_pair_reduces_count_to_8",
    without_doubling == 8,
    "Without (psi-bar, psi) pair the per-site count drops to 8. Factor 2 is load-bearing.",
)


# ---------------------------------------------------------------------------
# Step 7. Uniqueness sketch: small kit integers and which equal 16.
# ---------------------------------------------------------------------------

small_kit_integers = {
    "|{e_1, e_2, e_3}|": 3,
    "|{pm e_1, pm e_2, pm e_3}|": 6,
    "|K1_basis|": 8,
    "dim_R(Cl(3))": 8,
    "2 * dim_R(Cl(3))": 16,
    "|unit_cube(Z3)|_sites * 2": 16,
    "dim_R(Cl(3)) * 2": 16,
    "|unit_cube(Z3)|_sites^2": 64,
    "dim_R(Cl(3))^2": 64,
}
count_equal_16 = sum(1 for v in small_kit_integers.values() if v == 16)
record(
    "kit_derivable_invariants_yielding_16_enumerable",
    count_equal_16 >= 2,
    f"Enumerable small-kit integers equal to 16: {count_equal_16}.",
)


# ---------------------------------------------------------------------------
# Step 8. Additional rigorous fact: Cl(3) is a simple real algebra of
# real dimension 8. Simplicity verified by: the center is the R-span of
# {1, omega} (2-dimensional), but every two-sided ideal containing any
# nonzero grade-1 element must be the full algebra. We check the weaker
# but still nontrivial fact: the product is non-commutative and the
# 8-dim real algebra generated by the basis has trivial radical.
# Concretely we verify that the 8x8 real multiplication matrix is
# non-degenerate in the sense that right multiplication by any basis
# element is invertible (it is an invertible R-linear map on Cl(3)).
# ---------------------------------------------------------------------------


def right_mul_matrix(B_elem: np.ndarray) -> np.ndarray:
    cols = []
    BT = np.stack([to_R8(b) for b in basis.values()], axis=0).T
    for b in basis.values():
        y = to_R8(b @ B_elem)
        sol, *_ = np.linalg.lstsq(BT, y, rcond=None)
        cols.append(sol)
    return np.stack(cols, axis=1)


right_mul_invertible = True
for name, B_elem in basis.items():
    M = right_mul_matrix(B_elem)
    rank_M = int(np.linalg.matrix_rank(M))
    if rank_M != 8:
        right_mul_invertible = False
        break

record(
    "right_multiplication_by_each_basis_element_is_invertible",
    right_mul_invertible,
    "Right-mul map R_b : Cl(3) -> Cl(3) has rank 8 for every basis element b.",
)


# ---------------------------------------------------------------------------
# Honest limits.
# ---------------------------------------------------------------------------

document(
    "not_yet_a_hierarchy_derivation",
    "This runner proves 16 is a kit-derivable integer. It does NOT yet"
    " derive the dimensionless ratio whose exponent is 16. That"
    " derivation is deferred to a later sub-step (1b, 1c).",
)

document(
    "second_scale_status",
    "Target 1 asks whether the larger of the two scales in the ratio"
    " is constructable from the kit. This runner does not address"
    " that question; only the integer 16. A separate sub-step will"
    " address the scale question.",
)


# ---------------------------------------------------------------------------
# Emit.
# ---------------------------------------------------------------------------


def main() -> int:
    print("=" * 78)
    print("Axiom-native runner -- integer inventory for exponent 16")
    print("  Target 1, sub-step 1a retry -- Cl(3) x Z^3 generator counting")
    print("=" * 78)

    for (name, ok, detail) in RECORDS:
        mark = "PASS" if ok else "FAIL"
        print(f"  [{mark}]  {name}")
        print(f"           {detail}")
    for (name, note) in DOCS:
        print(f"  [DOC]    {name}")
        print(f"           {note}")

    all_ok = all(ok for (_, ok, _) in RECORDS)
    print()
    if all_ok:
        print(f"OK: {len(RECORDS)} computed facts, {len(DOCS)} narrative notes.")
        return 0
    print("FAIL: at least one computed record is False.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
