#!/usr/bin/env python3
"""Bounded radial shell matching law from the exact sewing-shell source.

Exact content:
  1. The exact shell source sigma_R decomposes uniquely into a shell-radial
     average sigma_rad and a zero-monopole anisotropic remainder delta_sigma.
  2. sigma_rad carries the full total charge, while delta_sigma has zero total
     charge.

Bounded content:
  3. The field generated by sigma_rad already captures the exact exterior
     field outside the sewing shell to ~12% max relative error and ~3.2% RMS
     for both exact source families on codex/review-active.

This does not close full nonlinear GR. It sharpens the sewing-shell target to
the radial shell profile plus controlled anisotropic correction.
"""

from __future__ import annotations

from dataclasses import dataclass
from _frontier_loader import load_frontier

import numpy as np
from scipy.sparse.linalg import spsolve


@dataclass
class Check:
    name: str
    ok: bool
    detail: str
    status: str


CHECKS: list[Check] = []


def record(name: str, ok: bool, detail: str, status: str = "EXACT") -> None:
    CHECKS.append(Check(name=name, ok=ok, detail=detail, status=status))
    tag = "PASS" if ok else "FAIL"
    print(f"[{status}] {tag}: {name}")
    if detail:
        print(f"    {detail}")


same_source = load_frontier("same_source_metric", "frontier_same_source_metric_ansatz_scan.py")
coarse = load_frontier("coarse_grained", "frontier_coarse_grained_exterior_law.py")
finite_rank = load_frontier("finite_rank_metric", "frontier_finite_rank_gravity_residual.py")
sew = load_frontier("sewing_shell", "frontier_sewing_shell_source.py")


def solve_from_source(source_grid: np.ndarray) -> np.ndarray:
    size = source_grid.shape[0]
    H0, interior = finite_rank.build_neg_laplacian_sparse(size)
    rhs = source_grid[1:-1, 1:-1, 1:-1].reshape(-1)
    sol = spsolve(H0, rhs)
    out = np.zeros_like(source_grid)
    out[1:-1, 1:-1, 1:-1] = sol.reshape((interior, interior, interior))
    return out


def radial_average_shell(source_grid: np.ndarray, tol: float = 1e-12) -> np.ndarray:
    size = source_grid.shape[0]
    center = (size - 1) / 2.0
    out = np.zeros_like(source_grid)
    groups: dict[int, list[tuple[int, int, int]]] = {}
    for i in range(size):
        for j in range(size):
            for k in range(size):
                if abs(source_grid[i, j, k]) > tol:
                    dx = i - center
                    dy = j - center
                    dz = k - center
                    d2 = int(dx * dx + dy * dy + dz * dz)
                    groups.setdefault(d2, []).append((i, j, k))
    for pts in groups.values():
        avg = float(np.mean([source_grid[p] for p in pts]))
        for p in pts:
            out[p] = avg
    return out


def exterior_relative_errors(phi_exact: np.ndarray, phi_approx: np.ndarray, cutoff: float = 5.0):
    radii = sew.radii_grid(phi_exact.shape[0])
    mask = radii > cutoff + 1e-12
    rel = np.abs(phi_exact[mask] - phi_approx[mask]) / np.maximum(np.abs(phi_exact[mask]), 1e-12)
    return float(np.max(rel)), float(np.sqrt(np.mean(rel * rel)))


def analyze_family(name: str, phi_grid: np.ndarray, shell_radius: float = 4.0):
    phi_ext = sew.exterior_projector(phi_grid, shell_radius)
    sigma = sew.full_neg_laplacian(phi_ext)
    sigma_rad = radial_average_shell(sigma)
    sigma_aniso = sigma - sigma_rad

    phi_rad = solve_from_source(sigma_rad)
    phi_aniso = solve_from_source(sigma_aniso)

    q_total = float(np.sum(sigma))
    q_rad = float(np.sum(sigma_rad))
    q_aniso = float(np.sum(sigma_aniso))

    max_rel, rms_rel = exterior_relative_errors(phi_ext, phi_rad)
    print(
        f"{name}: Q={q_total:.8f}, Q_rad={q_rad:.8f}, Q_aniso={q_aniso:.3e}, "
        f"radial exterior max_rel={max_rel:.4f}, rms_rel={rms_rel:.4f}, "
        f"aniso_norm={float(np.max(np.abs(phi_aniso))):.4e}"
    )

    return {
        "q_total": q_total,
        "q_rad": q_rad,
        "q_aniso": q_aniso,
        "max_rel": max_rel,
        "rms_rel": rms_rel,
    }


def main() -> None:
    print("Radial shell matching law from exact sewing-shell source")
    print("=" * 72)

    oh = analyze_family("exact local O_h family", same_source.build_best_phi_grid())
    fr = analyze_family("exact finite-rank family", coarse.build_finite_rank_phi_grid())

    record(
        "the local O_h shell-radial source carries the full total charge",
        abs(oh["q_rad"] - oh["q_total"]) < 1e-12 and abs(oh["q_aniso"]) < 1e-12,
        f"Q={oh['q_total']:.8f}, Q_rad={oh['q_rad']:.8f}, Q_aniso={oh['q_aniso']:.3e}",
    )
    record(
        "the finite-rank shell-radial source carries the full total charge",
        abs(fr["q_rad"] - fr["q_total"]) < 1e-12 and abs(fr["q_aniso"]) < 1e-12,
        f"Q={fr['q_total']:.8f}, Q_rad={fr['q_rad']:.8f}, Q_aniso={fr['q_aniso']:.3e}",
    )
    record(
        "the local O_h exterior is well approximated by the radial shell law",
        oh["max_rel"] < 0.13 and oh["rms_rel"] < 0.04,
        f"max_rel={oh['max_rel']:.4f}, rms_rel={oh['rms_rel']:.4f}",
        status="BOUNDED",
    )
    record(
        "the finite-rank exterior is well approximated by the radial shell law",
        fr["max_rel"] < 0.13 and fr["rms_rel"] < 0.04,
        f"max_rel={fr['max_rel']:.4f}, rms_rel={fr['rms_rel']:.4f}",
        status="BOUNDED",
    )
    record(
        "the radial shell law is uniformly robust across both exact source families",
        max(oh["max_rel"], fr["max_rel"]) < 0.13 and max(oh["rms_rel"], fr["rms_rel"]) < 0.04,
        (
            f"O_h max/rms=({oh['max_rel']:.4f}, {oh['rms_rel']:.4f}), "
            f"finite-rank max/rms=({fr['max_rel']:.4f}, {fr['rms_rel']:.4f})"
        ),
        status="BOUNDED",
    )

    print("\n" + "=" * 72)
    print("SUMMARY")
    print("=" * 72)
    n_pass = sum(c.ok for c in CHECKS)
    n_fail = sum(not c.ok for c in CHECKS)
    print(f"PASS={n_pass} FAIL={n_fail} TOTAL={len(CHECKS)}")
    if n_fail == 0:
        print("All checks passed.")
    else:
        print("Some checks failed.")


if __name__ == "__main__":
    main()
