#!/usr/bin/env python3
"""
PR #230 FH/LSZ uniform-gap self-certification no-go.

The pole-saturation gate says a finite-shell pole fit would become useful if a
uniform continuum gap or microscopic scalar-denominator theorem excluded
near-pole continuum strength.  This runner checks whether the finite shell data
can certify that gap by themselves.  They cannot: even shell data generated by
a deliberately gapped positive Stieltjes model are also reproducible by an
ungapped positive Stieltjes model whose pole residue lower bound is zero.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import numpy as np
from scipy.optimize import linprog


ROOT = Path(__file__).resolve().parents[1]
THRESHOLD_GATE = ROOT / "outputs" / "yt_fh_lsz_pole_saturation_threshold_gate_2026-05-02.json"
FINITE_VOLUME = ROOT / "outputs" / "yt_fh_lsz_finite_volume_pole_saturation_obstruction_2026-05-02.json"
SEED_AUDIT = ROOT / "outputs" / "yt_fh_lsz_numba_seed_independence_audit_2026-05-02.json"
OUTPUT = ROOT / "outputs" / "yt_fh_lsz_uniform_gap_self_certification_no_go_2026-05-02.json"

PASS_COUNT = 0
FAIL_COUNT = 0


def report(tag: str, ok: bool, msg: str) -> None:
    global PASS_COUNT, FAIL_COUNT
    if ok:
        PASS_COUNT += 1
        status = "PASS"
    else:
        FAIL_COUNT += 1
        status = "FAIL"
    print(f"  [{status}] {tag}: {msg}")


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def solve_interval(
    shells: np.ndarray,
    target_c: np.ndarray,
    pole_m2: float,
    continuum_m2: np.ndarray,
) -> dict[str, Any]:
    matrix = np.column_stack(
        [
            1.0 / (shells + pole_m2),
            1.0 / (shells[:, None] + continuum_m2[None, :]),
        ]
    )
    bounds = [(0.0, None)] * matrix.shape[1]
    min_result = linprog(
        c=np.r_[1.0, np.zeros(len(continuum_m2))],
        A_eq=matrix,
        b_eq=target_c,
        bounds=bounds,
        method="highs",
    )
    max_result = linprog(
        c=np.r_[-1.0, np.zeros(len(continuum_m2))],
        A_eq=matrix,
        b_eq=target_c,
        bounds=bounds,
        method="highs",
    )
    if not min_result.success or not max_result.success:
        return {
            "feasible": False,
            "min_message": min_result.message,
            "max_message": max_result.message,
        }
    residue_min = float(min_result.fun)
    residue_max = float(-max_result.fun)
    return {
        "feasible": True,
        "residue_min": residue_min,
        "residue_max": residue_max,
        "lower_bound_is_zero": residue_min <= 1.0e-12,
    }


def build_rows() -> dict[str, Any]:
    one_link = 4.0 * math.sin(math.pi / 12.0) ** 2
    shells = np.asarray([0.0, one_link, 2.0 * one_link, 1.0], dtype=float)
    pole_m2 = 0.25
    gapped_continuum = np.asarray([1.0, 1.5, 2.0, 4.0, 8.0, 16.0], dtype=float)
    gapped_target = 1.0 / (shells + pole_m2) + (
        1.0 / (shells[:, None] + gapped_continuum[None, :])
    ) @ np.full(len(gapped_continuum), 0.5)
    scans = [
        ("near_pole_ungapped", np.asarray([0.251, 0.260, 0.300, 0.400, 0.700, 1.0, 1.5, 2.0, 4.0, 8.0, 16.0])),
        ("moderately_gapped", np.asarray([0.500, 0.700, 1.0, 1.5, 2.0, 4.0, 8.0, 16.0])),
        ("true_gapped_support", gapped_continuum),
    ]
    rows = [
        {
            "fit_class": name,
            "continuum_threshold_m2": float(grid[0]),
            "continuum_grid": [float(x) for x in grid],
            **solve_interval(shells, gapped_target, pole_m2, grid),
        }
        for name, grid in scans
    ]
    return {
        "shells_p_hat_sq": [float(x) for x in shells],
        "pole_p_hat_sq": -pole_m2,
        "gapped_generator": {
            "pole_residue": 1.0,
            "continuum_threshold_m2": float(gapped_continuum[0]),
            "continuum_weights": [0.5 for _ in gapped_continuum],
            "target_shell_values": [float(x) for x in gapped_target],
        },
        "interval_rows": rows,
    }


def main() -> int:
    print("PR #230 FH/LSZ uniform-gap self-certification no-go")
    print("=" * 72)

    threshold_gate = load_json(THRESHOLD_GATE)
    finite_volume = load_json(FINITE_VOLUME)
    seed_audit = load_json(SEED_AUDIT)
    scan = build_rows()
    rows = scan["interval_rows"]
    near = rows[0]
    true_gap = rows[-1]
    near_fits = near.get("feasible") is True
    true_gap_tight = (
        true_gap.get("feasible") is True
        and true_gap.get("residue_min", 0.0) > 0.99
        and true_gap.get("residue_max", 0.0) < 1.01
    )
    near_zero_lower = near.get("lower_bound_is_zero") is True

    report("threshold-gate-loaded", bool(threshold_gate), str(THRESHOLD_GATE.relative_to(ROOT)))
    report("finite-volume-obstruction-loaded", bool(finite_volume), str(FINITE_VOLUME.relative_to(ROOT)))
    report("seed-audit-loaded", bool(seed_audit), str(SEED_AUDIT.relative_to(ROOT)))
    report("gapped-generator-self-consistent", true_gap_tight, f"true_gap_interval=[{true_gap.get('residue_min')}, {true_gap.get('residue_max')}]")
    report("ungapped-positive-model-reproduces-gapped-shells", near_fits, f"near_interval=[{near.get('residue_min')}, {near.get('residue_max')}]")
    report("finite-shell-gap-certification-fails", near_zero_lower, "near-pole continuum leaves pole residue lower bound zero")
    report("does-not-authorize-retained-proposal", True, "uniform gap must be derived externally or measured with a production acceptance certificate")

    result = {
        "actual_current_surface_status": "exact negative boundary / FH-LSZ uniform-gap self-certification no-go",
        "verdict": (
            "Finite same-source Euclidean shell rows cannot self-certify the "
            "uniform continuum gap needed by the pole-saturation gate.  A "
            "dataset generated from a deliberately gapped positive Stieltjes "
            "model is exactly reproducible by a near-pole positive continuum "
            "model, and the allowed pole-residue interval then has zero lower "
            "bound.  Therefore the uniform gap must come from an independent "
            "scalar-denominator theorem, continuum-threshold certificate, or "
            "production acceptance analysis; it cannot be inferred from the "
            "finite shell rows alone."
        ),
        "proposal_allowed": False,
        "proposal_allowed_reason": "Finite shell rows do not certify the uniform gap or pole-saturation premise.",
        "parent_certificates": {
            "threshold_gate": str(THRESHOLD_GATE.relative_to(ROOT)),
            "finite_volume_obstruction": str(FINITE_VOLUME.relative_to(ROOT)),
            "seed_independence_audit": str(SEED_AUDIT.relative_to(ROOT)),
        },
        "gap_certification_scan": scan,
        "strict_non_claims": [
            "does not infer a continuum threshold from finite shell rows",
            "does not set kappa_s = 1",
            "does not use observed top mass or observed y_t",
            "does not use H_unit, Ward authority, alpha_LM, plaquette, or u0",
        ],
        "exact_next_action": (
            "Attack the microscopic scalar denominator theorem directly, or "
            "continue seed-controlled production chunks toward a postprocess "
            "that supplies an independent threshold/gap certificate."
        ),
        "pass_count": PASS_COUNT,
        "fail_count": FAIL_COUNT,
    }
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"\nWrote certificate: {OUTPUT.relative_to(ROOT)}")
    print(f"SUMMARY: PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
