#!/usr/bin/env python3
"""
Majorana source-ray theorem on the Nambu-complete unique local block.

Question:
  After the Nambu source principle, is the genuinely new one-generation
  Majorana source still an arbitrary pseudospin vector on span{J_x, J_y, J_z}?

Answer on the exact local block:
  No. Once the retained normal slice span{J_z} is recognized as already
  present on the current stack, the genuinely new beyond-retained source lives
  entirely in the transverse pairing plane span{J_x, J_y}. The local nu_R
  rephasing generated by J_z rotates that plane exactly, so every nonzero
  transverse source is equivalent to the canonical pure-pairing ray mu J_x
  with mu >= 0.

Boundary:
  This is an exact one-generation source-ray theorem on the admitted
  Nambu-complete local grammar. It does NOT fix the amplitude mu, the
  staircase level, or the three-generation texture amplitudes.
"""

from __future__ import annotations

import math
import sys

import numpy as np

np.set_printoptions(precision=6, suppress=True, linewidth=140)

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "") -> bool:
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    msg = f"  [{status}] {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return condition


def commutator(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return a @ b - b @ a


def annihilation_operators(n_modes: int) -> list[np.ndarray]:
    sigma_minus = np.array([[0.0, 1.0], [0.0, 0.0]], dtype=complex)
    sigma_z = np.array([[1.0, 0.0], [0.0, -1.0]], dtype=complex)
    ident = np.eye(2, dtype=complex)

    operators: list[np.ndarray] = []
    for mode in range(n_modes):
        op = np.array([[1.0]], dtype=complex)
        for idx in range(n_modes):
            if idx < mode:
                op = np.kron(op, sigma_z)
            elif idx == mode:
                op = np.kron(op, sigma_minus)
            else:
                op = np.kron(op, ident)
        operators.append(op)
    return operators


def unitary_from_generator(generator: np.ndarray, theta: float) -> np.ndarray:
    evals, evecs = np.linalg.eigh(generator)
    phases = np.diag(np.exp(-1j * theta * evals))
    return evecs @ phases @ evecs.conj().T


def frob_coeffs(operator: np.ndarray, basis: list[np.ndarray]) -> np.ndarray:
    gram = np.array(
        [[np.trace(bi.conj().T @ bj) for bj in basis] for bi in basis],
        dtype=complex,
    )
    rhs = np.array([np.trace(bi.conj().T @ operator) for bi in basis], dtype=complex)
    return np.linalg.solve(gram, rhs)


def local_block_generators() -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    c1, c2 = annihilation_operators(2)
    n1 = c1.conj().T @ c1
    n2 = c2.conj().T @ c2
    ident = np.eye(c1.shape[0], dtype=complex)

    pair_ann = c1 @ c2
    pair_cre = pair_ann.conj().T

    jx = 0.5 * (pair_ann + pair_cre)
    jy = (pair_cre - pair_ann) / (2.0j)
    jz = 0.5 * (n1 + n2 - ident)
    n_tot = n1 + n2
    return jx, jy, jz, n_tot, pair_ann, pair_cre


def test_exact_old_new_split() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    print("\n" + "=" * 88)
    print("PART 1: THE LOCAL NAMBU FAMILY SPLITS EXACTLY INTO RETAINED AND NEW DIRECTIONS")
    print("=" * 88)

    jx, jy, jz, n_tot, pair_ann, pair_cre = local_block_generators()

    ortho_xz = abs(np.trace(jx.conj().T @ jz))
    ortho_yz = abs(np.trace(jy.conj().T @ jz))
    charge_z = np.linalg.norm(commutator(n_tot, jz))
    charge_ann = np.linalg.norm(commutator(n_tot, pair_ann) + 2.0 * pair_ann)
    charge_cre = np.linalg.norm(commutator(n_tot, pair_cre) - 2.0 * pair_cre)

    a, b, c = 0.41, -0.29, 0.63
    source = a * jx + b * jy + c * jz
    coeffs = frob_coeffs(source, [jx, jy, jz])
    new_part = source - coeffs[2] * jz
    new_err = np.linalg.norm(new_part - (a * jx + b * jy))

    check("J_z is Frobenius-orthogonal to J_x", ortho_xz < 1e-12,
          f"<J_x,J_z>={ortho_xz:.2e}")
    check("J_z is Frobenius-orthogonal to J_y", ortho_yz < 1e-12,
          f"<J_y,J_z>={ortho_yz:.2e}")
    check("J_z remains the exact charge-zero normal direction", charge_z < 1e-12,
          f"charge error={charge_z:.2e}")
    check("The transverse pairing seed carries charge -2/+2 through J_-/J_+", charge_ann < 1e-12 and charge_cre < 1e-12,
          f"ann error={charge_ann:.2e}, cre error={charge_cre:.2e}")
    check("Removing the retained J_z component leaves exactly the transverse pairing part", new_err < 1e-12,
          f"projection error={new_err:.2e}")

    print()
    print("  So on the admitted Nambu-complete local grammar, the genuinely new")
    print("  beyond-retained source is the transverse pairing component, not an")
    print("  arbitrary mixture with the already-retained normal J_z direction.")

    return jx, jy, jz


def test_rephasing_rotates_transverse_plane() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    print("\n" + "=" * 88)
    print("PART 2: LOCAL nu_R REPHASING ACTS AS EXACT SO(2) ON THE NEW SOURCE PLANE")
    print("=" * 88)

    jx, jy, jz, _, _, _ = local_block_generators()
    theta = 0.73
    u = unitary_from_generator(jz, theta)

    rot_x = u @ jx @ u.conj().T
    rot_y = u @ jy @ u.conj().T

    coeffs_x = frob_coeffs(rot_x, [jx, jy, jz])
    coeffs_y = frob_coeffs(rot_y, [jx, jy, jz])

    target_x = np.array([math.cos(theta), math.sin(theta), 0.0], dtype=complex)
    target_y = np.array([-math.sin(theta), math.cos(theta), 0.0], dtype=complex)
    err_x = np.linalg.norm(coeffs_x - target_x)
    err_y = np.linalg.norm(coeffs_y - target_y)

    check("Rephasing about J_z rotates J_x inside the transverse plane", err_x < 1e-12,
          f"rotation error={err_x:.2e}")
    check("Rephasing about J_z rotates J_y inside the transverse plane", err_y < 1e-12,
          f"rotation error={err_y:.2e}")

    print()
    print("  This is the local phase-removal theorem in Nambu language: the")
    print("  transverse pairing plane is an exact rephasing orbit under J_z.")

    return jx, jy, jz


def test_every_new_source_aligns_to_canonical_pairing_ray() -> None:
    print("\n" + "=" * 88)
    print("PART 3: EVERY NONZERO NEW SOURCE IS EQUIVALENT TO THE CANONICAL RAY mu J_x")
    print("=" * 88)

    jx, jy, jz, _, _, _ = local_block_generators()
    a, b = -0.37, 0.91
    mu = math.hypot(a, b)
    transverse = a * jx + b * jy

    theta = -math.atan2(b, a)
    u = unitary_from_generator(jz, theta)
    aligned = u @ transverse @ u.conj().T
    coeffs = frob_coeffs(aligned, [jx, jy, jz])

    align_err = np.linalg.norm(aligned - mu * jx)
    jy_err = abs(coeffs[1])
    jz_err = abs(coeffs[2])

    check("A transverse source has invariant amplitude mu = sqrt(a^2+b^2)", abs(mu - math.hypot(a, b)) < 1e-12,
          f"mu={mu:.6f}")
    check("A J_z rephasing aligns any nonzero transverse source to mu J_x", align_err < 1e-12,
          f"alignment error={align_err:.2e}")
    check("The aligned source has no residual J_y or J_z component", jy_err < 1e-12 and jz_err < 1e-12,
          f"|c_y|={jy_err:.2e}, |c_z|={jz_err:.2e}")

    print()
    print("  So the genuinely new one-generation source is not an arbitrary")
    print("  Nambu vector. Up to the exact local rephasing already allowed on")
    print("  the nu_R singlet, it is the unique pure-pairing ray mu J_x.")


def main() -> int:
    print("=" * 88)
    print("NEUTRINO MAJORANA: SOURCE-RAY THEOREM")
    print("=" * 88)
    print()
    print("Authority stack:")
    print("  - docs/NEUTRINO_MAJORANA_PHASE_REMOVAL_NOTE.md")
    print("  - docs/NEUTRINO_MAJORANA_CANONICAL_LOCAL_BLOCK_NOTE.md")
    print("  - docs/NEUTRINO_MAJORANA_NAMBU_SOURCE_PRINCIPLE_NOTE.md")
    print()
    print("Question:")
    print("  After admitting the exact local Nambu-complete source family, is the")
    print("  genuinely new one-generation Majorana source still an arbitrary")
    print("  pseudospin vector, or is its direction already fixed?")

    test_exact_old_new_split()
    test_rephasing_rotates_transverse_plane()
    test_every_new_source_aligns_to_canonical_pairing_ray()

    print("\n" + "=" * 88)
    print("RESULT")
    print("=" * 88)
    print("  The genuinely new beyond-retained one-generation Majorana source is")
    print("  already fixed to a unique pure-pairing ray. The retained J_z")
    print("  direction belongs to the old normal grammar, while every nonzero new")
    print("  transverse source is exactly rephasing-equivalent to mu J_x with")
    print("  mu >= 0.")
    print()
    print("  So the live DM blocker is no longer a local source-vector direction.")
    print("  It is the absolute amplitude / staircase law and its three-generation")
    print("  lift.")
    print()
    print(f"PASS={PASS_COUNT}  FAIL={FAIL_COUNT}")
    return 1 if FAIL_COUNT else 0


if __name__ == "__main__":
    sys.exit(main())
