#!/usr/bin/env python3
"""Narrow runner for HIERARCHY_LT4_KLEIN_FOUR_SIN_SQUARED_UNIFORMITY_NARROW_THEOREM_NOTE_2026-05-10.

Verifies the standalone class-A narrow positive theorem:

  Among even integer L_t in {2, 4, 6, 8, 10, 12, 14, 16}, the per-mode
  weight sin^2((2n + 1) pi / L_t) on the APBC fermion Matsubara mode
  set M(L_t) = {(2n+1) pi / L_t : n = 0, ..., L_t - 1} is uniform
  exactly at L_t in {2, 4} and not at any other scanned value. At
  L_t = 4 the mode set is a single V_4 = Z_2 x Z_2 orbit with
  constant value 1/2.

The Klein-four group V_4 is generated by the involutions
  sigma_1 : omega -> pi - omega,
  sigma_2 : omega -> omega + pi (mod 2 pi).
Both leave sin^2 invariant.

Pure class-A exact-algebraic / rational arithmetic + elementary
group-orbit decomposition. No framework baseline, axiom, or admission is
consumed. The parent narrow source note states this explicitly; the
runner only verifies the trigonometric and orbit-theoretic identities.

Target: PASS = 10, FAIL = 0.
"""

from __future__ import annotations

import sys
from fractions import Fraction
from pathlib import Path

try:
    import sympy as sp
    from sympy import (
        Rational,
        Symbol,
        floor,
        pi,
        simplify,
        sin,
        symbols,
    )
except ImportError:
    print("FAIL: sympy required for exact algebra")
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent

PASS = 0
FAIL = 0


def check(label: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        tag = "PASS (A)"
    else:
        FAIL += 1
        tag = "FAIL (A)"
    suffix = f"  ({detail})" if detail else ""
    print(f"  [{tag}] {label}{suffix}")


def section(title: str) -> None:
    print("\n" + "-" * 88 + f"\n{title}\n" + "-" * 88)


def apbc_modes(L_t: int):
    """Return SymPy expressions for the APBC fermion Matsubara modes M(L_t)."""
    return [Rational(2 * n + 1, L_t) * pi for n in range(L_t)]


def sin_squared_values(L_t: int):
    """Return list of simplified sin^2(omega) for omega in M(L_t)."""
    return [simplify(sin(omega) ** 2) for omega in apbc_modes(L_t)]


def is_uniform(values) -> bool:
    """Check if every entry in `values` is symbolically equal to the first."""
    if not values:
        return True
    first = values[0]
    return all(sp.simplify(v - first) == 0 for v in values[1:])


def reduce_mod_2pi(x):
    """Reduce a SymPy angle expression to the canonical interval [0, 2 pi)."""
    coeff = simplify(x / pi)
    coeff_mod = coeff - floor(coeff / 2) * 2
    return simplify(coeff_mod * pi)


def v4_action(omega):
    """Return the four images { id, sigma_1, sigma_2, sigma_3 } applied to omega.

    sigma_1 : omega -> pi - omega
    sigma_2 : omega -> omega + pi (mod 2 pi)
    sigma_3 : sigma_1 sigma_2 : omega -> -omega (mod 2 pi)
    """
    return [
        reduce_mod_2pi(omega),
        reduce_mod_2pi(pi - omega),
        reduce_mod_2pi(omega + pi),
        reduce_mod_2pi(-omega),
    ]


# ============================================================================
section("Pattern A narrow theorem: L_t=4 Klein-four sin^2 uniformity")
# Statement: among even L_t in {2, 4, 6, 8, 10, 12, 14, 16}, sin^2(omega) is
# uniform on M(L_t) exactly at L_t in {2, 4}; at L_t = 4 the mode set is a
# single V_4 = Z_2 x Z_2 orbit.
# ============================================================================


# ----------------------------------------------------------------------------
section("Part 1: uniformity at L_t = 2 (T1)")
# Trivial uniform case: both modes pi/2 and 3 pi/2 have sin^2 = 1.
# ----------------------------------------------------------------------------

t1_values = sin_squared_values(2)
all_one_t1 = all(v == Rational(1) for v in t1_values)
check(
    "T1: sin^2((2n+1)pi/2) = 1 for n in {0,1} (uniform at L_t=2)",
    all_one_t1,
    detail=f"values = {[str(v) for v in t1_values]}",
)


# ----------------------------------------------------------------------------
section("Part 2: uniformity at L_t = 4 (T2)")
# Main case: all four modes in M(4) have sin^2 = 1/2.
# ----------------------------------------------------------------------------

t2_values = sin_squared_values(4)
all_half_t2 = all(v == Rational(1, 2) for v in t2_values)
check(
    "T2: sin^2((2n+1)pi/4) = 1/2 for n in {0,1,2,3} (uniform at L_t=4)",
    all_half_t2,
    detail=f"values = {[str(v) for v in t2_values]}",
)


# ----------------------------------------------------------------------------
section("Part 3: non-uniformity at L_t = 6 (T3)")
# Explicit values {1/4, 1, 1/4, 1/4, 1, 1/4} from M(6).
# ----------------------------------------------------------------------------

t3_values = sin_squared_values(6)
expected_t3 = [
    Rational(1, 4),
    Rational(1),
    Rational(1, 4),
    Rational(1, 4),
    Rational(1),
    Rational(1, 4),
]
t3_match = all(t3_values[i] == expected_t3[i] for i in range(6))
t3_non_uniform = not is_uniform(t3_values)
check(
    "T3: at L_t=6, sin^2 values are {1/4, 1, 1/4, 1/4, 1, 1/4} (non-uniform)",
    t3_match and t3_non_uniform,
    detail=f"values = {[str(v) for v in t3_values]}",
)


# ----------------------------------------------------------------------------
section("Part 4: non-uniformity at L_t = 8 (T4)")
# sin^2 values include both 1/2 - sqrt(2)/4 and 1/2 + sqrt(2)/4.
# ----------------------------------------------------------------------------

t4_values = sin_squared_values(8)
expected_minus = sp.simplify(Rational(1, 2) - sp.sqrt(2) / 4)
expected_plus = sp.simplify(Rational(1, 2) + sp.sqrt(2) / 4)
has_minus = any(sp.simplify(v - expected_minus) == 0 for v in t4_values)
has_plus = any(sp.simplify(v - expected_plus) == 0 for v in t4_values)
t4_non_uniform = not is_uniform(t4_values)
check(
    "T4: at L_t=8, sin^2 values include 1/2 - sqrt(2)/4 and 1/2 + sqrt(2)/4 (non-uniform)",
    has_minus and has_plus and t4_non_uniform,
    detail=(
        f"has 1/2-sqrt(2)/4 = {has_minus}, has 1/2+sqrt(2)/4 = {has_plus}, "
        f"distinct symbolic values present"
    ),
)


# ----------------------------------------------------------------------------
section("Part 5: scanned uniformity profile (T5)")
# For even L_t in {2, 4, 6, 8, 10, 12, 14, 16}, uniformity holds exactly at
# L_t in {2, 4}.
# ----------------------------------------------------------------------------

scan_lts = [2, 4, 6, 8, 10, 12, 14, 16]
uniformity_profile = {L_t: is_uniform(sin_squared_values(L_t)) for L_t in scan_lts}
uniform_lts = [L_t for L_t, ok in uniformity_profile.items() if ok]
expected_uniform = [2, 4]
profile_match = uniform_lts == expected_uniform
check(
    "T5: uniformity holds exactly at L_t in {2, 4} for even L_t in {2,4,6,8,10,12,14,16}",
    profile_match,
    detail=(
        "profile = "
        + ", ".join(f"L_t={L_t}:{'uniform' if ok else 'split'}"
                    for L_t, ok in uniformity_profile.items())
    ),
)


# ----------------------------------------------------------------------------
section("Part 6: V_4 invariances of sin^2 (T6)")
# Symbolic verification: each V_4 generator preserves sin^2(omega).
# ----------------------------------------------------------------------------

omega = Symbol("omega", real=True)
sigma1_diff = simplify(sin(pi - omega) ** 2 - sin(omega) ** 2)
sigma2_diff = simplify(sin(omega + pi) ** 2 - sin(omega) ** 2)
sigma3_diff = simplify(sin(-omega) ** 2 - sin(omega) ** 2)
all_invariant = (sigma1_diff == 0) and (sigma2_diff == 0) and (sigma3_diff == 0)
check(
    "T6: sin^2(pi - omega) = sin^2(omega + pi) = sin^2(-omega) = sin^2(omega) symbolically",
    all_invariant,
    detail=(
        f"sigma_1 diff = {sigma1_diff}, sigma_2 diff = {sigma2_diff}, "
        f"sigma_3 diff = {sigma3_diff}"
    ),
)


# ----------------------------------------------------------------------------
section("Part 7: V_4 orbit closure of M(4) (T7)")
# Apply { id, sigma_1, sigma_2, sigma_3 } to seed pi/4, reduce mod 2 pi,
# and check the resulting set equals M(4) = { pi/4, 3 pi/4, 5 pi/4, 7 pi/4 }.
# ----------------------------------------------------------------------------

seed_lt4 = pi / 4
orbit_lt4_raw = v4_action(seed_lt4)
orbit_lt4_set = set(simplify(o) for o in orbit_lt4_raw)
expected_lt4_set = set(simplify(m) for m in apbc_modes(4))
orbit_match_lt4 = orbit_lt4_set == expected_lt4_set
check(
    "T7: V_4 orbit of seed pi/4 reproduces M(4) = {pi/4, 3pi/4, 5pi/4, 7pi/4}",
    orbit_match_lt4,
    detail=f"orbit = {sorted(str(s) for s in orbit_lt4_set)}; M(4) = {sorted(str(s) for s in expected_lt4_set)}",
)


# ----------------------------------------------------------------------------
section("Part 8: single-orbit at L_t=4 vs split-orbit at L_t=6 (T8)")
# At L_t = 4, M(4) is a single V_4 orbit (size 4).
# At L_t = 6, M(6) decomposes into orbits {pi/6, 5pi/6, 7pi/6, 11pi/6} (w=1/4)
# and {pi/2, 3pi/2} (w=1), with distinct w values.
# ----------------------------------------------------------------------------


def orbit_decompose(L_t: int):
    """Decompose M(L_t) into V_4 orbits. Returns list of (orbit_set, w_value)."""
    modes = [simplify(m) for m in apbc_modes(L_t)]
    visited = set()
    orbits = []
    for m in modes:
        if m in visited:
            continue
        orbit = set(simplify(x) for x in v4_action(m))
        # restrict to elements of M(L_t)
        orbit = {x for x in orbit if any(simplify(x - mm) == 0 for mm in modes)}
        visited |= orbit
        # representative weight on the orbit
        rep = next(iter(orbit))
        w_val = simplify(sin(rep) ** 2)
        orbits.append((orbit, w_val))
    return orbits


orbits_lt4 = orbit_decompose(4)
orbits_lt6 = orbit_decompose(6)

single_orbit_lt4 = (
    len(orbits_lt4) == 1
    and len(orbits_lt4[0][0]) == 4
    and orbits_lt4[0][1] == Rational(1, 2)
)

# At L_t = 6, expect two orbits: size-4 with w=1/4 and size-2 with w=1.
two_orbits_lt6 = len(orbits_lt6) == 2
sizes_lt6 = sorted(len(o) for o, _ in orbits_lt6)
weights_lt6 = sorted(orbits_lt6, key=lambda x: len(x[0]))
size_pattern_lt6 = sizes_lt6 == [2, 4]
# w=1 on the size-2 orbit, w=1/4 on the size-4 orbit
size2_orbit = next(o for o in orbits_lt6 if len(o[0]) == 2)
size4_orbit = next(o for o in orbits_lt6 if len(o[0]) == 4)
weight_pattern_lt6 = size2_orbit[1] == Rational(1) and size4_orbit[1] == Rational(1, 4)
distinct_weights_lt6 = simplify(size2_orbit[1] - size4_orbit[1]) != 0

t8_ok = (
    single_orbit_lt4
    and two_orbits_lt6
    and size_pattern_lt6
    and weight_pattern_lt6
    and distinct_weights_lt6
)
check(
    "T8: M(4) is a single V_4 orbit (w=1/2); M(6) splits 4+2 with w=(1/4, 1) distinct",
    t8_ok,
    detail=(
        f"L_t=4 orbits = {len(orbits_lt4)} (sizes={[len(o) for o,_ in orbits_lt4]}, "
        f"weights={[str(w) for _,w in orbits_lt4]}); "
        f"L_t=6 orbits = {len(orbits_lt6)} (sizes={sizes_lt6}, "
        f"weights={[str(w) for _,w in orbits_lt6]})"
    ),
)


# ----------------------------------------------------------------------------
section("Part 9: V_4 group structure (T9)")
# Each non-identity element of {sigma_1, sigma_2, sigma_3} has order 2 on
# the quotient R / 2 pi Z, and pairwise products give the third element on
# the same quotient. We verify this structurally by working with reduced
# representatives via reduce_mod_2pi() at three independent test seeds (an
# irrational angle would require special handling in floor(); we use
# rational seeds where reduce_mod_2pi is well-defined).
# ----------------------------------------------------------------------------


def sigma1(x):
    return pi - x


def sigma2(x):
    return x + pi


def sigma3(x):
    return -x


# Test seeds: three rational multiples of pi covering generic positions.
# Chosen so reduce_mod_2pi is exact (no irrational floor needed).
test_seeds = [pi / 4, pi / 6, 2 * pi / 5]

t9_ok_per_seed = []
t9_details = []
for seed in test_seeds:
    s = simplify(seed)
    # sigma_i^2 acting on s, then reduced mod 2 pi, equals s:
    s11 = reduce_mod_2pi(sigma1(sigma1(s)))
    s22 = reduce_mod_2pi(sigma2(sigma2(s)))
    s33 = reduce_mod_2pi(sigma3(sigma3(s)))
    s_red = reduce_mod_2pi(s)
    order_2 = (
        simplify(s11 - s_red) == 0
        and simplify(s22 - s_red) == 0
        and simplify(s33 - s_red) == 0
    )
    # sigma_1 * sigma_2 = sigma_3, sigma_2 * sigma_1 = sigma_3,
    # sigma_2 * sigma_3 = sigma_1, sigma_1 * sigma_3 = sigma_2 (all mod 2 pi):
    prod_12 = reduce_mod_2pi(sigma1(sigma2(s)))
    prod_21 = reduce_mod_2pi(sigma2(sigma1(s)))
    prod_23 = reduce_mod_2pi(sigma2(sigma3(s)))
    prod_13 = reduce_mod_2pi(sigma1(sigma3(s)))
    target_3 = reduce_mod_2pi(sigma3(s))
    target_1 = reduce_mod_2pi(sigma1(s))
    target_2 = reduce_mod_2pi(sigma2(s))
    prods_close = (
        simplify(prod_12 - target_3) == 0
        and simplify(prod_21 - target_3) == 0
        and simplify(prod_23 - target_1) == 0
        and simplify(prod_13 - target_2) == 0
    )
    seed_ok = order_2 and prods_close
    t9_ok_per_seed.append(seed_ok)
    t9_details.append(f"seed={seed}: order_2={order_2}, prods={prods_close}")

t9_ok = all(t9_ok_per_seed)
check(
    "T9: V_4 group structure: sigma_i^2 = id and pairwise products = third (on R/2piZ)",
    t9_ok,
    detail=" | ".join(t9_details),
)


# ----------------------------------------------------------------------------
section("Part 10: trivial V_4 orbit at L_t = 2 (T10)")
# Apply { id, sigma_1, sigma_2, sigma_3 } to seed pi/2 and check the result
# (after restriction to M(2)) reproduces M(2) = { pi/2, 3 pi/2 }.
# Note: sigma_1(pi/2) = pi/2 is an internal fixed point (the seed reflects
# to itself), illustrating the "trivial" character of the L_t = 2 case.
# ----------------------------------------------------------------------------

seed_lt2 = pi / 2
orbit_lt2_raw = v4_action(seed_lt2)
orbit_lt2_set = set(simplify(o) for o in orbit_lt2_raw)
expected_lt2_set = set(simplify(m) for m in apbc_modes(2))
orbit_match_lt2 = orbit_lt2_set == expected_lt2_set
# sigma_1 fixes pi/2:
sigma1_fixed_pi2 = simplify(sigma1(pi / 2) - pi / 2) == 0
t10_ok = orbit_match_lt2 and sigma1_fixed_pi2
check(
    "T10: V_4 orbit of seed pi/2 reproduces M(2) = {pi/2, 3pi/2}; sigma_1 fixes pi/2",
    t10_ok,
    detail=(
        f"orbit = {sorted(str(s) for s in orbit_lt2_set)}; "
        f"M(2) = {sorted(str(s) for s in expected_lt2_set)}; "
        f"sigma_1(pi/2) = pi/2: {sigma1_fixed_pi2}"
    ),
)


# ----------------------------------------------------------------------------
section("Informational: per-L_t mode list")
# Print the explicit sin^2 values for each scanned L_t (informational only,
# not part of pass/fail target).
# ----------------------------------------------------------------------------

print("\n  Mode-by-mode sin^2 values (informational):")
for L_t in scan_lts:
    vals = sin_squared_values(L_t)
    print(f"    L_t = {L_t:2d}: {[str(v) for v in vals]}")


# ----------------------------------------------------------------------------
section("Narrow theorem summary")
# ----------------------------------------------------------------------------
print(
    """
  Narrow Pattern A theorem statement (recapitulation):

  HYPOTHESIS:
    Let L_t >= 2 be an even integer. Define
       M(L_t)  =  { (2n+1) pi / L_t : n = 0, ..., L_t - 1 }
    and the per-mode weight w(omega) = sin^2(omega).

  CONCLUSION:
    Among even L_t in {2, 4, 6, 8, 10, 12, 14, 16}, the multiset
       { w(omega) : omega in M(L_t) }
    is constant (uniform) exactly at L_t in {2, 4} (with values 1
    and 1/2 respectively); at every other scanned L_t the multiset
    contains at least two distinct symbolic values. At L_t = 4 the
    entire mode set forms a single V_4 = Z_2 x Z_2 orbit, which
    structurally explains the uniformity.

  Audit-lane class:
    (A) - pure exact-algebraic / rational arithmetic + elementary
    group-orbit decomposition. No external numerical input. No framework
    baseline or admission consumed.

  This narrow theorem is independent of:
    - The framework's selection of L_t = 4 as the physical block
      (separate, bilinear-selector question).
    - The hierarchy formula v = M_Pl x alpha_LM^16 x (7/8)^(1/4).
    - The (7/8) and (1/4) exponents (separate narrow theorems).
    - Any physical interpretation of M(L_t) beyond its algebraic
      definition.
"""
)


print(f"\n{'=' * 88}\n  TOTAL: PASS={PASS}, FAIL={FAIL}\n{'=' * 88}")
sys.exit(1 if FAIL > 0 else 0)
