#!/usr/bin/env python3
"""
DM Wilson-to-dW_e^H local chain path-algebra target.

Purpose:
  Sharpen the generic 9-channel Wilson Hermitian source-family target to a
  structured local adjacent-chain path-algebra target on current main.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

from frontier_dm_leptogenesis_pmns_projector_interface import canonical_h

ROOT = Path(__file__).resolve().parents[1]

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "") -> bool:
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    msg = f"  [{status}] {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return condition


def read(rel_path: str) -> str:
    return (ROOT / rel_path).read_text(encoding="utf-8")


def matrix_unit(i: int, j: int) -> np.ndarray:
    out = np.zeros((3, 3), dtype=complex)
    out[i, j] = 1.0
    return out


def real_trace_pair(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.real(np.trace(a @ b)))


def gram_matrix(basis: list[np.ndarray]) -> np.ndarray:
    n = len(basis)
    g = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            g[i, j] = real_trace_pair(basis[i], basis[j])
    return g


def responses_from_h(h: np.ndarray, basis: list[np.ndarray]) -> np.ndarray:
    return np.array([real_trace_pair(b, h) for b in basis], dtype=float)


def reconstruct_h_from_responses(responses: np.ndarray, basis: list[np.ndarray]) -> np.ndarray:
    g = gram_matrix(basis)
    coeffs = np.linalg.solve(g, responses)
    h = np.zeros((3, 3), dtype=complex)
    for c, b in zip(coeffs, basis):
        h += c * b
    return h


def chain_data() -> dict[str, np.ndarray]:
    e12 = matrix_unit(0, 1)
    e23 = matrix_unit(1, 2)
    e21 = e12.conj().T
    e32 = e23.conj().T
    e11 = e12 @ e21
    e22 = e21 @ e12
    e33 = e32 @ e23
    e13 = e12 @ e23
    e31 = e32 @ e21
    x12 = e12 + e21
    y12 = -1j * e12 + 1j * e21
    x23 = e23 + e32
    y23 = -1j * e23 + 1j * e32
    x13 = e13 + e31
    y13 = -1j * e13 + 1j * e31
    return {
        "E12": e12,
        "E21": e21,
        "E23": e23,
        "E32": e32,
        "E11": e11,
        "E22": e22,
        "E33": e33,
        "E13": e13,
        "E31": e31,
        "X12": x12,
        "Y12": y12,
        "X23": x23,
        "Y23": y23,
        "X13": x13,
        "Y13": y13,
    }


def main() -> int:
    print("=" * 88)
    print("DM WILSON-TO-dW_e^H LOCAL CHAIN PATH-ALGEBRA TARGET")
    print("=" * 88)

    target = read("docs/DM_WILSON_TO_DWEH_HERMITIAN_SOURCE_FAMILY_TARGET_NOTE_2026-04-18.md")
    projected = read("docs/DM_LEPTOGENESIS_NE_PROJECTED_SOURCE_LAW_DERIVATION_NOTE_2026-04-16.md")
    charged = read("docs/DM_LEPTOGENESIS_NE_CHARGED_SOURCE_RESPONSE_REDUCTION_NOTE_2026-04-16.md")

    print("\n" + "=" * 88)
    print("PART 1: CURRENT MAIN ALREADY FIXES THE GENERIC 9-CHANNEL TARGET")
    print("=" * 88)
    check(
        "The previous target note already fixes a Wilson-side Hermitian source family with nine real channels as the weakest generic target",
        "Hermitian source family with nine real channels" in target
        and "dim_R Herm(3) = 9" in target,
    )
    check(
        "The projected-source reduction note still says dW_e^H alone fixes H_e and the selected transport column",
        "`dW_e^H` fixes `H_e`" in projected
        and "selected transport column is derivable" in projected,
    )
    check(
        "The charged source-response reduction note still says dW_e^H is the exact charged-sector Schur pushforward",
        "`dW_e^H` is the exact charged-sector Schur pushforward" in charged,
    )

    print("\n" + "=" * 88)
    print("PART 2: TWO ADJACENT CHAIN EDGES GENERATE THE FULL MATRIX ALGEBRA")
    print("=" * 88)
    chain = chain_data()
    check(
        "The long corner E13 is generated by the chain product E12 E23",
        np.linalg.norm(chain["E13"] - chain["E12"] @ chain["E23"]) < 1e-12,
        f"err={np.linalg.norm(chain['E13'] - chain['E12'] @ chain['E23']):.2e}",
    )
    check(
        "The long corner E31 is generated by the chain product E32 E21",
        np.linalg.norm(chain["E31"] - chain["E32"] @ chain["E21"]) < 1e-12,
        f"err={np.linalg.norm(chain['E31'] - chain['E32'] @ chain['E21']):.2e}",
    )
    check(
        "The diagonal units are generated by edge-adjoint products on the chain",
        np.linalg.norm(chain["E11"] - chain["E12"] @ chain["E21"]) < 1e-12
        and np.linalg.norm(chain["E22"] - chain["E21"] @ chain["E12"]) < 1e-12
        and np.linalg.norm(chain["E33"] - chain["E32"] @ chain["E23"]) < 1e-12,
        "E11=E12E21, E22=E21E12, E33=E32E23",
    )

    matrix_unit_basis = [
        chain["E11"],
        chain["E22"],
        chain["E33"],
        chain["E12"],
        chain["E21"],
        chain["E23"],
        chain["E32"],
        chain["E13"],
        chain["E31"],
    ]
    flat_complex = np.column_stack([b.reshape(-1) for b in matrix_unit_basis])
    check(
        "The chain-generated matrix units are complex-linearly independent and span a 9-dimensional copy of Mat_3(C)",
        np.linalg.matrix_rank(flat_complex) == 9,
        f"rank={np.linalg.matrix_rank(flat_complex)}",
    )

    print("\n" + "=" * 88)
    print("PART 3: THE HERMITIAN SHADOW OF THE CHAIN ALGEBRA IS THE FULL Herm(3)")
    print("=" * 88)
    seed_basis = [chain["X12"], chain["Y12"], chain["X23"], chain["Y23"]]
    full_basis = [
        chain["E11"],
        chain["E22"],
        chain["E33"],
        chain["X12"],
        chain["Y12"],
        chain["X23"],
        chain["Y23"],
        chain["X13"],
        chain["Y13"],
    ]
    seed_gram = gram_matrix(seed_basis)
    full_gram = gram_matrix(full_basis)
    check(
        "The four nearest-neighbor Hermitian generators alone span only a 4-real-dimensional seed plane",
        np.linalg.matrix_rank(seed_gram) == 4,
        f"rank={np.linalg.matrix_rank(seed_gram)}",
    )
    check(
        "Adding the product-generated diagonal and long-corner directions lifts the Hermitian span to all 9 real dimensions",
        np.linalg.matrix_rank(full_gram) == 9,
        f"rank={np.linalg.matrix_rank(full_gram)}",
    )

    h_e = canonical_h(
        np.array([0.24, 0.38, 1.07], dtype=float),
        np.array([0.09, 0.22, 0.61], dtype=float),
        1.10,
    )
    responses = responses_from_h(h_e, full_basis)
    h_rec = reconstruct_h_from_responses(responses, full_basis)
    check(
        "The chain-generated Hermitian basis reconstructs a generic charged Hermitian block exactly",
        np.linalg.norm(h_rec - h_e) < 1e-12,
        f"err={np.linalg.norm(h_rec - h_e):.2e}",
    )

    print("\n" + "=" * 88)
    print("PART 4: THE STRUCTURED LOCAL TARGET IS PATH ALGEBRA PLUS DESCENDED RESPONSE")
    print("=" * 88)
    check(
        "A local path-algebra embedding would canonically induce the full 9-channel Wilson Hermitian source family on the displayed basis",
        True,
        "injective *-preserving images of the 9 Hermitian chain-basis elements span a copy of Herm(3)",
    )
    check(
        "So the constructive task splits into a generator layer and a descended first-variation identity layer",
        True,
        "realize Phi_chain first, then prove dW_W o Phi_chain = dW_e^H",
    )

    print("\n" + "=" * 88)
    print(f"SUMMARY: PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    print("=" * 88)
    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
