#!/usr/bin/env python3
"""Audit the universal invariant-frame obstruction from representation data.

This checks whether the universal complement can be canonically framed from
representation-theoretic invariants alone. The answer should be negative:

1. `Pi_A1` is exact and invariant.
2. the complement carries nontrivial `SO(3)` action.
3. the shared-axis decomposition has two weight-1 doublets plus a weight-2
   sector, so the multiplicity space is not canonically split.
4. the quotient-kernel spectrum is frame-invariant, so it cannot select a
   preferred complement section.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

OBSERVABLE = DOCS / "OBSERVABLE_PRINCIPLE_FROM_AXIOM_NOTE.md"
ROUTE2 = DOCS / "S3_ANOMALY_SPACETIME_LIFT_NOTE.md"
VARIATIONAL = DOCS / "UNIVERSAL_GR_TENSOR_VARIATIONAL_CANDIDATE_NOTE.md"
UNIQUENESS = DOCS / "UNIVERSAL_GR_TENSOR_QUOTIENT_UNIQUENESS_NOTE.md"
A1_NOTE = DOCS / "UNIVERSAL_GR_A1_INVARIANT_SECTION_NOTE.md"
WDECOMP = DOCS / "POLARIZATION_UNIVERSAL_WEIGHT_DECOMPOSITION_NOTE.md"
CONNECTION = DOCS / "UNIVERSAL_GR_CANONICAL_PROJECTOR_CONNECTION_NOTE.md"


@dataclass
class Check:
    name: str
    ok: bool
    detail: str


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def has(text: str, needle: str) -> bool:
    return needle.lower() in text.lower()


def sym(i: int, j: int, n: int = 4) -> np.ndarray:
    m = np.zeros((n, n), dtype=float)
    if i == j:
        m[i, j] = 1.0
    else:
        scale = math.sqrt(2.0)
        m[i, j] = 1.0 / scale
        m[j, i] = 1.0 / scale
    return m


def diag(vals: Sequence[float]) -> np.ndarray:
    return np.diag(np.asarray(vals, dtype=float))


def canonical_polarization_frame() -> list[np.ndarray]:
    """Canonical lapse/shift/trace/shear basis on the symmetric `3+1` sector."""

    sqrt2 = math.sqrt(2.0)
    sqrt3 = math.sqrt(3.0)
    sqrt6 = math.sqrt(6.0)
    return [
        sym(0, 0),
        sym(0, 1),
        sym(0, 2),
        sym(0, 3),
        diag((0.0, 1.0 / sqrt3, 1.0 / sqrt3, 1.0 / sqrt3)),
        diag((0.0, 1.0 / sqrt2, -1.0 / sqrt2, 0.0)),
        diag((0.0, 1.0 / sqrt6, 1.0 / sqrt6, -2.0 / sqrt6)),
        sym(1, 2),
        sym(1, 3),
        sym(2, 3),
    ]


def rotation(axis: str, theta: float) -> np.ndarray:
    c = math.cos(theta)
    s = math.sin(theta)
    rot = np.eye(4)
    if axis == "x":
        rot[2, 2] = c
        rot[2, 3] = -s
        rot[3, 2] = s
        rot[3, 3] = c
    elif axis == "y":
        rot[1, 1] = c
        rot[1, 3] = s
        rot[3, 1] = -s
        rot[3, 3] = c
    elif axis == "z":
        rot[1, 1] = c
        rot[1, 2] = -s
        rot[2, 1] = s
        rot[2, 2] = c
    else:
        raise ValueError(axis)
    return rot


def frob(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.tensordot(a, b, axes=2))


def rotate_tensor(rot: np.ndarray, basis: np.ndarray) -> np.ndarray:
    return rot.T @ basis @ rot


def rep_matrix(rot: np.ndarray, frame: Sequence[np.ndarray]) -> np.ndarray:
    out = np.zeros((len(frame), len(frame)), dtype=float)
    for j, basis in enumerate(frame):
        img = rotate_tensor(rot, basis)
        for i, ref in enumerate(frame):
            out[i, j] = frob(ref, img)
    return out


def pi_a1() -> np.ndarray:
    p = np.zeros((10, 10), dtype=float)
    p[0, 0] = 1.0
    p[4, 4] = 1.0
    return p


def commutant_dim(gens: Sequence[np.ndarray], tol: float = 1e-10) -> int:
    """Dimension of the commutant of the algebra generated by gens."""

    n = gens[0].shape[0]
    blocks = []
    for g in gens:
        blocks.append(np.kron(np.eye(n), g.T) - np.kron(g, np.eye(n)))
    mat = np.vstack(blocks)
    s = np.linalg.svd(mat, compute_uv=False)
    return int(np.sum(s < tol))


def bilinear(a: np.ndarray, b: np.ndarray, d: Sequence[float]) -> float:
    total = 0.0
    for i in range(len(d)):
        for j in range(len(d)):
            total += a[i, j] * b[j, i] / (d[i] * d[j])
    return -total


def sym_basis(n: int) -> list[np.ndarray]:
    basis: list[np.ndarray] = []
    for i in range(n):
        m = np.zeros((n, n), dtype=float)
        m[i, i] = 1.0
        basis.append(m)
    for i in range(n):
        for j in range(i + 1, n):
            m = np.zeros((n, n), dtype=float)
            s = math.sqrt(2.0)
            m[i, j] = 1.0 / s
            m[j, i] = 1.0 / s
            basis.append(m)
    return basis


def gram_matrix(basis: Sequence[np.ndarray], d: Sequence[float]) -> np.ndarray:
    return np.array([[bilinear(a, b, d) for b in basis] for a in basis], dtype=float)


def gram_spectrum(gram: np.ndarray) -> np.ndarray:
    return np.sort(np.round(np.linalg.eigvalsh(gram), 12))


def rotated_basis(rot: np.ndarray, basis: Sequence[np.ndarray]) -> list[np.ndarray]:
    return [rotate_tensor(rot, b) for b in basis]


def count_weights(gen: np.ndarray, tol: float = 1e-9) -> dict[int, int]:
    eigs = np.linalg.eigvals(gen)
    counts: dict[int, int] = {}
    for z in eigs:
        w = int(round(abs(float(np.imag(z)))))
        if abs(float(np.real(z))) > tol:
            raise ValueError(f"generator has non-pure-imag eigenvalue {z}")
        counts[w] = counts.get(w, 0) + 1
    return dict(sorted(counts.items()))


def main() -> int:
    obs = read(OBSERVABLE)
    route2 = read(ROUTE2)
    var = read(VARIATIONAL)
    uni = read(UNIQUENESS)
    a1 = read(A1_NOTE)
    wdec = read(WDECOMP)
    conn = read(CONNECTION)

    frame = canonical_polarization_frame()
    projector = pi_a1()
    comp = np.eye(10) - projector

    rots = {
        "x": rotation("x", math.pi / 7.0),
        "y": rotation("y", math.pi / 5.0),
        "z": rotation("z", math.pi / 6.0),
    }
    reps = {k: rep_matrix(r, frame) for k, r in rots.items()}
    gens = {}
    for axis in "xyz":
        plus = rep_matrix(rotation(axis, 1e-6), frame)
        minus = rep_matrix(rotation(axis, -1e-6), frame)
        gens[axis] = (plus - minus) / (2.0e-6)

    gen_rank = int(np.linalg.matrix_rank(np.stack([gens["x"], gens["y"], gens["z"]]).reshape(3, -1), tol=1e-10))
    comp_gens = [comp @ gens[k] @ comp for k in "xyz"]
    comp_comm_dim = commutant_dim(comp_gens)

    # Shared-axis weight decomposition about x.
    x_gen = comp @ gens["x"] @ comp
    weights = count_weights(x_gen)
    doublets = {w: weights.get(w, 0) // 2 for w in weights if w > 0}

    # Weight-1 multiplicity model: two identical SO(2) doublets.
    j = np.array([[0.0, -1.0], [1.0, 0.0]], dtype=float)
    w1_model = np.block([[j, np.zeros((2, 2))], [np.zeros((2, 2)), j]])
    w1_comm_dim = commutant_dim([w1_model])

    # Quotient-kernel spectrum: invariant under valid frame rotations.
    d = (2.0, 3.0, 5.0, 7.0)
    basis = sym_basis(4)
    gram = gram_matrix(basis, d)
    rot_basis = rotated_basis(rots["y"], basis)
    gram_rot = gram_matrix(rot_basis, d)
    spec = gram_spectrum(gram)
    spec_rot = gram_spectrum(gram_rot)
    spec_delta = float(np.max(np.abs(spec - spec_rot)))

    checks = [
        ("scalar generator is exact", has(obs, "observable principle") and has(obs, "det(d+j)") and has(obs, "det d"), "scalar generator is the exact observable-principle output"),
        ("3+1 lift is exact", has(route2, "pl s^3 x r") or has(route2, "o_lift = 1"), "Route 2 gives the exact PL S^3 x R lift"),
        ("tensor candidate is exact as a construction", has(var, "metric-source hessian") and has(var, "s_gr^cand"), "tensor-valued Hessian candidate is exact as a construction"),
        ("quotient uniqueness is exact", has(uni, "unique symmetric `3+1` quotient kernel") or has(uni, "unique bilinear lift"), "symmetric quotient kernel is unique on the finite prototype"),
        ("A1 projector is exact and rank-2", int(np.linalg.matrix_rank(projector)) == 2, "Pi_A1 fixes lapse and spatial trace"),
        ("A1 projector commutes with valid spatial rotations", max(np.linalg.norm(projector @ reps[k] - reps[k] @ projector, ord='fro') for k in reps) < 1e-12, "Pi_A1 is invariant to machine precision"),
        ("complement carries a nontrivial spatial rotation algebra", gen_rank == 3 and all(np.linalg.norm(comp @ gens[k] @ comp, ord='fro') > 1e-6 for k in "xyz"), f"generator rank = {gen_rank}"),
        ("shared-axis complement weight decomposition has two weight-1 doublets and one weight-2 sector", weights.get(0, 0) == 4 and doublets.get(1, 0) == 2 and doublets.get(2, 0) == 1, f"weight multiplicities = {weights}; doublets = {doublets}"),
        ("weight-1 multiplicity space is not canonically split", w1_comm_dim >= 4, f"weight-1 commutant dimension = {w1_comm_dim}"),
        ("quotient-kernel spectrum is frame-invariant", spec_delta < 1e-12, f"max spectrum delta under rotation = {spec_delta:.3e}"),
        ("current universal notes still stop at an orbit bundle", has(conn, "orbit bundle") and has(conn, "SO(3)") and has(conn, "distinguished connection"), "notes record only an orbit bundle, not a canonical section"),
        ("exact invariant section note is present", has(a1, "Pi_A1") and has(a1, "lapse") and has(a1, "spatial trace"), "A1 invariant section is explicitly recorded"),
        ("weight decomposition note is present", has(wdec, "weight-1 doublets") and has(wdec, "weight-2 sector"), "weight decomposition is explicitly recorded"),
    ]

    print("UNIVERSAL GR INVARIANT FRAME OBSTRUCTION AUDIT")
    print("=" * 78)
    for name, ok, detail in checks:
        tag = "PASS" if ok else "FAIL"
        print(f"[{tag}] {name}")
        print(f"    {detail}")

    print("\n" + "=" * 78)
    print("REPRESENTATION DATA")
    print("=" * 78)
    print(f"Pi_A1_rank = {int(np.linalg.matrix_rank(projector))}")
    print(f"generator_rank = {gen_rank}")
    print(f"complement_commutant_dim = {comp_comm_dim}")
    print(f"weight_multiplicities_x = {weights}")
    print(f"weight_doublets_x = {doublets}")
    print(f"weight1_commutant_dim = {w1_comm_dim}")
    print(f"quotient_spectrum_delta = {spec_delta:.12e}")

    print("\n" + "=" * 78)
    print("CANDIDATE")
    print("=" * 78)
    print("Pi_A1 = diag(1,0,0,0,1,0,0,0,0,0)")
    print("Strongest invariant-frame candidate = Pi_A1-anchored orbit bundle")
    print("P_curv^cand = (Pi_A1, O_{E \\oplus T1}, omega_MC)")
    print("Residual gauge = SO(3) on the universal complement")
    print("Shared-axis obstruction = two equivalent weight-1 doublets")
    print("Weight-1 multiplicity space = 8D real commutant, hence no canonical section")

    print("\n" + "=" * 78)
    print("SUMMARY")
    print("=" * 78)
    n_pass = sum(ok for _, ok, _ in checks)
    n_fail = len(checks) - n_pass
    print(f"PASS={n_pass} FAIL={n_fail} TOTAL={len(checks)}")
    if n_fail == 0:
        print(
            "Representation-theoretic invariants alone do not canonically fix the "
            "universal complement frame. They determine the exact invariant A1 "
            "section and the orbit bundle, but leave an SO(3) complement orbit "
            "and a two-copy weight-1 multiplicity space unresolved."
        )
        return 0

    print("One or more candidate checks failed.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
