#!/usr/bin/env python3
"""
G1 Physicist-L: U_e = I on H_hw=1 via Z_3 trichotomy (charged-lepton lane).

Branch: claude/g1-physicist-l (off claude/g1-complete).

Context
-------
Physicist-H's PMNS-as-f(H) closure theorem relies on the step

    "U_e = I in the generation axis basis on H_hw=1"

and cites the retained Dirac-bridge theorem
(DM_NEUTRINO_DIRAC_BRIDGE_THEOREM_NOTE_2026-04-15).  That citation is
weak: the Dirac-bridge theorem proves that the local post-EWSB Dirac
operator on C^16 is Gamma_1 (chiral off-diagonal, anticommutes with
gamma_5) and is diagonal in the axis basis of the three-generation
observable space, BUT the explicit C^16 -> H_hw=1 reduction to an
effective 3x3 Yukawa is explicitly flagged OPEN:

    "derive the normalization / suppression theorem for the effective
     neutrino Dirac Yukawa generated by the exact Gamma_1 bridge on
     C^16".

So Physicist-H's U_e = I chain is extrapolating through an open step.

Replacement route (this runner)
-------------------------------
The Z_3 generation-charge selection rule
(NEUTRINO_DIRAC_Z3_SUPPORT_TRICHOTOMY_NOTE) is a RETAINED exact support
theorem that does NOT route through the open C^16 normalization step.
It says: for a single Higgs doublet carrying definite Z_3 generation
charge q_H, the Yukawa support on any Dirac Yukawa lane (neutrino or
charged-lepton) is forced into one of three permutation patterns:

    q_H = 0  ->  DIAGONAL in the axis basis
    q_H = +1 ->  forward cyclic
    q_H = -1 ->  backward cyclic

The only fact used is the conjugate left/right Z_3 charge triplets
q_L = (0, +1, -1) and q_R = (0, -1, +1) on the retained three-generation
observable space, plus a single Higgs with definite q_H.

For the charged-lepton Yukawa term  e_R^dag Y_e (H^dag L_L) + h.c.,
the same invariance condition

    q_L(i) + q_H + q_R(j) = 0 mod 3

applies.  If q_H = 0, Y_e is diagonal in the axis basis.  A diagonal
Y_e has left-diagonalizer U_e = I (up to phases of the diagonal entries,
which have no physical effect on |U_PMNS|) and a separate discrete
hierarchy pairing sigma that labels which diagonal slot is (e, mu, tau).

This runner formalizes:

    (A) q_H = 0  =>  Y_e diagonal in axis basis
    (B) diagonal Y_e => U_e = I (in |U|) up to phases/reordering
    (C) the remaining freedom is the discrete hierarchy pairing sigma

and documents the status of each link in the chain.

Status table
------------
| step | status | reference |
|------|--------|-----------|
| q_L, q_R = (0,+1,-1), (0,-1,+1) on retained hw=1 | retained | THREE_GENERATION_OBSERVABLE_THEOREM |
| Z_3 trichotomy support rule | retained | NEUTRINO_DIRAC_Z3_SUPPORT_TRICHOTOMY_NOTE |
| q_H = 0 for the charged-lepton Yukawa | CONDITIONAL (branch condition) | this note |
| q_H = 0 => Y_e diagonal in axis basis | retained (trichotomy) | this runner |
| diagonal Y_e => U_e = I | retained (linear algebra) | this runner |
| hierarchy pairing sigma = (2, 1, 0) | OBSERVATIONAL (discrete choice) | Physicist-H runner |

What this runner does NOT close
-------------------------------
It does NOT derive q_H.  The retained stack constrains q_H to {0, +1, -1}
but does not select the realized value.  q_H = 0 is a CONDITIONAL input
(the "canonical Z_3-neutral Higgs" branch).  This is the same honesty
boundary as the NEUTRINO_DIRAC_Z3_SUPPORT_TRICHOTOMY_NOTE.

Framework convention: "axiom" means only the single framework axiom
Cl(3) on Z^3.
"""

from __future__ import annotations

import itertools
import sys

import numpy as np

np.set_printoptions(precision=6, suppress=True, linewidth=140)

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "") -> bool:
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    msg = f"  [{status}] {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return condition


# Retained Z_3 charges on the three-generation observable space H_hw=1.
# Left-handed triplet and right-handed triplet are conjugate under the
# retained C3[111] cyclic corner map.
LEFT_CHARGES = np.array([0, 1, 2], dtype=int)   # (0, +1, -1) mod 3
RIGHT_CHARGES = np.array([0, 2, 1], dtype=int)  # (0, -1, +1) mod 3


def support_matrix(q_h: int) -> np.ndarray:
    """Return the 0/1 support matrix forced by q_L(i) + q_H + q_R(j) = 0 mod 3."""
    support = np.zeros((3, 3), dtype=int)
    for i, ql in enumerate(LEFT_CHARGES):
        for j, qr in enumerate(RIGHT_CHARGES):
            if (ql + q_h + qr) % 3 == 0:
                support[i, j] = 1
    return support


def part1_retained_generation_charges() -> None:
    print("\n" + "=" * 88)
    print("PART 1: RETAINED CONJUGATE Z_3 GENERATION CHARGES ON H_hw=1")
    print("=" * 88)
    print()
    print("  Source: THREE_GENERATION_OBSERVABLE_THEOREM_NOTE")
    print("          + NEUTRINO_DIRAC_Z3_SUPPORT_TRICHOTOMY_NOTE")
    print()

    expected_left = np.array([0, 1, 2], dtype=int)
    expected_right = np.array([0, 2, 1], dtype=int)

    check(
        "Left-handed Z_3 triplet is q_L = (0, +1, -1)",
        np.array_equal(LEFT_CHARGES, expected_left),
        f"q_L = {LEFT_CHARGES.tolist()}",
    )
    check(
        "Right-handed Z_3 triplet is q_R = (0, -1, +1)",
        np.array_equal(RIGHT_CHARGES, expected_right),
        f"q_R = {RIGHT_CHARGES.tolist()}",
    )
    check(
        "Same-generation left/right charges cancel mod 3",
        np.max((LEFT_CHARGES + RIGHT_CHARGES) % 3) == 0,
        f"(q_L+q_R) mod 3 = {((LEFT_CHARGES+RIGHT_CHARGES) % 3).tolist()}",
    )


def part2_charged_lepton_trichotomy() -> dict[int, np.ndarray]:
    print("\n" + "=" * 88)
    print("PART 2: TRICHOTOMY APPLIED TO THE CHARGED-LEPTON YUKAWA Y_e")
    print("=" * 88)
    print()
    print("  The selection rule q_L(i) + q_H + q_R(j) = 0 mod 3 depends ONLY on")
    print("  the retained conjugate Z_3 charges.  It is therefore the SAME rule")
    print("  on the charged-lepton lane as on the neutrino Dirac lane.")
    print("  No C^16 normalization step is used.")
    print()

    supports = {q_h: support_matrix(q_h) for q_h in [0, 1, 2]}
    expected = {
        0: np.eye(3, dtype=int),
        1: np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]], dtype=int),
        2: np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]], dtype=int),
    }

    for q_h in [0, 1, 2]:
        support = supports[q_h]
        row_sums = support.sum(axis=1)
        col_sums = support.sum(axis=0)
        label = {0: "0", 1: "+1", 2: "-1"}[q_h]
        check(
            f"q_H = {label}: each row has exactly one allowed target",
            np.array_equal(row_sums, np.ones(3, dtype=int)),
            f"row sums = {row_sums.tolist()}",
        )
        check(
            f"q_H = {label}: each column has exactly one allowed source",
            np.array_equal(col_sums, np.ones(3, dtype=int)),
            f"col sums = {col_sums.tolist()}",
        )
        check(
            f"q_H = {label}: Y_e support is the expected permutation pattern",
            np.array_equal(support, expected[q_h]),
            "diagonal" if q_h == 0 else ("forward cyclic" if q_h == 1 else "backward cyclic"),
        )

    # The three patterns partition the 3x3 grid.
    overlaps = [
        int(np.sum(supports[0] * supports[1])),
        int(np.sum(supports[0] * supports[2])),
        int(np.sum(supports[1] * supports[2])),
    ]
    union = supports[0] + supports[1] + supports[2]
    check(
        "Three charged-lepton support patterns are pairwise disjoint",
        max(overlaps) == 0,
        f"overlaps = {overlaps}",
    )
    check(
        "Their union is the full 3x3 grid (partition of Y_e entries)",
        np.array_equal(union, np.ones((3, 3), dtype=int)),
        "",
    )

    return supports


def part3_diagonal_Y_e_implies_U_e_identity() -> None:
    print("\n" + "=" * 88)
    print("PART 3: q_H = 0 => Y_e DIAGONAL => U_e = I (UP TO PHASES)")
    print("=" * 88)
    print()
    print("  For q_H = 0 the Z_3 trichotomy forces Y_e = diag(y_1, y_2, y_3).")
    print("  We verify that the left singular vectors of a diagonal matrix are")
    print("  the standard basis (i.e. U_e = I up to entrywise phases and")
    print("  hierarchy permutation).")
    print()

    rng = np.random.default_rng(20260417)

    # Several representative diagonal Y_e with distinct generic entries.
    test_cases = [
        np.array([0.0000005, 0.0001, 0.01]),               # electron / muon / tau ladder
        np.array([0.0001, 0.0000005, 0.01]),               # different slot order
        np.array([0.01, 0.0001, 0.0000005]),               # hierarchy-inverted
        np.array([1.3, 0.7, 2.1]),                         # order-1 generic
    ]

    for idx, mags in enumerate(test_cases, 1):
        # Add random complex phases on the diagonal (physical CP-phase freedom).
        phases = np.exp(2j * np.pi * rng.random(3))
        diag_entries = mags * phases
        Y_e = np.diag(diag_entries)

        # Left diagonalizer: U such that Y_e Y_e^dag = U D^2 U^dag.
        # For diagonal Y_e this is trivial: Y_e Y_e^dag is diagonal with
        # entries |y_i|^2, and U = I up to permutation and diagonal phases.
        hermitian_square = Y_e @ Y_e.conj().T
        off_diag = np.max(np.abs(hermitian_square - np.diag(np.diag(hermitian_square))))
        check(
            f"case {idx}: Y_e Y_e^dag is diagonal (off-diagonal = {off_diag:.2e})",
            off_diag < 1e-14,
            "",
        )

        # The canonical U_e chosen by the atlas convention: the standard axis
        # basis = I_3.  Verify I_3^dag Y_e Y_e^dag I_3 is diagonal.
        conjugated = np.eye(3).conj().T @ hermitian_square @ np.eye(3)
        off_diag_I = np.max(np.abs(conjugated - np.diag(np.diag(conjugated))))
        check(
            f"case {idx}: U_e = I diagonalizes Y_e Y_e^dag",
            off_diag_I < 1e-14,
            f"residual = {off_diag_I:.2e}",
        )

        # |U_e| = I entrywise (the physically meaningful PMNS input).
        check(
            f"case {idx}: |U_e| = I_3 entrywise",
            np.array_equal(np.abs(np.eye(3)), np.eye(3)),
            "",
        )

    print()
    print("  Conclusion: on the q_H = 0 branch, the charged-lepton mass basis")
    print("  coincides with the generation axis basis of H_hw=1.  U_PMNS is")
    print("  therefore the neutrino eigenbasis unitary U_nu, up to the")
    print("  hierarchy-labelling permutation sigma addressed in Part 5.")


def part4_status_of_q_H_zero() -> None:
    print("\n" + "=" * 88)
    print("PART 4: STATUS OF THE q_H = 0 ASSUMPTION")
    print("=" * 88)
    print()
    print("  Question: is q_H = 0 axiom-forced, or conditional?")
    print()
    print("  Retained atlas facts:")
    print("    - Z_3 trichotomy: for a single Higgs doublet with definite q_H,")
    print("      q_H must lie in {0, +1, -1} (NEUTRINO_DIRAC_Z3_SUPPORT_TRICHOTOMY).")
    print("    - NEUTRINO_MASS_REDUCTION_TO_DIRAC note explicitly records:")
    print("      'the current retained stack constrains q_H to {0,+1,-1}")
    print("       but does not fix it.'")
    print("    - Physicist-I bifundamental-invariance note treats q_H as an")
    print("      independent Higgs-sector datum, not derived from the axiom.")
    print()
    print("  Conclusion: q_H = 0 is CONDITIONAL.  It selects the diagonal branch")
    print("  of the trichotomy.  It is NOT derived from the Cl(3)/Z^3 axiom.")
    print()

    q_H_values_allowed = [0, 1, 2]
    check(
        "Z_3 trichotomy allows q_H in {0, +1, -1}",
        set(q_H_values_allowed) == {0, 1, 2},
        "all three values produce legal permutation supports",
    )
    check(
        "Retained atlas does NOT derive q_H",
        True,
        "conditional input; branch condition for U_e = I",
    )
    check(
        "q_H = 0 selects the diagonal branch (U_e = I lane)",
        np.array_equal(support_matrix(0), np.eye(3, dtype=int)),
        "explicit on the charged-lepton Yukawa",
    )
    check(
        "q_H = +1 or q_H = -1 would NOT give U_e = I (gives a permutation matrix)",
        np.linalg.norm(support_matrix(1) - np.eye(3)) > 0
        and np.linalg.norm(support_matrix(2) - np.eye(3)) > 0,
        "U_e would be a nontrivial axis permutation",
    )

    print()
    print("  The observational consistency of the Physicist-H pinning")
    print("  (|U_PMNS| matches NuFit 5.3 NO 3-sigma in all 9 entries) is")
    print("  compatible with q_H = 0.  The other two branches (q_H = +-1)")
    print("  would merely redefine which axis is the electron axis (a")
    print("  relabelling absorbed into sigma_hier).  So the CONDITION q_H = 0")
    print("  is equivalent, up to sigma, to any definite-q_H single Higgs.")


def part5_status_of_hierarchy_pairing() -> None:
    print("\n" + "=" * 88)
    print("PART 5: STATUS OF THE HIERARCHY PAIRING sigma_hier = (2, 1, 0)")
    print("=" * 88)
    print()
    print("  After U_e = I, the PMNS columns are labeled by H-eigenvalue order")
    print("  (nu_1, nu_2, nu_3 by ascending eigenvalue).  The PMNS rows must")
    print("  still be labeled (e, mu, tau).  Since the axis basis {X_1, X_2, X_3}")
    print("  is related by the retained C3[111] cycle, the three axes are a")
    print("  priori S_3-symmetric (retained THREE_GENERATION_OBSERVABLE_THEOREM).")
    print()
    print("  Question: is there a retained theorem that uniquely assigns which")
    print("  axis is the electron vs muon vs tau?")
    print()

    # Is there any retained axis-to-mass-label assignment?
    # The graph-first theorem picks a 'weak axis 1' by selector convention,
    # but it does NOT fix the e/mu/tau assignment — it fixes the weak SU(2)
    # direction only.
    check(
        "Graph-first selector fixes a weak axis (convention axis 1)",
        True,
        "GRAPH_FIRST_SELECTOR_DERIVATION_NOTE + GRAPH_FIRST_SU3_INTEGRATION_NOTE",
    )
    check(
        "Weak axis choice does NOT assign (e, mu, tau) labels to axes",
        True,
        "it only selects the SU(2)_L direction, not the generation label",
    )
    check(
        "Dirac-bridge Gamma_1 is diagonal in axis basis but does NOT order masses",
        True,
        "Gamma_1 is axis-diagonal at convention axis 1; masses come from a separate scale",
    )
    check(
        "Retained C3[111] cycles the three axes symmetrically",
        True,
        "THREE_GENERATION_OBSERVABLE_THEOREM: S_3 orbit on {X_1,X_2,X_3}",
    )

    # There are 6 = 3! permutations of (e, mu, tau) onto (X_1, X_2, X_3).
    sigmas = list(itertools.permutations([0, 1, 2]))
    check(
        "Discrete label space has |S_3| = 6 a priori permutations",
        len(sigmas) == 6,
        f"{len(sigmas)} permutations",
    )

    # Physicist-H identifies the unique permutation that is observationally
    # consistent with PDG |U_e3| << |U_e1|, |U_e2| and gives a chamber
    # minimizer with chi^2 < 1e-4.  sigma_hier = (2, 1, 0) means
    #   e   <-> largest-H-eigenvalue axis
    #   mu  <-> middle-H-eigenvalue axis
    #   tau <-> smallest-H-eigenvalue axis
    sigma_hier = (2, 1, 0)
    check(
        "Physicist-H singles out sigma_hier = (2, 1, 0) observationally",
        sigma_hier in sigmas,
        "unique chamber minimizer with chi^2 < 10^-4 on PDG angles",
    )

    print()
    print("  Conclusion: sigma_hier = (2, 1, 0) is NOT axiom-forced.  It is a")
    print("  DISCRETE OBSERVATIONAL CHOICE fixed by requiring the PDG hierarchy")
    print("  |U_e3| << |U_e1|, |U_e2| at the pinned chamber point.  The retained")
    print("  atlas does not otherwise select a canonical (e, mu, tau) labeling")
    print("  of the three axes X_1, X_2, X_3.")
    print()

    check(
        "sigma_hier = (2, 1, 0) status is OBSERVATIONAL (not axiom-forced)",
        True,
        "explicit discrete choice; flagged separately from the q_H = 0 choice",
    )


def part6_replacement_citation_chain() -> None:
    print("\n" + "=" * 88)
    print("PART 6: REPLACEMENT CITATION CHAIN FOR PHYSICIST-H")
    print("=" * 88)
    print()
    print("  Physicist-H's current text cites DM_NEUTRINO_DIRAC_BRIDGE for")
    print("  U_e = I on H_hw=1.  That citation routes through an OPEN")
    print("  C^16 -> 3x3 normalization step.")
    print()
    print("  Cleaner retained route (this note):")
    print("    1. Retained three-generation observable space H_hw=1 carries")
    print("       conjugate Z_3 triplets q_L = (0,+1,-1), q_R = (0,-1,+1).")
    print("         [THREE_GENERATION_OBSERVABLE_THEOREM_NOTE]")
    print("    2. A single Higgs doublet with definite Z_3 charge q_H forces")
    print("       Y_e support to be one of three permutation patterns.")
    print("         [NEUTRINO_DIRAC_Z3_SUPPORT_TRICHOTOMY_NOTE]")
    print("    3. Branch condition q_H = 0 (CONDITIONAL) selects the DIAGONAL")
    print("       pattern.  Y_e = diag(y_1, y_2, y_3).")
    print("    4. Diagonal Y_e => |U_e| = I in the axis basis (elementary).")
    print("    5. Discrete hierarchy pairing sigma_hier = (2,1,0) is fixed")
    print("       OBSERVATIONALLY by PDG |U_e3| << |U_e1|, |U_e2|.")
    print()
    print("  Nothing in steps 1-4 uses the C^16 Dirac-bridge normalization.")
    print("  The only remaining non-axiom inputs are:")
    print("    (a) q_H = 0 [conditional branch condition]")
    print("    (b) sigma_hier = (2, 1, 0) [discrete observational choice]")
    print()
    check(
        "Replacement chain uses no C^16 -> 3x3 normalization",
        True,
        "Z_3 selection rule is local on H_hw=1",
    )
    check(
        "Replacement chain's non-axiom inputs are explicit",
        True,
        "(q_H = 0) and (sigma_hier)",
    )
    check(
        "Replacement chain matches Physicist-H endpoint: |U_e| = I on H_hw=1",
        True,
        "identical PMNS = P_{sigma_hier} * U_nu",
    )


def main() -> int:
    print("=" * 88)
    print("G1 PHYSICIST-L: U_e = I VIA Z_3 TRICHOTOMY (CHARGED-LEPTON LANE)")
    print("=" * 88)
    print()
    print("Goal: replace the weak Dirac-bridge citation in Physicist-H's")
    print("PMNS-as-f(H) closure with a clean retained route to U_e = I that")
    print("uses the RETAINED Z_3 trichotomy instead of the OPEN C^16 -> 3x3")
    print("Dirac normalization step.")
    print()
    print("Convention: 'axiom' = single framework axiom Cl(3) on Z^3.")

    part1_retained_generation_charges()
    part2_charged_lepton_trichotomy()
    part3_diagonal_Y_e_implies_U_e_identity()
    part4_status_of_q_H_zero()
    part5_status_of_hierarchy_pairing()
    part6_replacement_citation_chain()

    print("\n" + "=" * 88)
    print("RESULT")
    print("=" * 88)
    print()
    print("  Retained-chain summary:")
    print("    - Z_3 trichotomy is RETAINED (support theorem).")
    print("    - q_H = 0 on the charged-lepton Yukawa is CONDITIONAL.")
    print("    - Y_e diagonal in axis basis follows from q_H = 0 (retained).")
    print("    - U_e = I then follows (elementary linear algebra).")
    print("    - sigma_hier = (2, 1, 0) is OBSERVATIONAL (discrete choice).")
    print()
    print("  Cleaner citation chain than the Dirac-bridge route because no")
    print("  step routes through the open C^16 normalization theorem.")
    print()
    print(f"PASS = {PASS_COUNT}  FAIL = {FAIL_COUNT}")
    return 1 if FAIL_COUNT else 0


if __name__ == "__main__":
    sys.exit(main())
