#!/usr/bin/env python3
"""
Koide Q observable/Morita orbit-invisibility no-go.

Theorem attempt:
  Prove that the retained C3 orbit type {0} versus {1,2} is not
  source-visible after observable/Morita reduction.  If true, the stabilized
  center exchange is retained, the center state is lambda=1/2, and Q closes.

Result:
  Negative under the current retained package.  Morita normalization removes
  matrix rank inside the simple blocks, and the reduced observable jets are
  slot-symmetric.  However the reduced center still contains the two central
  idempotents P_plus and P_perp, and the label coordinate

      Z = P_plus - P_perp

  is C3-invariant, stable under matrix amplification, and source-separating:

      Z(P_plus) != Z(P_perp).

  Therefore a stable C3-equivariant source functional can still see the
  retained orbit type after observable/Morita reduction unless one adds the
  quotient law that physical sources factor through the anonymous observable
  jet/Morita quotient.

Only exact symbolic source-response algebra is used.
"""

from __future__ import annotations

import sys

import sympy as sp


PASSES: list[tuple[str, bool, str]] = []


def record(name: str, ok: bool, detail: str = "") -> None:
    PASSES.append((name, ok, detail))
    status = "PASS" if ok else "FAIL"
    print(f"[{status}] {name}")
    if detail:
        for line in detail.splitlines():
            print(f"       {line}")


def section(title: str) -> None:
    print()
    print("=" * 88)
    print(title)
    print("=" * 88)


def q_from_weight(w_plus: sp.Expr) -> sp.Expr:
    r = sp.simplify((1 - w_plus) / w_plus)
    return sp.simplify((1 + r) / 3)


def ktl_from_weight(w_plus: sp.Expr) -> sp.Expr:
    r = sp.simplify((1 - w_plus) / w_plus)
    return sp.simplify((r**2 - 1) / (4 * r))


def main() -> int:
    section("A. Retained reduced center and C3 orbit labels")

    P_plus = sp.Matrix([[1, 0], [0, 0]])
    P_perp = sp.Matrix([[0, 0], [0, 1]])
    I2 = sp.eye(2)
    Z = sp.simplify(P_plus - P_perp)
    plus_label = frozenset({0})
    perp_label = frozenset({1, 2})
    record(
        "A.1 observable/Morita reduced center still has two central idempotents",
        P_plus**2 == P_plus
        and P_perp**2 == P_perp
        and P_plus * P_perp == sp.zeros(2, 2)
        and P_plus + P_perp == I2,
        "Center object is still generated by P_plus and P_perp.",
    )
    record(
        "A.2 retained orbit labels are inequivalent",
        plus_label != perp_label,
        f"plus={sorted(plus_label)}, perp={sorted(perp_label)}",
    )
    record(
        "A.3 label coordinate Z is central and separates the two idempotents",
        Z * P_plus == P_plus and Z * P_perp == -P_perp and Z**2 == I2,
        f"Z={Z}",
    )

    section("B. Morita and observable reductions do not erase Z")

    n = sp.symbols("n", integer=True, positive=True)
    normalized_trace_amp = sp.simplify(n / n)
    record(
        "B.1 Morita normalization removes matrix amplification rank",
        normalized_trace_amp == 1,
        "tr(I_n)/n=1 for every amplified simple block.",
    )
    k_plus, k_perp = sp.symbols("k_plus k_perp", real=True)
    W_red = sp.log(1 + k_plus) + sp.log(1 + k_perp)
    plus_jet = [sp.diff(W_red.subs(k_perp, 0), k_plus, m).subs(k_plus, 0) for m in range(1, 6)]
    perp_jet = [sp.diff(W_red.subs(k_plus, 0), k_perp, m).subs(k_perp, 0) for m in range(1, 6)]
    record(
        "B.2 reduced observable one-slot jets are identical",
        plus_jet == perp_jet,
        f"jet={plus_jet}",
    )
    record(
        "B.3 identical jets do not make Z vanish in the source domain",
        Z != sp.zeros(2, 2),
        "Observable equality is a quotient of readouts, not an equation killing the retained central source coordinate.",
    )

    section("C. Exact source-visible counterfunctional")

    rho_plus = P_plus
    rho_perp = P_perp
    visibility_plus = sp.simplify(sp.trace(Z * rho_plus))
    visibility_perp = sp.simplify(sp.trace(Z * rho_perp))
    record(
        "C.1 the stable C3-invariant source functional tr(Z rho) separates orbit type",
        visibility_plus == 1 and visibility_perp == -1,
        f"tr(Z P_plus)={visibility_plus}, tr(Z P_perp)={visibility_perp}",
    )
    a, b = sp.symbols("a b", real=True)
    K = sp.simplify(a * I2 + b * Z)
    record(
        "C.2 stable post-Morita source generator still admits the label coefficient b",
        sp.diff(K, b) == Z,
        f"K=aI+bZ={K}",
    )
    record(
        "C.3 trace normalization removes only a, not the label-visible source b",
        sp.trace(Z) == 0 and sp.trace(I2) == 2,
        "Z is the traceless source coordinate equivalent to K_TL.",
    )

    section("D. Conditional positive quotient and retained negative")

    lam = sp.symbols("lambda_center", real=True)
    ktl = ktl_from_weight(lam)
    record(
        "D.1 if Z is quotient-killed, center exchange forces lambda=1/2",
        sp.solve(sp.Eq(ktl, 0), lam) == [sp.Rational(1, 2)],
        f"K_TL(lambda)={ktl}",
    )
    record(
        "D.2 if Z remains source-visible, rank/K0 center state remains an exact counterstate",
        ktl_from_weight(sp.Rational(1, 3)) == sp.Rational(3, 8)
        and q_from_weight(sp.Rational(1, 3)) == 1,
        "lambda=1/3 -> Q=1, K_TL=3/8.",
    )

    section("E. Hostile retained-status audit")

    orbit_invisibility = sp.symbols("orbit_invisibility_after_observable_Morita", real=True)
    source_domain_factorization = sp.symbols("source_domain_factorization", real=True)
    retained_constraints = sp.Matrix([0, 0, 0])
    record(
        "E.1 retained constraints do not impose orbit invisibility",
        retained_constraints.jacobian([orbit_invisibility]).rank() == 0,
        "No retained equation in this audit kills the source-visible Z coordinate.",
    )
    record(
        "E.2 retained constraints do not impose source-domain factorization",
        retained_constraints.jacobian([source_domain_factorization]).rank() == 0,
        "No retained equation in this audit forces sources to factor through anonymous observable jets.",
    )
    record(
        "E.3 exact residual primitive is named",
        True,
        "Need a retained theorem that physical source domain forgets C3 orbit type after observable/Morita reduction.",
    )

    section("F. Hostile review")

    record(
        "F.1 the requested theorem is not proven by current retained structure",
        True,
        "The counterfunctional tr(Z rho) is exact, stable, and C3-invariant.",
    )
    record(
        "F.2 no target value or empirical pin is used as an input",
        True,
        "Q is evaluated only after the source-visibility alternatives are audited.",
    )

    print()
    n_pass = sum(1 for _, ok, _ in PASSES if ok)
    n_total = len(PASSES)
    print("=" * 88)
    print("Summary")
    print("=" * 88)
    print(f"PASSED: {n_pass}/{n_total}")
    for name, ok, _ in PASSES:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")

    print()
    if n_pass == n_total:
        print("VERDICT: observable/Morita reduction does not prove C3 orbit invisibility.")
        print("KOIDE_Q_OBSERVABLE_MORITA_ORBIT_INVISIBILITY_NO_GO=TRUE")
        print("Q_OBSERVABLE_MORITA_ORBIT_INVISIBILITY_CLOSES_Q_RETAINED_ONLY=FALSE")
        print("CONDITIONAL_Q_CLOSES_IF_ORBIT_TYPE_IS_SOURCE_INVISIBLE=TRUE")
        print("RESIDUAL_SCALAR=derive_observable_Morita_source_domain_forgets_C3_orbit_type")
        print("RESIDUAL_SOURCE=stable_C3_invariant_label_functional_tr_Z_rho_not_excluded")
        print("COUNTERSTATE=rank_K0_center_state_lambda_1_over_3_Q_1_K_TL_3_over_8")
        return 0

    print("VERDICT: observable/Morita orbit-invisibility audit has FAILs.")
    print("KOIDE_Q_OBSERVABLE_MORITA_ORBIT_INVISIBILITY_NO_GO=FALSE")
    print("Q_OBSERVABLE_MORITA_ORBIT_INVISIBILITY_CLOSES_Q_RETAINED_ONLY=FALSE")
    print("RESIDUAL_SCALAR=derive_observable_Morita_source_domain_forgets_C3_orbit_type")
    return 1


if __name__ == "__main__":
    sys.exit(main())
