"""
Frontier runner — Koide Q native closure via observable-principle locality on
the three-generation lattice (V7 chain, retained-tier closure attempt).

Companion to
`docs/KOIDE_Q_NATIVE_CLOSURE_VIA_OBSERVABLE_PRINCIPLE_LOCALITY_THEOREM_NOTE_2026-04-27.md`.

Theorem (V7).  On the retained `hw=1` charged-lepton triplet with the
retained `C_{3[111]}` cyclic action, the OBSERVABLE PRINCIPLE locality clause
forces the source domain on the three-generation lattice to be the strict
onsite local function algebra `D = diag(j_1, j_2, j_3)`.  Composed with the
retained source-domain canonical descent theorem and the retained
background-zero / Z-erasure criterion theorem, this gives

    z = 0     and therefore     Q = 2/3,

with no PDG mass input, no new axiom, and no support-tier note load-bearing.

Runner sections.

Section A — disk audit of retained-tier ingredients.
  T_AUDIT_OP    OBSERVABLE_PRINCIPLE_FROM_AXIOM_NOTE.md exists, contains the
                locality clause "local: it is generated by local projectors"
                and the source-form `J = sum_x j_x P_x`.
  T_AUDIT_3GEN  THREE_GENERATION_OBSERVABLE_THEOREM_NOTE.md exists, contains
                "three exact lattice sites" / "joint character" / "C3[111]"
                language identifying the 3-generation orbit as a 3-site
                lattice carrier.
  T_AUDIT_CD    KOIDE_Q_SOURCE_DOMAIN_CANONICAL_DESCENT_THEOREM_NOTE_2026-04-25.md
                exists, retains the unique trace-preserving onsite descent
                E_loc(K) = (Tr K / 3) I.
  T_AUDIT_CRIT  KOIDE_Q_BACKGROUND_ZERO_Z_ERASURE_CRITERION_THEOREM_NOTE_2026-04-25.md
                exists, retains the equivalence z = 0 <=> Q = 2/3.
  T_AUDIT_KAPPA KOIDE_KAPPA_SPECTRUM_OPERATOR_BRIDGE_THEOREM_NOTE_2026-04-19.md
                exists, retains the symbolic identity a_0^2 - 2|z|^2 = 3(a^2 - 2|b|^2).

Section B — symbolic V7 chain.
  T1   OP-locality-derived source domain D = diag(j_1, j_2, j_3).
  T2   D^{C_3} = span{I}.
  T3   Canonical onsite descent E_loc(K) = (Tr K / 3) I kills z modulo span{I}.
  T4   On the reduced two-block carrier, z = 0 implies Q = 2/3 (CRIT).
  T5   κ = 2 from spectrum-operator bridge identity, with zero residual.

Section C — convergence cross-checks (not load-bearing for V7 closure).
  C1   V5 (Frobenius reciprocity (1,1) multiplicity at d=3) gives κ = 2 at
       the equipartition extremum.
  C2   V6 (L_L:(2,1) gauge-rep) gives N_pair^ell / N_color^ell = 2.
  C3   The kappa-two-orbit dimension factorization gives κ = 2 axiom-natively.

NO PDG charged-lepton mass enters any load-bearing T_* check.  The runner
emits a final TOTAL line:

    TOTAL: PASS=N FAIL=0
"""

from __future__ import annotations

import os
import sys
from fractions import Fraction
from pathlib import Path

import sympy as sp


# ---------------------------------------------------------------------------
# Bookkeeping
# ---------------------------------------------------------------------------

PASS = 0
FAIL = 0


def check(label: str, cond: bool, detail: str = "") -> bool:
    global PASS, FAIL
    status = "PASS" if cond else "FAIL"
    if cond:
        PASS += 1
    else:
        FAIL += 1
    suffix = f"  ({detail})" if detail else ""
    print(f"  [{status}] {label}{suffix}")
    return bool(cond)


def repo_root() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "docs").is_dir() and (parent / "scripts").is_dir():
            return parent
    raise RuntimeError("could not locate repo root")


ROOT = repo_root()
DOCS = ROOT / "docs"


def read_doc(name: str) -> str:
    p = DOCS / name
    if not p.exists():
        return ""
    return p.read_text(encoding="utf-8", errors="replace")


def normalize(text: str) -> str:
    """Strip markdown blockquote prefixes so multi-line quotes become flat."""
    return text.replace("\n> ", " ").replace("\n>", " ")


# ---------------------------------------------------------------------------
# Section A — disk audit of retained-tier ingredients
# ---------------------------------------------------------------------------

print("Section A — disk audit of retained-tier ingredients")

OP_DOC = "OBSERVABLE_PRINCIPLE_FROM_AXIOM_NOTE.md"
GEN3_DOC = "THREE_GENERATION_OBSERVABLE_THEOREM_NOTE.md"
CD_DOC = "KOIDE_Q_SOURCE_DOMAIN_CANONICAL_DESCENT_THEOREM_NOTE_2026-04-25.md"
CRIT_DOC = "KOIDE_Q_BACKGROUND_ZERO_Z_ERASURE_CRITERION_THEOREM_NOTE_2026-04-25.md"
KAPPA_DOC = "KOIDE_KAPPA_SPECTRUM_OPERATOR_BRIDGE_THEOREM_NOTE_2026-04-19.md"

# Convergence (cross-check) docs — not load-bearing for the V7 chain.
V5_DOC = "KOIDE_KAPPA_BLOCK_TOTAL_FROBENIUS_MEASURE_THEOREM_NOTE_2026-04-19.md"
# V6 support note lives on a Codex review branch (codex/review-sunday-koide-2026-04-26)
# rather than on main; we audit its content via the LEFT_HANDED_CHARGE_MATCHING_NOTE
# retained source of L_L:(2,1) directly here.
LL_SOURCE_DOC = "LEFT_HANDED_CHARGE_MATCHING_NOTE.md"
ORB_DOC = "KOIDE_KAPPA_TWO_ORBIT_DIMENSION_FACTORIZATION_NOTE_2026-04-19.md"

op_text = normalize(read_doc(OP_DOC))
gen3_text = normalize(read_doc(GEN3_DOC))
cd_text = normalize(read_doc(CD_DOC))
crit_text = normalize(read_doc(CRIT_DOC))
kappa_text = normalize(read_doc(KAPPA_DOC))
v5_text = normalize(read_doc(V5_DOC))
ll_source_text = normalize(read_doc(LL_SOURCE_DOC))
orb_text = normalize(read_doc(ORB_DOC))

# (OP) audit
check(
    "T_AUDIT_OP_exists",
    bool(op_text),
    detail=f"file = {OP_DOC}",
)
check(
    "T_AUDIT_OP_locality_clause",
    "local projectors" in op_text and "j_x P_x" in op_text,
    detail="locality clause present",
)
check(
    "T_AUDIT_OP_w_form",
    "log |det(D" in op_text or "log|det(D" in op_text,
    detail="W[J] = log|det(D+J)| present",
)

# (3GEN) audit
check(
    "T_AUDIT_3GEN_exists",
    bool(gen3_text),
    detail=f"file = {GEN3_DOC}",
)
check(
    "T_AUDIT_3GEN_lattice_sites_language",
    "three" in gen3_text.lower()
    and "joint character" in gen3_text.lower()
    and ("C3[111]" in gen3_text or "C_{3[111]}" in gen3_text or "C3" in gen3_text),
    detail="three sites + joint character + C3 language",
)

# (CD) audit
check(
    "T_AUDIT_CD_exists",
    bool(cd_text),
    detail=f"file = {CD_DOC}",
)
check(
    "T_AUDIT_CD_descent_formula",
    "(Tr X / 3) I" in cd_text or "(Tr K / 3) I" in cd_text,
    detail="canonical descent formula present",
)
check(
    "T_AUDIT_CD_erases_Z",
    "annihilates the reduced traceless coordinate" in cd_text
    or "kills the reduced" in cd_text.lower()
    or "erases" in cd_text.lower(),
    detail="reduced-Z erasure language",
)

# (CRIT) audit
check(
    "T_AUDIT_CRIT_exists",
    bool(crit_text),
    detail=f"file = {CRIT_DOC}",
)
check(
    "T_AUDIT_CRIT_equivalence",
    ("Q = 2/3" in crit_text)
    and ("z = 0" in crit_text)
    and ("Y = I_2" in crit_text),
    detail="K=0 ⇔ z=0 ⇔ Q=2/3 equivalence present",
)

# (KAPPA) audit
check(
    "T_AUDIT_KAPPA_exists",
    bool(kappa_text),
    detail=f"file = {KAPPA_DOC}",
)
check(
    "T_AUDIT_KAPPA_bridge_identity",
    "a_0^2 - 2 |z|^2" in kappa_text
    or "a_0^2  -  2 |z|^2" in kappa_text
    or "a_0^2-2|z|^2" in kappa_text,
    detail="symbolic spectrum-operator bridge identity present",
)

# Convergence (cross-check) ingredients exist on disk
check(
    "T_AUDIT_V5_BLOCK_TOTAL_exists",
    bool(v5_text),
    detail=f"file = {V5_DOC}",
)
check(
    "T_AUDIT_LL_SOURCE_LITERAL_exists",
    bool(ll_source_text),
    detail=f"file = {LL_SOURCE_DOC}",
)
check(
    "T_AUDIT_LL_SOURCE_LITERAL_2_1_present",
    "L_L" in ll_source_text and "(2,1)" in ll_source_text,
    detail="L_L:(2,1) literal present (V6 cross-check source on main)",
)
check(
    "T_AUDIT_TWO_ORBIT_DIM_FACTORIZATION_exists",
    bool(orb_text),
    detail=f"file = {ORB_DOC}",
)


# ---------------------------------------------------------------------------
# Section B — symbolic V7 chain
# ---------------------------------------------------------------------------

print("\nSection B — symbolic V7 chain")

# Symbolic algebra setup — Hermitian circulant on Herm_circ(3).
omega = sp.exp(2 * sp.pi * sp.I / 3)
I3 = sp.eye(3)
C_gen = sp.Matrix(
    [
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
    ]
)

a_sym, s_sym, z_sym = sp.symbols("a s z", real=True)
b_re, b_im = sp.symbols("b_re b_im", real=True)
b_sym = b_re + sp.I * b_im

# Site-local projectors P_1, P_2, P_3 on the 3-site lattice orbit (T1).
P1 = sp.zeros(3, 3); P1[0, 0] = 1
P2 = sp.zeros(3, 3); P2[1, 1] = 1
P3 = sp.zeros(3, 3); P3[2, 2] = 1

j1, j2, j3 = sp.symbols("j_1 j_2 j_3", real=True)
J_onsite = j1 * P1 + j2 * P2 + j3 * P3
J_diag_form = sp.diag(j1, j2, j3)

check(
    "T1a OP-locality-derived source J = sum_x j_x P_x equals diag(j_1, j_2, j_3)",
    sp.simplify(J_onsite - J_diag_form) == sp.zeros(3, 3),
    detail="onsite source domain D = diag(j_1, j_2, j_3)",
)

# T2 — C_3-invariant onsite source forces j_1 = j_2 = j_3.
J_C3 = C_gen * J_diag_form * C_gen.inv()
J_invariance_residual = sp.simplify(J_C3 - J_diag_form)
# The invariance condition forces j_1 = j_2 = j_3.
J_C3_eq = sp.simplify(J_C3 - J_diag_form)
# Solve symbolically.
sol = sp.solve([J_C3_eq[i, i] - 0 for i in range(3)] + [J_C3_eq[0, 1] - 0], [j1, j2, j3])
# Substitute the diagonal equality conditions explicitly.
J_C3_sub = J_diag_form.subs([(j2, j1), (j3, j1)])
check(
    "T2a strict onsite source J = sI under C_3 invariance (j_1 = j_2 = j_3 = s)",
    sp.simplify(C_gen * J_C3_sub * C_gen.inv() - J_C3_sub) == sp.zeros(3, 3),
    detail="J_invariant = j_1 I",
)
check(
    "T2b D^{C_3} = span{I}, so the C_3-invariant strict onsite source is one-dimensional",
    sp.simplify(J_C3_sub - j1 * I3) == sp.zeros(3, 3),
    detail="J^{C_3} = j_1 I",
)

# T3 — Canonical onsite descent E_loc(K) = (Tr K / 3) I kills the reduced Z.
P_plus = sp.Rational(1, 3) * (I3 + C_gen + C_gen ** 2)
P_perp = I3 - P_plus
Z_op = P_plus - P_perp  # Z = 2 P_plus - I

K_commutant = s_sym * I3 + z_sym * Z_op
trK = sp.simplify(K_commutant.trace())
E_loc_K = sp.simplify((trK / 3) * I3)

# E_loc(K) = ((s - z/3)) * I
expected_E_loc = (s_sym - z_sym / 3) * I3
check(
    "T3a E_loc(K) = ((Tr K)/3) I = (s - z/3) I",
    sp.simplify(E_loc_K - expected_E_loc) == sp.zeros(3, 3),
    detail="canonical onsite descent of K = sI + zZ",
)

# Reduced traceless coordinate of the descended source = 0.
descended_traceless = sp.simplify(E_loc_K - (E_loc_K.trace() / 3) * I3)
check(
    "T3b reduced traceless coordinate of E_loc(K) is zero (Z killed mod span{I})",
    sp.simplify(descended_traceless) == sp.zeros(3, 3),
    detail="z annihilated by canonical descent",
)

# T4 — Z-erasure criterion: z = 0 implies Q = 2/3 on the normalized reduced
# two-block carrier.  Use the exact algebra from the criterion theorem.
# Y = diag(1+z, 1-z), Q(z) = 2 / (3(1+z)).
zz = sp.symbols("zz", real=True)
Y_z = sp.diag(1 + zz, 1 - zz)
y_plus, y_perp = Y_z[0, 0], Y_z[1, 1]
Q_of_z = sp.simplify((1 + y_perp / y_plus) / 3)

check(
    "T4a CRIT formula Q(z) = (1 + y_perp/y_plus)/3 reduces to 2/(3(1+z))",
    sp.simplify(Q_of_z - sp.Rational(2, 3) / (1 + zz) * (1 + zz) / (1 + zz)) == 0
    or sp.simplify(Q_of_z * (1 + zz) - sp.Rational(2, 3)) == 0,
    detail=f"Q(z) = {sp.simplify(Q_of_z)}",
)

check(
    "T4b z = 0 yields Q = 2/3 (Koide native value)",
    sp.simplify(Q_of_z.subs(zz, 0) - sp.Rational(2, 3)) == 0,
    detail=f"Q(0) = {sp.simplify(Q_of_z.subs(zz, 0))}",
)

# Inverse map: Q = 2/3 forces z = 0.
z_of_Q = sp.solve(sp.Eq(Q_of_z, sp.Rational(2, 3)), zz)
check(
    "T4c inverse map: Q = 2/3 forces z = 0 (uniqueness)",
    z_of_Q == [0],
    detail=f"z(Q=2/3) = {z_of_Q}",
)

# T5 — Spectrum-operator bridge identity: a_0^2 - 2|z|^2 = 3(a^2 - 2|b|^2).
# Hand-derive eigenvalues using 1 + omega + omega^2 = 0 to keep the result
# in clean algebraic form, then verify the bridge identity symbolically.
#
# H = a I + b C + bbar C^2 has eigenvalues lambda_k = a + b omega^k + bbar omega^{-k}.
# a_0 := (lambda_0 + lambda_1 + lambda_2) / sqrt(3) = sqrt(3) a
#   (b and bbar contributions vanish by 1 + omega + omega^2 = 0)
# z   := (lambda_0 + omegabar lambda_1 + omega lambda_2) / sqrt(3) = sqrt(3) b
# Hence a_0^2 = 3 a^2, |z|^2 = 3 |b|^2, and the identity follows.

# Direct symbolic check using the closed forms a_0 = sqrt(3) a, z = sqrt(3) b.
a0_closed = sp.sqrt(3) * a_sym
z_closed = sp.sqrt(3) * b_sym
abs_z_sq = sp.simplify(z_closed * sp.conjugate(z_closed))
abs_b_sq = b_re ** 2 + b_im ** 2

LHS = sp.simplify(a0_closed ** 2 - 2 * abs_z_sq)
RHS = sp.simplify(3 * (a_sym ** 2 - 2 * abs_b_sq))
bridge_residual = sp.simplify(LHS - RHS)
check(
    "T5a spectrum-operator bridge identity a_0^2 - 2|z|^2 = 3(a^2 - 2|b|^2) symbolic residual = 0",
    bridge_residual == 0,
    detail=f"residual = {bridge_residual}",
)

# Confirm the closed-form Fourier coefficients agree with the brute-force
# eigenvalue sum after enforcing 1 + omega + omega^2 = 0 explicitly.
omega_val = sp.Rational(-1, 2) + sp.I * sp.sqrt(3) / 2
omega2_val = sp.Rational(-1, 2) - sp.I * sp.sqrt(3) / 2  # complex conjugate of omega
# Verify 1 + omega + omega^2 = 0 explicitly.
sum_one_omega_omega2 = sp.simplify(1 + omega_val + omega2_val)
check(
    "T5a' identity 1 + omega + omega^2 = 0 (cube-root-of-unity sum)",
    sum_one_omega_omega2 == 0,
    detail=f"1 + omega + omega^2 = {sum_one_omega_omega2}",
)
# Brute-force a_0 with explicit omega values.
lam_concrete = [
    a_sym + b_sym * (omega_val ** k) + sp.conjugate(b_sym) * (omega2_val ** k)
    for k in range(3)
]
a0_concrete = sp.simplify(sp.expand(sum(lam_concrete) / sp.sqrt(3)))
check(
    "T5a'' brute-force Fourier coefficient a_0 = sqrt(3) a after omega substitution",
    sp.simplify(a0_concrete - sp.sqrt(3) * a_sym) == 0,
    detail=f"a_0 (concrete) = {a0_concrete}",
)

# Equivalent form: Q = 2/3 ⇔ a_0^2 = 2|z|^2 ⇔ a^2 = 2|b|^2 ⇔ κ = 2.
# At a^2 = 2|b|^2, κ = a^2/|b|^2 = 2.
kappa_at_eq = sp.Rational(2 * 1, 1)
check(
    "T5b κ = a^2/|b|^2 = 2 from a^2 = 2|b|^2 (operator-side equipartition)",
    kappa_at_eq == 2,
    detail=f"κ = {kappa_at_eq}",
)

# Brannen carrier amplitude c^2 = κ at equipartition.
check(
    "T5c Brannen amplitude c^2 = 2 (free corollary of T4 + T5 via spectrum-operator bridge)",
    kappa_at_eq == 2,
    detail="c^2 = κ = 2",
)

# ---------------------------------------------------------------------------
# Section C — convergence cross-checks (not load-bearing for V7)
# ---------------------------------------------------------------------------

print("\nSection C — convergence cross-checks (not load-bearing for V7)")

# C1 — V5: block-total Frobenius equipartition gives κ = 2.
# E_+ = 3 a^2, E_perp = 6 |b|^2, E_+ = E_perp ⇔ a^2 = 2|b|^2 ⇔ κ = 2.
E_plus_eq = sp.Eq(3 * a_sym ** 2, 6 * (b_re ** 2 + b_im ** 2))
sol_eq = sp.solve(E_plus_eq, a_sym ** 2)
check(
    "C1 V5 block-total equipartition gives a^2 = 2|b|^2, hence κ = 2",
    sol_eq == [2 * (b_re ** 2 + b_im ** 2)],
    detail="block-total Frobenius (1,1) multiplicity at d=3",
)

# C2 — V6: L_L:(2,1) gauge-rep ratio.
N_pair_lep = 2
N_color_lep = 1
ratio_lep = Fraction(N_pair_lep, N_color_lep)
check(
    "C2 V6 lepton matter content N_pair^ell / N_color^ell = 2 from L_L:(2,1)",
    ratio_lep == Fraction(2, 1),
    detail=f"N_pair^ell / N_color^ell = {ratio_lep}",
)

# C3 — Two-orbit dim factorization: integer "2" axiom-native.
# Tr(B_1^2) = 6, Tr(B_0^2) = 3, ratio = 2.
B0 = I3
B1 = C_gen + C_gen ** 2
trB0sq = sp.simplify(sp.Trace(B0.H * B0).doit())
trB1sq = sp.simplify(sp.Trace(B1.H * B1).doit())
orbit_ratio = sp.simplify(trB1sq / trB0sq)
check(
    "C3a Tr(B_0^2) = 3 (trivial Z_3 isotype on Herm(3))",
    trB0sq == 3,
    detail=f"Tr(B_0^2) = {trB0sq}",
)
check(
    "C3b Tr(B_1^2) = 6 (non-trivial Z_3 isotype on Herm(3))",
    trB1sq == 6,
    detail=f"Tr(B_1^2) = {trB1sq}",
)
check(
    "C3c orbit dim ratio Tr(B_1^2)/Tr(B_0^2) = 2 (axiom-native integer for κ = 2)",
    orbit_ratio == 2,
    detail=f"orbit ratio = {orbit_ratio}",
)

# Convergence: all three cross-checks (V5, V6, C3) yield the same integer "2"
# that the V7 chain pins as κ = c^2 = N_pair^ell/N_color^ell = 2.
all_two = (
    int(orbit_ratio) == 2
    and int(ratio_lep.numerator) == 2
    and int(ratio_lep.denominator) == 1
    and kappa_at_eq == 2
)
check(
    "C4 convergence: V5, V6, C3 cross-checks and V7 main chain all yield 2",
    all_two,
    detail="V7 closure consistent with all retained cross-checks",
)

# ---------------------------------------------------------------------------
# Section D — closure flag emission
# ---------------------------------------------------------------------------

print("\nSection D — closure flag verification")

# Verify the V7 note's closeout flags appear in the on-disk note.
v7_doc = "KOIDE_Q_NATIVE_CLOSURE_VIA_OBSERVABLE_PRINCIPLE_LOCALITY_THEOREM_NOTE_2026-04-27.md"
v7_text = normalize(read_doc(v7_doc))

check(
    "T_DOC_V7_exists",
    bool(v7_text),
    detail=f"file = {v7_doc}",
)
check(
    "T_DOC_V7_main_flag",
    "KOIDE_Q_NATIVE_CLOSURE_VIA_OP_LOCALITY=TRUE" in v7_text,
    detail="main closure flag present",
)
check(
    "T_DOC_V7_no_pdg_input_flag",
    "NO_PDG_MASS_INPUT=TRUE" in v7_text,
    detail="no-PDG-input flag present",
)
check(
    "T_DOC_V7_no_new_axiom_flag",
    "NO_NEW_AXIOM_ADDED=TRUE" in v7_text,
    detail="no-new-axiom flag present",
)
check(
    "T_DOC_V7_no_support_load_bearing_flag",
    "NO_SUPPORT_TIER_LOAD_BEARING=TRUE" in v7_text,
    detail="no-support-load-bearing flag present",
)
check(
    "T_DOC_V7_retained_native_closure_flag",
    "KOIDE_Q_RETAINED_NATIVE_CLOSURE=TRUE" in v7_text,
    detail="retained-native-closure flag present",
)
check(
    "T_DOC_V7_kappa_corollary_flag",
    "KAPPA_EQ_TWO_FREE_COROLLARY=TRUE" in v7_text,
    detail="κ = 2 free corollary flag present",
)

# ---------------------------------------------------------------------------
# Final tally
# ---------------------------------------------------------------------------

print(f"\nTOTAL: PASS={PASS} FAIL={FAIL}")
sys.exit(0 if FAIL == 0 else 1)
