#!/usr/bin/env python3
"""
Koide Q local C3 polynomial source-exhaustion no-go.

Theorem attempt:
  Exhaust retained local C3-equivariant polynomial source grammars generated by
  the singlet/doublet idempotents and prove that they are pure trace on the
  normalized second-order carrier, hence K_TL = 0.

Result:
  The exhaustion is exact but negative.  The local C3 idempotent algebra is
  two-dimensional.  With Z = P_plus - P_perp, every polynomial source reduces
  to

      F(Z) = A_even I + A_odd Z.

  Trace normalization absorbs A_even.  The only physical source coefficient is
  A_odd, exactly the already named K_TL source.  No local polynomial identity
  in the retained C3 algebra forces A_odd = 0.  Imposing A_odd = 0 is the
  missing source law; imposing Z -> -Z would be block exchange, already known
  not to be retained on the rank-1/rank-2 carrier.
"""

from __future__ import annotations

import sys

import sympy as sp


PASSES: list[tuple[str, bool, str]] = []


def record(name: str, ok: bool, detail: str = "") -> None:
    PASSES.append((name, ok, detail))
    status = "PASS" if ok else "FAIL"
    print(f"[{status}] {name}")
    if detail:
        for line in detail.split("\n"):
            print(f"       {line}")


def section(title: str) -> None:
    print()
    print("=" * 88)
    print(title)
    print("=" * 88)


def split_even_odd(coeffs: list[sp.Expr]) -> tuple[sp.Expr, sp.Expr]:
    even = sp.simplify(sum(coeffs[n] for n in range(0, len(coeffs), 2)))
    odd = sp.simplify(sum(coeffs[n] for n in range(1, len(coeffs), 2)))
    return even, odd


def q_from_ktl(k: sp.Expr) -> sp.Expr:
    y = sp.symbols("y", positive=True, real=True)
    ktl_y = sp.simplify((1 - y) / (y * (2 - y)))
    sol = [root for root in sp.solve(sp.Eq(ktl_y, k), y) if root.is_real is not False]
    # Use the closed form branch with y in (0,2) for sampled rational k.
    if k == 0:
        yk = sp.Integer(1)
    else:
        yk = [root for root in sol if 0 < float(root.evalf()) < 2][0]
    r = sp.simplify((2 - yk) / yk)
    return sp.simplify((1 + r) / 3)


def main() -> int:
    section("A. Retained local C3 idempotent algebra")

    C = sp.Matrix([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
    I3 = sp.eye(3)
    J = sp.ones(3, 3)
    P_plus = J / 3
    P_perp = I3 - P_plus
    Z = sp.simplify(P_plus - P_perp)

    record(
        "A.1 P_plus and P_perp are retained complementary C3-central idempotents",
        sp.simplify(P_plus**2 - P_plus) == sp.zeros(3, 3)
        and sp.simplify(P_perp**2 - P_perp) == sp.zeros(3, 3)
        and sp.simplify(P_plus * P_perp) == sp.zeros(3, 3)
        and sp.simplify(C * P_plus - P_plus * C) == sp.zeros(3, 3)
        and sp.simplify(C * P_perp - P_perp * C) == sp.zeros(3, 3),
        "The local source algebra generated by the isotype projectors is commutative.",
    )
    record(
        "A.2 Z=P_plus-P_perp is an involution, so every polynomial collapses to I and Z",
        sp.simplify(Z**2 - I3) == sp.zeros(3, 3),
        "Z^2=I.",
    )

    section("B. Exhaust arbitrary finite local polynomial source")

    degree = 6
    coeffs = list(sp.symbols(f"a0:{degree + 1}", real=True))
    F = sp.zeros(3, 3)
    for n, coeff in enumerate(coeffs):
        F += coeff * (Z**n)
    F = sp.simplify(F)
    A_even, A_odd = split_even_odd(coeffs)
    collapsed = sp.simplify(A_even * I3 + A_odd * Z)

    record(
        "B.1 an arbitrary degree-6 retained local polynomial source collapses exactly",
        sp.simplify(F - collapsed) == sp.zeros(3, 3),
        f"F(Z)=A_even I + A_odd Z, A_even={A_even}, A_odd={A_odd}",
    )
    record(
        "B.2 quotient by trace leaves exactly one physical source coefficient",
        sp.simplify(collapsed - A_even * I3 - A_odd * Z) == sp.zeros(3, 3)
        and A_odd.has(*coeffs),
        "A_even is trace/multiplier data; A_odd is the singlet-vs-doublet source.",
    )

    section("C. No polynomial identity forces the odd coefficient to vanish")

    off_coeffs = {coeff: 0 for coeff in coeffs}
    off_coeffs[coeffs[1]] = sp.Rational(1, 5)
    F_off = sp.simplify(F.subs(off_coeffs))
    A_odd_off = sp.simplify(A_odd.subs(off_coeffs))
    record(
        "C.1 a retained local polynomial source can have nonzero A_odd",
        A_odd_off == sp.Rational(1, 5) and sp.simplify(F_off - sp.Rational(1, 5) * Z) == sp.zeros(3, 3),
        "Example: F(Z)=Z/5.",
    )

    pure_trace_coeffs = {coeff: 0 for coeff in coeffs}
    pure_trace_coeffs[coeffs[0]] = 7
    pure_trace_coeffs[coeffs[2]] = -2
    A_odd_trace = sp.simplify(A_odd.subs(pure_trace_coeffs))
    record(
        "C.2 pure-trace polynomial sources are a codimension-one coefficient condition",
        A_odd_trace == 0,
        "They require the odd coefficient sum A_odd to vanish.",
    )

    section("D. Stability/convexity of scalar polynomial laws still leaves arbitrary selected value")

    k, c = sp.symbols("K_TL c", real=True)
    Vc = (k - c) ** 2
    record(
        "D.1 positive convex polynomial scalar laws can select any K_TL=c",
        sp.diff(Vc, k, 2) == 2 and sp.solve(sp.Eq(sp.diff(Vc, k), 0), k) == [c],
        "V_c=(K_TL-c)^2 is retained-polynomial compatible once c is supplied.",
    )
    sample_ks = [sp.Rational(-1, 5), sp.Rational(0), sp.Rational(1, 5)]
    sample_q = {value: q_from_ktl(value) for value in sample_ks}
    record(
        "D.2 the same stable grammar realizes off-Koide and Koide leaves",
        sample_q[sp.Rational(0)] == sp.Rational(2, 3)
        and sample_q[sp.Rational(-1, 5)] != sp.Rational(2, 3)
        and sample_q[sp.Rational(1, 5)] != sp.Rational(2, 3),
        f"K_TL -> Q samples = {sample_q}",
    )

    section("E. What extra principle would be needed")

    record(
        "E.1 imposing Z -> -Z would kill A_odd, but that is block exchange",
        True,
        "The retained rank-1 singlet and rank-2 real doublet cannot be exchanged on the physical carrier.",
    )
    record(
        "E.2 local C3 polynomial source exhaustion reduces Q to one explicit coefficient law",
        True,
        "Closure requires A_odd=0 from a new physical source theorem, not from the local C3 polynomial grammar.",
    )

    section("Summary")

    n_pass = sum(1 for _, ok, _ in PASSES if ok)
    n_total = len(PASSES)
    print(f"PASSED: {n_pass}/{n_total}")
    for name, ok, _ in PASSES:
        status = "PASS" if ok else "FAIL"
        print(f"  [{status}] {name}")

    print()
    if n_pass == n_total:
        print("VERDICT: retained local C3 polynomial source exhaustion does not close Q.")
        print("The source algebra exhausts to trace plus one odd quotient coefficient;")
        print("that coefficient is exactly the missing K_TL source.")
        print()
        print("KOIDE_Q_LOCAL_C3_POLYNOMIAL_SOURCE_EXHAUSTION_NO_GO=TRUE")
        print("Q_LOCAL_C3_POLYNOMIAL_SOURCE_EXHAUSTION_CLOSES_Q=FALSE")
        print("RESIDUAL_COEFFICIENT=A_odd_equiv_K_TL")
        return 0

    print("VERDICT: local C3 polynomial source exhaustion audit has FAILs.")
    print()
    print("KOIDE_Q_LOCAL_C3_POLYNOMIAL_SOURCE_EXHAUSTION_NO_GO=FALSE")
    print("Q_LOCAL_C3_POLYNOMIAL_SOURCE_EXHAUSTION_CLOSES_Q=FALSE")
    print("RESIDUAL_COEFFICIENT=A_odd_equiv_K_TL")
    return 1


if __name__ == "__main__":
    sys.exit(main())

