#!/usr/bin/env python3
"""
Theorem-grade admissibility restriction for exact quark endpoint denominators.

Status:
  exact denominator-admissibility theorem / no-go on the reduced quark
  endpoint atoms

Safe claim:
  On the current quark endpoint lane, the denominator problem should not be
  widened into another generic expression search.

  The live exact atoms already force a much smaller multiplicative grammar:
    - after stripping the fixed projector `sqrt(5/6)` down to its support-side
      denominator slot,
    - and excluding bridge ratios that still carry numerator contamination,
    - every exact support denominator lives on the half-integer six/seven
      lattice generated by `{6, 7, sqrt(6), sqrt(7)}`.

  This runner proves the exact endpoint:
    - smallest structurally admissible generator class:
      `{6, 7, sqrt(6), sqrt(7)}`
    - datum-inclusive realized admissible class on the current endpoint atoms:
      `{6, 7, 42, sqrt(6), sqrt(7), sqrt(42)}`
    - `sqrt(7)` is not unique on the full admissible class
    - `sqrt(7)` is unique only in the pure seven-only irrational generator
      subclass.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction


PASS_COUNT = 0
FAIL_COUNT = 0

F = Fraction


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS_COUNT, FAIL_COUNT
    if condition:
        PASS_COUNT += 1
        status = "PASS"
    else:
        FAIL_COUNT += 1
        status = "FAIL"
    line = f"  [{status}] {name}"
    if detail:
        line += f"  ({detail})"
    print(line)


@dataclass(frozen=True)
class EndpointAtom:
    label: str
    exp5: Fraction
    exp6: Fraction
    exp7: Fraction
    role: str

    def support_projection(self) -> tuple[Fraction, Fraction]:
        return (self.exp6, self.exp7)

    def support_denominator_pair(self) -> tuple[Fraction, Fraction] | None:
        if self.exp6 <= 0 and self.exp7 <= 0:
            return (-self.exp6, -self.exp7)
        return None


ATOMS = (
    EndpointAtom("delta_A1", F(0), F(-1), F(-1), "support-datum"),
    EndpointAtom("6/7", F(0), F(1), F(-1), "bridge-ratio"),
    EndpointAtom("1/6", F(0), F(-1), F(0), "support-reciprocal"),
    EndpointAtom("1/sqrt(42)", F(0), F(-1, 2), F(-1, 2), "support-reciprocal"),
    EndpointAtom("1/sqrt(7)", F(0), F(0), F(-1, 2), "support-reciprocal"),
    EndpointAtom("sqrt(6/7)", F(0), F(1, 2), F(-1, 2), "bridge-ratio"),
    EndpointAtom("sqrt(5/6)", F(1, 2), F(-1, 2), F(0), "projector-prefactor"),
)


def pair_label(pair: tuple[Fraction, Fraction]) -> str:
    mapping = {
        (F(1), F(0)): "6",
        (F(0), F(1)): "7",
        (F(1), F(1)): "42",
        (F(1, 2), F(0)): "sqrt(6)",
        (F(0), F(1, 2)): "sqrt(7)",
        (F(1, 2), F(1, 2)): "sqrt(42)",
    }
    return mapping[pair]


def combine_pairs(
    left: tuple[Fraction, Fraction],
    right: tuple[Fraction, Fraction],
    op: str,
) -> tuple[Fraction, Fraction]:
    if op == "mul":
        return (left[0] + right[0], left[1] + right[1])
    if op == "div":
        return (left[0] - right[0], left[1] - right[1])
    raise ValueError(op)


def support_projector_pair() -> tuple[Fraction, Fraction]:
    projector = next(atom for atom in ATOMS if atom.label == "sqrt(5/6)")
    return (-projector.exp6, -projector.exp7)


def direct_pure_reciprocal_pairs() -> dict[str, tuple[Fraction, Fraction]]:
    direct: dict[str, tuple[Fraction, Fraction]] = {}
    for atom in ATOMS:
        if atom.label == "sqrt(5/6)":
            # Strip the fixed projector `sqrt(5)` numerator. On the support side
            # this contributes only the `1/sqrt(6)` denominator slot.
            direct["sqrt(5/6)|support-proj"] = support_projector_pair()
            continue
        pair = atom.support_denominator_pair()
        if pair is not None:
            direct[atom.label] = pair
    return direct


def part1_atom_reduction() -> None:
    print("\n" + "=" * 72)
    print("PART 1: Exact Endpoint Atom Reduction")
    print("=" * 72)

    print("\n  support-side exponent basis:")
    print("    value = 5^(a5/2) 6^(a6/2) 7^(a7/2)")
    print("    admissible denominator slots come from negative support exponents")

    print("\n  live endpoint atoms:")
    for atom in ATOMS:
        e5, e6, e7 = atom.exp5, atom.exp6, atom.exp7
        print(
            f"    {atom.label:20s} "
            f"(a5, a6, a7) = ({e5}, {e6}, {e7})  "
            f"[{atom.role}]"
        )

    direct = direct_pure_reciprocal_pairs()
    print("\n  direct pure reciprocal support slots:")
    for label, pair in direct.items():
        print(f"    {label:20s} -> 1/{pair_label(pair)}")

    bridge_atoms = [atom for atom in ATOMS if atom.role == "bridge-ratio"]
    print("\n  bridge atoms with numerator contamination:")
    for atom in bridge_atoms:
        e6, e7 = atom.support_projection()
        print(f"    {atom.label:20s} -> 6^{e6} 7^{e7}")

    check(
        "Every live endpoint atom lies on the half-integer six/seven support lattice",
        all(atom.exp6.denominator in {1, 2} and atom.exp7.denominator in {1, 2} for atom in ATOMS),
        "all support exponents have denominator <= 2",
    )
    check(
        "Bridge ratios 6/7 and sqrt(6/7) do not define pure reciprocal denominators",
        all(atom.support_denominator_pair() is None for atom in bridge_atoms),
        "both carry positive six numerator content",
    )
    check(
        "Stripping the fixed projector sqrt(5/6) leaves exactly the sqrt(6) denominator slot",
        direct["sqrt(5/6)|support-proj"] == (F(1, 2), F(0)),
        f"pair = {direct['sqrt(5/6)|support-proj']}",
    )


def part2_minimal_class() -> tuple[set[str], set[str]]:
    print("\n" + "=" * 72)
    print("PART 2: Minimal Admissible Denominator Class")
    print("=" * 72)

    direct = direct_pure_reciprocal_pairs()

    # The missing rational seven-slot is forced exactly by support centering:
    #   delta_A1 / (1/6) = 1/7
    # and equivalently
    #   (6/7) * (1/6) = 1/7.
    rational_seven_pair = combine_pairs(
        next(pair for label, pair in direct.items() if label == "delta_A1"),
        next(pair for label, pair in direct.items() if label == "1/6"),
        "div",
    )

    generator_pairs = {
        direct["1/6"],
        rational_seven_pair,
        direct["sqrt(5/6)|support-proj"],
        direct["1/sqrt(7)"],
    }
    generator_class = {pair_label(pair) for pair in generator_pairs}

    realized_pairs = set(direct.values()) | {rational_seven_pair}
    realized_class = {pair_label(pair) for pair in realized_pairs}

    print("\n  exact rational seven witness:")
    print("    delta_A1 / (1/6) = 1/7")
    print("    (6/7) * (1/6)    = 1/7")
    print(f"    recovered pair   = {rational_seven_pair} -> 1/{pair_label(rational_seven_pair)}")

    print("\n  smallest structurally admissible generator class:")
    print(f"    {sorted(generator_class)}")
    print("\n  datum-inclusive realized admissible class:")
    print(f"    {sorted(realized_class)}")

    check(
        "The exact rational seven slot is recovered from the live support atoms",
        rational_seven_pair == (F(0), F(1)),
        f"pair = {rational_seven_pair}",
    )
    check(
        "The smallest generator class is exactly {6, 7, sqrt(6), sqrt(7)}",
        generator_class == {"6", "7", "sqrt(6)", "sqrt(7)"},
        f"class = {sorted(generator_class)}",
    )
    check(
        "The datum-inclusive realized class is exactly {6, 7, 42, sqrt(6), sqrt(7), sqrt(42)}",
        realized_class == {"6", "7", "42", "sqrt(6)", "sqrt(7)", "sqrt(42)"},
        f"class = {sorted(realized_class)}",
    )
    check(
        "delta_A1 and 1/sqrt(42) are composite support denominators over the generator class",
        next(pair for label, pair in direct.items() if label == "delta_A1") == (F(1), F(1))
        and next(pair for label, pair in direct.items() if label == "1/sqrt(42)") == (F(1, 2), F(1, 2)),
        "42 = 6*7 and sqrt(42) = sqrt(6)*sqrt(7)",
    )

    return generator_class, realized_class


def part3_uniqueness(generator_class: set[str], realized_class: set[str]) -> None:
    print("\n" + "=" * 72)
    print("PART 3: sqrt(7) Uniqueness / No-Go")
    print("=" * 72)

    seven_bearing_realized = {"7", "42", "sqrt(7)", "sqrt(42)"}
    irrational_seven_bearing_realized = {"sqrt(7)", "sqrt(42)"}
    pure_irrational_generator = {"sqrt(7)"}

    print("\n  seven-bearing realized denominators:")
    print(f"    {sorted(seven_bearing_realized)}")
    print("\n  irrational seven-bearing realized denominators:")
    print(f"    {sorted(irrational_seven_bearing_realized)}")
    print("\n  pure seven-only irrational generator subclass:")
    print(f"    {sorted(pure_irrational_generator)}")

    # User-supplied simplification: sqrt(42/5) = sqrt(7) / sqrt(5/6).
    # In exponent language, multiplying by the fixed projector sqrt(5/6)
    # strips the 5-sector and leaves exactly the sqrt(7) denominator slot.
    simplified_pair = (F(0), F(1, 2))
    print("\n  projector-stripped simplification:")
    print("    sqrt(42/5) * sqrt(5/6) = sqrt(7)")

    print("\n  additive two-step string:")
    print("    2 + sqrt(5/6)")
    print("    is outside the admissible multiplicative denominator grammar")

    check(
        "sqrt(7) is not unique on the full realized admissible class",
        "sqrt(7)" in realized_class and len(seven_bearing_realized) > 1,
        f"seven-bearing class = {sorted(seven_bearing_realized)}",
    )
    check(
        "sqrt(7) is not unique even among irrational seven-bearing realized denominators",
        irrational_seven_bearing_realized != {"sqrt(7)"},
        f"irrational seven-bearing class = {sorted(irrational_seven_bearing_realized)}",
    )
    check(
        "sqrt(7) is the unique pure seven-only irrational generator",
        pure_irrational_generator == {"sqrt(7)"} and "sqrt(7)" in generator_class,
        f"generator class = {sorted(generator_class)}",
    )
    check(
        "The simplified sqrt(42/5) denominator reduces to the sqrt(7) slot after restoring the fixed projector prefactor",
        simplified_pair == (F(0), F(1, 2)),
        f"pair = {simplified_pair} -> 1/{pair_label(simplified_pair)}",
    )


def main() -> None:
    part1_atom_reduction()
    generator_class, realized_class = part2_minimal_class()
    part3_uniqueness(generator_class, realized_class)

    print("\n" + "=" * 72)
    print(f"SUMMARY: PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    print("=" * 72)


if __name__ == "__main__":
    main()
