#!/usr/bin/env python3
"""
Intersection of A_S^{S_3} and the Hw-Projector Algebra

Classical math applied:
  - Linear algebra of subspace intersection: for two linear subspaces
    U, V of W,  dim(U ∩ V)  =  dim U + dim V − dim(U + V)  (Grassmann
    formula; textbook).
  - Hadamard / Z_2^3 character theory (Frobenius 1896) for analysis
    of Hadamard-diagonal operators.
  - Hamming-weight diagonality for hw-graded operators (standard
    spectral-projector framework).
  - Only scalars are both Hadamard-diagonal (on all |ψ_s⟩ with the
    same eigenvalue) AND hw-diagonal (on all |α⟩ with the same
    eigenvalue); this reduces to the observation that any operator
    with both diagonal structures simultaneously is a scalar multiple
    of I (standard spectral argument).

Framework object:
  Two distinct 4-dim abelian S_3-invariant subalgebras of the 20-dim
  commutant End(C^8)^{S_3}:
    · A_S^{S_3}  =  span{e_0, e_1, e_2, e_3}  (Batch 4): the
      S_3-invariant elementary-symmetric subalgebra of the cube-shift
      polynomial algebra, Hadamard-diagonal.
    · P  =  span{Π_0, Π_1, Π_2, Π_3}  (Batch 7 T1): the Hamming-
      weight projector algebra, hw-diagonal.

Theorem (intersection theorem):
  (1) A_S^{S_3} ∩ P  =  span_C{I}  (1-dimensional), spanned by the
      identity I = e_0 = Π_0 + Π_1 + Π_2 + Π_3.
  (2) A_S^{S_3} + P is a 4 + 4 − 1 = 7-dimensional subspace of the
      20-dim End(C^8)^{S_3}, strictly smaller.
  (3) A_S^{S_3} + P is NOT a subalgebra of End(C^8)^{S_3}: the
      product e_1 · Π_0 lies in neither A_S^{S_3} nor P.
      The subalgebra generated by A_S^{S_3} ∪ P has strictly larger
      dimension.

Proof method:
  (1) A_S^{S_3} is Hadamard-diagonal (Batch 4 Part 2).  P is
      hw-diagonal (Batch 7 T1 Part 5).  An operator that is both
      Hadamard-diagonal and hw-diagonal must be a scalar: it has
      the same eigenvalue on every Hadamard vector |ψ_s⟩ and on
      every computational basis vector |α⟩, and any two Hadamard
      vectors span the same |α⟩ components with different signs,
      forcing eigenvalue equality.  Hence the intersection is
      span{I}.
  (2) Grassmann formula.
  (3) Explicit construction: e_1 · Π_0 is computed and checked to
      lie outside both subalgebras.

Reusability:
  - Clarifies the two natural 4-dim "structural" subalgebras of the
    S_3-invariant commutant: one built from cube-shifts, one built
    from hw-projectors.  They are independent except for the common
    identity.
  - Used when classifying how an S_3-invariant operator decomposes
    against these two structural axes (cube-shift symmetric vs
    hw-graded).
"""

from __future__ import annotations

import itertools
import numpy as np

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS_COUNT, FAIL_COUNT
    if condition:
        PASS_COUNT += 1
        status = "PASS"
    else:
        FAIL_COUNT += 1
        status = "FAIL"
    line = f"  [{status}] {name}"
    if detail:
        line += f"  ({detail})"
    print(line)


# ---------------------------------------------------------------------------
# Operators
# ---------------------------------------------------------------------------

def cube_shift(mu: int) -> np.ndarray:
    sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
    I2 = np.eye(2, dtype=complex)
    factors = [I2, I2, I2]
    factors[mu] = sigma_x
    return np.kron(np.kron(factors[0], factors[1]), factors[2])


def elementary_symmetric() -> list:
    """Return (e_0, e_1, e_2, e_3) as 8x8 matrices."""
    S = [cube_shift(mu) for mu in range(3)]
    e0 = np.eye(8, dtype=complex)
    e1 = S[0] + S[1] + S[2]
    e2 = S[0] @ S[1] + S[0] @ S[2] + S[1] @ S[2]
    e3 = S[0] @ S[1] @ S[2]
    return [e0, e1, e2, e3]


def hw_projector(k: int) -> np.ndarray:
    P = np.zeros((8, 8), dtype=complex)
    for alpha in itertools.product([0, 1], repeat=3):
        if sum(alpha) == k:
            idx = alpha[0] * 4 + alpha[1] * 2 + alpha[2]
            P[idx, idx] = 1.0
    return P


def real_rank_of_matrices(mats: list) -> int:
    stacked = np.stack([M.reshape(-1) for M in mats], axis=1)
    real_stacked = np.vstack([stacked.real, stacked.imag])
    return np.linalg.matrix_rank(real_stacked, tol=1e-10)


def complex_rank_of_matrices(mats: list) -> int:
    stacked = np.stack([M.reshape(-1) for M in mats], axis=1)
    return np.linalg.matrix_rank(stacked, tol=1e-10)


# ---------------------------------------------------------------------------
# Part 1: Recover dim A_S^{S_3} = 4 and dim P = 4
# ---------------------------------------------------------------------------

def part1_subalgebra_dims() -> tuple:
    print("\n" + "=" * 72)
    print("PART 1: dim A_S^{S_3} = 4 (Batch 4)  and  dim P = 4 (Batch 7 T1)")
    print("=" * 72)

    e = elementary_symmetric()
    P = [hw_projector(k) for k in range(4)]

    dim_AS3 = complex_rank_of_matrices(e)
    dim_P = complex_rank_of_matrices(P)
    print(f"  dim A_S^{{S_3}} = {dim_AS3}")
    print(f"  dim P         = {dim_P}")

    check("dim A_S^{S_3} = 4", dim_AS3 == 4)
    check("dim P = 4", dim_P == 4)

    return e, P


# ---------------------------------------------------------------------------
# Part 2: dim (A_S^{S_3} + P) = 7  via Grassmann formula
# ---------------------------------------------------------------------------

def part2_sum_dimension(e: list, P: list) -> int:
    print("\n" + "=" * 72)
    print("PART 2: dim (A_S^{S_3} + P) = 7 by direct rank")
    print("=" * 72)

    combined = e + P
    dim_sum = complex_rank_of_matrices(combined)
    print(f"  dim (A_S^{{S_3}} + P) = {dim_sum}")
    check("dim (A_S^{S_3} + P) = 7", dim_sum == 7)

    # Grassmann: dim(U ∩ V) = dim U + dim V − dim(U + V)
    dim_intersection = 4 + 4 - dim_sum
    print(f"  Grassmann: dim (A_S^{{S_3}} ∩ P) = 4 + 4 − {dim_sum} = {dim_intersection}")
    check("dim (A_S^{S_3} ∩ P) = 1 via Grassmann",
          dim_intersection == 1)

    return dim_sum


# ---------------------------------------------------------------------------
# Part 3: Explicit generator of the intersection is I
# ---------------------------------------------------------------------------

def part3_intersection_is_identity(e: list, P: list) -> None:
    print("\n" + "=" * 72)
    print("PART 3: The intersection is span{I}")
    print("=" * 72)

    # I = e_0 (by construction in A_S^{S_3})
    I_from_e = e[0]
    check("e_0 = I", np.allclose(I_from_e, np.eye(8)))

    # I = Π_0 + Π_1 + Π_2 + Π_3 (by construction in P)
    I_from_P = sum(P)
    check("Π_0 + Π_1 + Π_2 + Π_3 = I", np.allclose(I_from_P, np.eye(8)))

    # Confirm no other non-trivial operator is in both
    # (An operator M is in both iff it's Hadamard-diagonal (from A_S^{S_3})
    # AND hw-diagonal (from P).  Scalars are both; any non-scalar?)
    # Cross check: try e_1 (Hadamard-diagonal).  Is e_1 hw-diagonal?
    # No: e_1 is the sum of cube-shifts, maps |α⟩ to Σ_μ |α ⊕ e_μ⟩,
    # hw-off-diagonal.  So e_1 ∉ P.
    # Similarly Π_1 (hw-diagonal).  Is Π_1 Hadamard-diagonal?
    # No: Π_1 has rank 3 but its eigenvalues on Hadamard vectors are
    # not constant.

    # Spectrum check: compute Π_1 in Hadamard basis
    H8 = np.zeros((8, 8), dtype=complex)
    for i, s in enumerate(itertools.product([+1, -1], repeat=3)):
        for j, alpha in enumerate(itertools.product([0, 1], repeat=3)):
            idx_s = i
            idx_a = alpha[0] * 4 + alpha[1] * 2 + alpha[2]
            phase = (s[0] ** alpha[0]) * (s[1] ** alpha[1]) * (s[2] ** alpha[2])
            H8[idx_a, idx_s] = phase / np.sqrt(8)

    Pi1_in_Hadamard = H8.conj().T @ P[1] @ H8
    off_diagonal_mass = np.linalg.norm(Pi1_in_Hadamard - np.diag(np.diag(Pi1_in_Hadamard)))
    check("Π_1 is NOT Hadamard-diagonal",
          off_diagonal_mass > 1e-6,
          f"off-diagonal Frobenius = {off_diagonal_mass:.4f}")

    # Similarly e_1 in computational basis
    e_1_off = np.linalg.norm(e[1] - np.diag(np.diag(e[1])))
    check("e_1 is NOT hw-diagonal (hence not in P)",
          e_1_off > 1e-6,
          f"off-diagonal Frobenius = {e_1_off:.4f}")


# ---------------------------------------------------------------------------
# Part 4: A_S^{S_3} + P is NOT a subalgebra
# ---------------------------------------------------------------------------

def part4_not_subalgebra(e: list, P: list) -> None:
    print("\n" + "=" * 72)
    print("PART 4: A_S^{S_3} + P is NOT a subalgebra of End(C^8)^{S_3}")
    print("=" * 72)

    # Consider M := e_1 · Π_0.
    # e_1 maps hw=0 to hw=1 (Batch 7 T1 Part 5).
    # Π_0 projects onto hw=0.
    # So M : hw=0 → hw=1, zero elsewhere.  In particular:
    #   · M is hw-OFF-diagonal, hence M ∉ P (which is hw-diagonal).
    #   · Is M Hadamard-diagonal?  On the Hadamard basis, e_1 is diagonal
    #     (Batch 4) but Π_0 is NOT Hadamard-diagonal (Part 3); so their
    #     product is generically not Hadamard-diagonal either.
    M = e[1] @ P[0]

    # Does M lie in A_S^{S_3} + P?  Compute rank of (basis ∪ {M}).
    combined = e + P + [M]
    rank_with_M = complex_rank_of_matrices(combined)
    rank_without_M = complex_rank_of_matrices(e + P)
    print(f"  rank(A_S^{{S_3}} + P)       = {rank_without_M}")
    print(f"  rank(A_S^{{S_3}} + P + {{M}}) = {rank_with_M}")
    check("e_1 · Π_0 ∉ A_S^{S_3} + P  (rank increases)",
          rank_with_M > rank_without_M)

    # Sanity: M is still S_3-invariant (since both factors are)
    tau = np.zeros((8, 8), dtype=complex)
    for a in itertools.product([0, 1], repeat=3):
        src = a[0] * 4 + a[1] * 2 + a[2]
        new_a = (a[1], a[0], a[2])
        dst = new_a[0] * 4 + new_a[1] * 2 + new_a[2]
        tau[dst, src] = 1.0
    check("M = e_1 · Π_0 is S_3-invariant (commutes with τ)",
          np.allclose(tau @ M, M @ tau))


# ---------------------------------------------------------------------------
# Part 5: Theorem statement
# ---------------------------------------------------------------------------

def part5_theorem() -> None:
    print("\n" + "=" * 72)
    print("PART 5: Intersection Theorem (statement)")
    print("=" * 72)

    print("""
  THEOREM (Intersection of A_S^{S_3} and P).  Let A_S^{S_3} be the
  S_3-invariant cube-shift elementary-symmetric subalgebra of
  End(C^8) (Batch 4, dim 4), and let P be the Hamming-weight
  projector algebra (Batch 7 T1, dim 4).  Both are 4-dimensional
  abelian S_3-invariant subalgebras of the 20-dim End(C^8)^{S_3}.
  Then:

  (1) A_S^{S_3} ∩ P  =  span_C{I}  (1-dimensional).

  (2) dim (A_S^{S_3} + P) = 4 + 4 − 1 = 7  (Grassmann formula).

  (3) A_S^{S_3} + P is NOT a subalgebra: for example, e_1 · Π_0 is
      S_3-invariant but lies outside A_S^{S_3} + P.

  CLASSICAL RESULTS USED.
  - Grassmann's formula dim(U ∩ V) = dim U + dim V − dim(U + V) for
    linear subspaces (textbook linear algebra).
  - Z_2^3 Hadamard character theory (Frobenius 1896) for the
    Hadamard-diagonal structure of A_S^{S_3}.
  - Spectral-projector framework for the hw-diagonal structure of P.
  - Standard fact that an operator diagonal in two "sufficiently
    different" orthonormal bases must be a scalar multiple of I
    (consequence of the spectral theorem + linear independence).

  FRAMEWORK-SPECIFIC STEP.
  - Identification of A_S^{S_3} (Hadamard-diagonal) and P
    (hw-diagonal) as two 4-dim S_3-invariant abelian subalgebras
    of End(C^8)^{S_3}, built from the cube-shift generators and
    the Hamming-weight grading respectively.

  PROOF.  (1) A_S^{S_3} is Hadamard-diagonal (Batch 4 Part 2) and P
  is hw-diagonal (Batch 7 T1).  An operator in both subalgebras is
  simultaneously Hadamard-diagonal and hw-diagonal.  Since the
  Hadamard and computational (hw) bases span C^8 together with
  different support patterns, the only simultaneous eigenvalue
  function is constant, giving a scalar multiple of I.  (2) follows
  from (1) and Grassmann.  (3) is verified by an explicit computation
  showing the product e_1 · Π_0 raises the rank of the span.  QED.

  REUSABILITY.
  - Makes precise how "cube-shift-symmetric" (via A_S^{S_3}) and
    "hw-graded" (via P) are complementary structural viewpoints on
    the S_3-invariant commutant.
  - Guides decomposition of any S_3-invariant operator: a 4-dim
    A_S^{S_3} part (symmetric in cube-shifts), a 4-dim P part
    (hw-graded diagonal), and a 13-dim "mixing" remainder.
""")


def main() -> int:
    print("=" * 72)
    print("  Intersection of A_S^{S_3} and the Hw-Projector Algebra")
    print("=" * 72)

    e, P = part1_subalgebra_dims()
    part2_sum_dimension(e, P)
    part3_intersection_is_identity(e, P)
    part4_not_subalgebra(e, P)
    part5_theorem()

    print("\n" + "=" * 72)
    print(f"  TOTAL: PASS={PASS_COUNT}, FAIL={FAIL_COUNT}")
    print("=" * 72)

    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
