#!/usr/bin/env python3
"""Orbit-channel structure of the sewing-shell anisotropic remainder.

Exact content:
  1. For the current exact source families on codex/review-active, the
     anisotropic shell remainder delta_sigma = sigma_R - sigma_rad has
     orbit-sum support only on four cubic orbit channels in the sewing band:
         (3,2,2), (3,3,0), (4,1,0), (4,1,1)
  2. The shellwise cancellation is exact:
         S_(3,2,2) + S_(4,1,0) = 0
         S_(3,3,0) + S_(4,1,1) = 0
  3. After normalizing by the anchor channel S_(3,3,0), the orbit-sum vector
     is identical across the current exact source families.

Bounded content:
  4. The shell-mean exterior field generated by delta_sigma is universal up to
     the same scalar anchor amplitude, and its shell-mean magnitude stays below
     8.1% of the radial-shell contribution outside the sewing band.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib.machinery import SourceFileLoader

import numpy as np


@dataclass
class Check:
    name: str
    ok: bool
    detail: str
    status: str


CHECKS: list[Check] = []


def record(name: str, ok: bool, detail: str, status: str = "EXACT") -> None:
    CHECKS.append(Check(name=name, ok=ok, detail=detail, status=status))
    tag = "PASS" if ok else "FAIL"
    print(f"[{status}] {tag}: {name}")
    if detail:
        print(f"    {detail}")


same_source = SourceFileLoader(
    "same_source_metric",
    "/private/tmp/physics-review-active/scripts/frontier_same_source_metric_ansatz_scan.py",
).load_module()
coarse = SourceFileLoader(
    "coarse_grained",
    "/private/tmp/physics-review-active/scripts/frontier_coarse_grained_exterior_law.py",
).load_module()
sew = SourceFileLoader(
    "sewing_shell",
    "/private/tmp/physics-review-active/scripts/frontier_sewing_shell_source.py",
).load_module()
rad = SourceFileLoader(
    "radial_shell",
    "/private/tmp/physics-review-active/scripts/frontier_radial_shell_matching_law.py",
).load_module()


ACTIVE_ORBITS = [
    (3, 2, 2),
    (3, 3, 0),
    (4, 1, 0),
    (4, 1, 1),
]
ANCHOR_ORBIT = (3, 3, 0)


def orbit_key(i: int, j: int, k: int, size: int) -> tuple[int, int, int]:
    center = (size - 1) // 2
    return tuple(sorted([abs(i - center), abs(j - center), abs(k - center)], reverse=True))


def shell_mean_rows(field: np.ndarray, cutoff: float = 5.0) -> list[tuple[float, float]]:
    size = field.shape[0]
    center = (size - 1) / 2.0
    groups: dict[int, list[tuple[int, int, int]]] = {}
    for i in range(size):
        for j in range(size):
            for k in range(size):
                d2 = int((i - center) ** 2 + (j - center) ** 2 + (k - center) ** 2)
                groups.setdefault(d2, []).append((i, j, k))
    rows = []
    for d2 in sorted(groups):
        radius = float(np.sqrt(d2))
        if radius <= cutoff + 1e-12:
            continue
        vals = np.array([field[p] for p in groups[d2]], dtype=float)
        rows.append((radius, float(np.mean(vals))))
    return rows


def family_data(phi_grid: np.ndarray, shell_radius: float = 4.0) -> dict[str, object]:
    sigma = sew.full_neg_laplacian(sew.exterior_projector(phi_grid, shell_radius))
    sigma_rad = rad.radial_average_shell(sigma)
    delta_sigma = sigma - sigma_rad
    phi_rad = rad.solve_from_source(sigma_rad)
    phi_aniso = rad.solve_from_source(delta_sigma)

    size = delta_sigma.shape[0]
    orbit_sums: dict[tuple[int, int, int], float] = {}
    orbit_avgs: dict[tuple[int, int, int], float] = {}
    orbit_pts: dict[tuple[int, int, int], list[tuple[int, int, int]]] = {}
    for i in range(size):
        for j in range(size):
            for k in range(size):
                key = orbit_key(i, j, k, size)
                orbit_pts.setdefault(key, []).append((i, j, k))
                orbit_sums.setdefault(key, 0.0)
                orbit_sums[key] += float(delta_sigma[i, j, k])
    for key, pts in orbit_pts.items():
        vals = [delta_sigma[p] for p in pts]
        orbit_avgs[key] = float(np.mean(vals))

    active = {k: v for k, v in orbit_sums.items() if abs(v) > 1e-12}
    anchor = active[ANCHOR_ORBIT]
    normalized = {k: v / anchor for k, v in active.items()}

    mean_rows_aniso = shell_mean_rows(phi_aniso)
    mean_rows_rad = shell_mean_rows(phi_rad)
    normalized_means = [(r, m / anchor) for (r, m) in mean_rows_aniso]
    max_ratio = max(
        abs(ma / mr)
        for (_, mr), (_, ma) in zip(mean_rows_rad, mean_rows_aniso)
        if abs(mr) > 1e-12
    )

    return {
        "active": active,
        "normalized": normalized,
        "mean_rows_aniso": mean_rows_aniso,
        "normalized_means": normalized_means,
        "max_ratio": max_ratio,
        "orbit_avgs": orbit_avgs,
    }


def max_norm_diff(a: dict[tuple[int, int, int], float], b: dict[tuple[int, int, int], float]) -> float:
    keys = sorted(set(a) | set(b))
    return max(abs(a.get(k, 0.0) - b.get(k, 0.0)) for k in keys)


def max_shell_mean_diff(
    rows_a: list[tuple[float, float]], rows_b: list[tuple[float, float]]
) -> float:
    return max(abs(ma - mb) for (_, ma), (_, mb) in zip(rows_a, rows_b))


def format_orbit_vector(data: dict[tuple[int, int, int], float]) -> str:
    parts = [f"{key}:{data[key]:+.12f}" for key in ACTIVE_ORBITS]
    return ", ".join(parts)


def main() -> None:
    print("Orbit-channel shell remainder for strong-field gravity")
    print("=" * 72)

    oh = family_data(same_source.build_best_phi_grid())
    fr = family_data(coarse.build_finite_rank_phi_grid())

    print("Active orbit-sum channels (local O_h):")
    print("  " + format_orbit_vector(oh["active"]))
    print("Active orbit-sum channels (finite-rank):")
    print("  " + format_orbit_vector(fr["active"]))
    print("Normalized by S_(3,3,0) (local O_h):")
    print("  " + format_orbit_vector(oh["normalized"]))
    print("Normalized by S_(3,3,0) (finite-rank):")
    print("  " + format_orbit_vector(fr["normalized"]))
    print(
        f"max shell-mean anisotropic/radial ratio: "
        f"O_h={oh['max_ratio']:.6f}, finite-rank={fr['max_ratio']:.6f}"
    )

    for label, data in [("local O_h", oh), ("finite-rank", fr)]:
        active_keys = sorted(data["active"])
        record(
            f"{label} anisotropic shell remainder has orbit-sum support only on the four cubic channels",
            active_keys == ACTIVE_ORBITS,
            f"active orbit channels={active_keys}",
        )
        record(
            f"{label} anisotropic orbit sums cancel shellwise on r^2 = 17 and r^2 = 18",
            abs(data["active"][(3, 2, 2)] + data["active"][(4, 1, 0)]) < 1e-12
            and abs(data["active"][(3, 3, 0)] + data["active"][(4, 1, 1)]) < 1e-12,
            (
                f"S322+S410={data['active'][(3, 2, 2)] + data['active'][(4, 1, 0)]:.3e}, "
                f"S330+S411={data['active'][(3, 3, 0)] + data['active'][(4, 1, 1)]:.3e}"
            ),
        )

    norm_diff = max_norm_diff(oh["normalized"], fr["normalized"])
    mean_diff = max_shell_mean_diff(oh["normalized_means"], fr["normalized_means"])

    record(
        "the normalized anisotropic orbit-sum vector is identical across the two exact source families",
        norm_diff < 1e-12,
        f"max normalized orbit-sum difference={norm_diff:.3e}",
    )
    record(
        "the normalized shell-mean exterior response of the anisotropic remainder is identical across the two exact source families",
        mean_diff < 1e-12,
        f"max normalized shell-mean difference={mean_diff:.3e}",
    )
    record(
        "the anisotropic shell-mean exterior correction stays below 8.1% of the radial-shell contribution outside the sewing band",
        max(oh["max_ratio"], fr["max_ratio"]) < 0.081,
        f"max ratio={max(oh['max_ratio'], fr['max_ratio']):.6f}",
        status="BOUNDED",
    )

    print("\n" + "=" * 72)
    print("SUMMARY")
    print("=" * 72)
    n_pass = sum(c.ok for c in CHECKS)
    n_fail = sum(not c.ok for c in CHECKS)
    print(f"PASS={n_pass} FAIL={n_fail} TOTAL={len(CHECKS)}")
    if n_fail == 0:
        print("All checks passed.")
    else:
        print("Some checks failed.")


if __name__ == "__main__":
    main()
