#!/usr/bin/env python3
"""
Hierarchy Z4 spinor-selector theorem.

This script upgrades the uniform-orbit selector to a deeper framework
candidate: the minimal resolved APBC temporal orbit should realize the
fermionic Z4 phase cycle coming from spinor double-cover structure.

On the APBC circle the temporal phases are:
    z_n = exp(i (2n+1) pi / Lt)

The unique even Lt for which this APBC orbit is exactly one Z4 spinor orbit
    z0 * {1, i, -1, -i}
is Lt = 4.

This makes Lt = 4 the unique minimal time-resolved spinor orbit, and therefore
the strongest exact selector candidate for the hierarchy normalization.
"""

from __future__ import annotations

import cmath
import math
import sys

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = ""):
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    print(f"  [{status}] {name}")
    if detail:
        print(f"         {detail}")


def apbc_phases(Lt: int):
    return [cmath.exp(1j * (2 * n + 1) * math.pi / Lt) for n in range(Lt)]


def canonicalize(phases):
    vals = []
    for z in phases:
        a = round(z.real, 12)
        b = round(z.imag, 12)
        vals.append((a, b))
    return sorted(set(vals))


def is_z4_spinor_orbit(Lt: int) -> bool:
    phases = apbc_phases(Lt)
    if len(phases) != 4:
        return False
    base = phases[0]
    target = [base * (1j) ** k for k in range(4)]
    return canonicalize(phases) == canonicalize(target)


def sin2_values(Lt: int):
    return [round(math.sin((2 * n + 1) * math.pi / Lt) ** 2, 15) for n in range(Lt)]


def a_lt(Lt: int) -> float:
    return (1.0 / (2.0 * Lt)) * sum(
        1.0 / (3.0 + math.sin((2 * n + 1) * math.pi / Lt) ** 2) for n in range(Lt)
    )


def c_lt(Lt: int) -> float:
    return ((1.0 / 8.0) / a_lt(Lt)) ** 0.25


def c_obs() -> float:
    return 246.22 / 253.4


def test_unique_z4_orbit():
    print("\n" + "=" * 78)
    print("PART 1: UNIQUE MINIMAL Z4 SPINOR ORBIT")
    print("=" * 78)

    z4_solutions = []
    for Lt in range(2, 18, 2):
        phases = canonicalize(apbc_phases(Lt))
        print(f"  Lt={Lt:2d}: phases={phases[:min(4,len(phases))]}{'...' if len(phases)>4 else ''}")
        if is_z4_spinor_orbit(Lt):
            z4_solutions.append(Lt)

    check(
        "the only even Lt <= 16 whose APBC orbit is exactly one Z4 spinor orbit is Lt = 4",
        z4_solutions == [4],
        f"Z4-orbit solutions = {z4_solutions}",
    )


def test_z4_properties_at_lt4():
    print("\n" + "=" * 78)
    print("PART 2: Lt=4 REALIZES THE FULL SPINOR Z4 CYCLE")
    print("=" * 78)

    phases = apbc_phases(4)
    canon = canonicalize(phases)
    base = phases[0]
    z4 = canonicalize([base * (1j) ** k for k in range(4)])
    conj = canonicalize([z.conjugate() for z in phases])
    neg = canonicalize([-z for z in phases])

    print(f"  Lt=4 APBC orbit  = {canon}")
    print(f"  generated Z4 set = {z4}")

    check(
        "Lt=4 APBC orbit equals one Z4 orbit generated by multiplication by i",
        canon == z4,
    )
    check(
        "Lt=4 orbit is closed under complex conjugation (time reversal)",
        canon == conj,
    )
    check(
        "Lt=4 orbit is closed under z -> -z (fermionic sign / half-cycle shift)",
        canon == neg,
    )


def test_lt2_is_z2_not_z4():
    print("\n" + "=" * 78)
    print("PART 3: Lt=2 IS THE UNRESOLVED Z2 ENDPOINT")
    print("=" * 78)

    phases2 = canonicalize(apbc_phases(2))
    print(f"  Lt=2 APBC orbit = {phases2}")

    check(
        "Lt=2 has only two APBC phases, so it does not realize the full Z4 spinor cycle",
        len(phases2) == 2 and not is_z4_spinor_orbit(2),
        f"number of phases = {len(phases2)}",
    )
    check(
        "Lt=2 still has uniform temporal weight but no resolved quarter-turn structure",
        max(sin2_values(2)) == min(sin2_values(2)) == 1.0,
        f"sin^2 values = {sin2_values(2)}",
    )


def test_selector_prediction():
    print("\n" + "=" * 78)
    print("PART 4: EXACT HIERARCHY CORRECTION FROM THE Z4 SELECTOR")
    print("=" * 78)

    c4 = c_lt(4)
    c4_exact = (7.0 / 8.0) ** 0.25
    v4 = 253.4 * c4
    cobs = c_obs()

    print(f"  C_4 exact = {c4_exact:.12f}")
    print(f"  C_obs     = {cobs:.12f}")
    print(f"  v_4       = {v4:.12f} GeV")

    check(
        "Z4 selector reproduces the exact Lt=4 correction (7/8)^(1/4)",
        abs(c4 - c4_exact) < 1e-15,
        f"absolute error = {abs(c4 - c4_exact):.2e}",
    )
    check(
        "Z4-selected prediction is within 0.5% of measured v",
        abs(v4 - 246.22) / 246.22 < 0.005,
        f"relative error = {abs(v4 - 246.22) / 246.22:.4%}",
    )


def main():
    print("Hierarchy Z4 spinor-selector theorem")
    print("=" * 78)
    test_unique_z4_orbit()
    test_z4_properties_at_lt4()
    test_lt2_is_z2_not_z4()
    test_selector_prediction()
    print("\n" + "=" * 78)
    print(f"SCORECARD: {PASS_COUNT} pass, {FAIL_COUNT} fail out of {PASS_COUNT + FAIL_COUNT}")
    print("=" * 78)
    sys.exit(1 if FAIL_COUNT else 0)


if __name__ == "__main__":
    main()
