#!/usr/bin/env python3
"""Verify the narrow three-generation-observable no-proper-quotient theorem
at exact rational precision via sympy.

Claim scope: on the retained hw=1 triplet, the diagonal projectors plus
C_3 cycle generate M_3(C) and no proper subspace is invariant under both.
Class (A) algebraic identity on declared graph-visible inputs.
"""

from pathlib import Path
import sys
import json

try:
    import sympy
    from sympy import Matrix, eye, zeros, Rational
except ImportError:
    print("FAIL: sympy required")
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
NOTE_PATH = ROOT / "docs" / "THREE_GENERATION_OBSERVABLE_NO_PROPER_QUOTIENT_NARROW_THEOREM_NOTE_2026-05-02.md"
CLAIM_ID = "three_generation_observable_no_proper_quotient_narrow_theorem_note_2026-05-02"

PASS = 0
FAIL = 0


def check(label, ok, detail=""):
    global PASS, FAIL
    if ok:
        PASS += 1
    else:
        FAIL += 1
    tag = "PASS (A)" if ok else "FAIL (A)"
    print(f"  [{tag}] {label}  ({detail})")


def section(title):
    print("\n" + "-" * 88 + f"\n{title}\n" + "-" * 88)


# ============================================================================
section("Part 1: note structure and scope discipline")
# ============================================================================
note_text = NOTE_PATH.read_text()
required = [
    "Three-Generation Observable: No-Proper-Quotient Narrow Theorem",
    "Type:** bounded_theorem",
    "M_3(ℂ)",
    "C₃[111]",
    "no proper quotient",
    "SITE_PHASE_CUBE_SHIFT_INTERTWINER_NOTE.md",
    "S3_TASTE_CUBE_DECOMPOSITION_NOTE.md",
    "S3_MASS_MATRIX_NO_GO_NOTE.md",
    "Z2_HW1_MASS_MATRIX_PARAMETRIZATION_NOTE.md",
    "physical-species interpretation",
    "out of scope",
    "class (A)",
    "target_claim_type: bounded_theorem",
]
for s in required:
    check(f"contains: {s!r}", s in note_text)

# Scope discipline: must NOT load-bear on generation_axiom_boundary
forbidden = [
    "load-bears on generation_axiom_boundary",
    "physical-species claim is hereby retained",
    "substrate physicality is established",
]
for f in forbidden:
    check(f"narrow scope avoids forbidden claim: {f!r}",
          f not in note_text)


# ============================================================================
section("Part 2: diagonal projectors + cyclic permutation generate M_3(C)")
# ============================================================================
# Build P_X1, P_X2, P_X3, C_3 as 3x3 matrices over Q
P = [zeros(3, 3) for _ in range(3)]
for i in range(3):
    P[i][i, i] = Rational(1)

# Mutually orthogonal projectors summing to I_3
check("P_X_i are projectors (P_i² = P_i)",
      all(P[i] * P[i] == P[i] for i in range(3)))
check("P_X_i are mutually orthogonal (P_i P_j = 0 for i ≠ j)",
      all(P[i] * P[j] == zeros(3, 3) for i in range(3) for j in range(3) if i != j))
check("Σ P_X_i = I_3",
      sum(P, zeros(3, 3)) == eye(3))

# C_3 cyclic permutation: X_1 -> X_2 -> X_3 -> X_1
C3 = Matrix([[0, 0, 1],
             [1, 0, 0],
             [0, 1, 0]])
check("C₃³ = I_3", C3**3 == eye(3))
# C_3 is unitary: C_3 C_3^T = I (since it's a real permutation matrix)
check("C₃ is orthogonal (C₃ C₃^T = I)", C3 * C3.T == eye(3))


# ============================================================================
section("Part 3: D_3 + C_3 generates M_3(ℂ)")
# ============================================================================
# To show generation: produce all 9 matrix units E_ij from {P_X_i, C_3}.
# Diagonal: E_ii = P_X_i  ✓
# Off-diagonal: C_3 = E_21 + E_32 + E_13 (one cyclic step)
#                  = sum of off-diagonal entries
# We can isolate individual off-diagonal entries by:
#   E_21 = P_X_2 · C_3 · P_X_1
#   E_32 = P_X_3 · C_3 · P_X_2
#   E_13 = P_X_1 · C_3 · P_X_3
# And inverse:
#   E_12 = (E_21)^T = P_X_1 · C_3^T · P_X_2 = P_X_1 · C_3^2 · P_X_2

E_units = {}
for i in range(3):
    for j in range(3):
        E_units[(i, j)] = P[i] * (C3 if (j == (i-1) % 3) else (C3**2 if (j == (i+1) % 3) else (eye(3) if i == j else zeros(3, 3)))) * P[j]

# Better: use {P_i C_3^k P_j} for k = 0, 1, 2
for i in range(3):
    for j in range(3):
        if i == j:
            target = zeros(3, 3)
            target[i, i] = 1
            E_units[(i, j)] = P[i]  # diagonal
        else:
            # E_ij = P_i C_3^k P_j where C_3^k sends j -> i
            # C_3 sends j -> j+1, so to send j -> i we need k = i - j mod 3
            k = (i - j) % 3
            E_units[(i, j)] = P[i] * (C3**k) * P[j]

# Verify each E_ij is the standard matrix unit
for (i, j), E in E_units.items():
    expected = zeros(3, 3)
    expected[i, j] = 1
    ok = (E == expected)
    if not ok:
        print(f"  E_{i}{j} mismatch: got {E}, expected {expected}")
check("all 9 matrix units E_ij are generated by {P_X_i} ∪ {C_3, C_3², I}",
      all(E_units[(i, j)][i, j] == 1 and
          all(E_units[(i, j)][a, b] == 0 for a in range(3) for b in range(3) if (a, b) != (i, j))
          for i in range(3) for j in range(3)))

check("therefore <{P_X_i, C_3}> generates the full M_3(ℂ)",
      True,  # follows from the matrix-unit generation above
      detail="9 matrix units span M_3(ℂ) as a vector space")


# ============================================================================
section("Part 4: no proper subspace is D_3- and C_3-invariant")
# ============================================================================
# D_3-invariant subspaces of C^3 are direct sums of {C·e_1, C·e_2, C·e_3}
# (since each P_i is rank-1 projecting onto e_i, the only D_3-invariant
# subspaces are spans of subsets of {e_1, e_2, e_3}).
# So D_3-invariant subspaces are: {0}, span(e_1), span(e_2), span(e_3),
# span(e_1, e_2), span(e_1, e_3), span(e_2, e_3), C^3.
# That's 8 = 2^3 subspaces.

# For each NON-trivial proper subspace, check if it's also C_3-invariant.
# C_3 cycles e_1 -> e_2 -> e_3 -> e_1.
# So C_3-orbits of {e_1, e_2, e_3} are the full set or empty.
# A subset S ⊂ {1,2,3} is C_3-invariant iff S is the full orbit, i.e. S ∈ {∅, {1,2,3}}.

# Enumerate all subsets of {1,2,3} and check both invariances:
subsets = [
    frozenset(),
    frozenset({0}),
    frozenset({1}),
    frozenset({2}),
    frozenset({0, 1}),
    frozenset({0, 2}),
    frozenset({1, 2}),
    frozenset({0, 1, 2}),
]
def cycle(S):
    return frozenset((i + 1) % 3 for i in S)

D3_C3_invariant = []
for S in subsets:
    # Always D_3-invariant by construction
    # Check C_3-invariant
    if cycle(S) == S:
        D3_C3_invariant.append(S)

check("the only D_3- AND C_3-invariant subspaces are {0} and ℂ³",
      D3_C3_invariant == [frozenset(), frozenset({0, 1, 2})],
      detail=f"observed: {[sorted(S) for S in D3_C3_invariant]}")
check("therefore no PROPER subspace is invariant under both D_3 and C_3",
      len(D3_C3_invariant) == 2 and (frozenset() in D3_C3_invariant) and (frozenset({0,1,2}) in D3_C3_invariant))


# ============================================================================
section("Part 5: declared authorities are graph-visible")
# ============================================================================
LEDGER = ROOT / "docs" / "audit" / "data" / "audit_ledger.json"
ledger = json.loads(LEDGER.read_text())
rows = ledger['rows']

cited = {
    "site_phase_cube_shift_intertwiner_note": "SITE_PHASE_CUBE_SHIFT_INTERTWINER_NOTE.md",
    "s3_taste_cube_decomposition_note": "S3_TASTE_CUBE_DECOMPOSITION_NOTE.md",
    "s3_mass_matrix_no_go_note": "S3_MASS_MATRIX_NO_GO_NOTE.md",
    "z2_hw1_mass_matrix_parametrization_note": "Z2_HW1_MASS_MATRIX_PARAMETRIZATION_NOTE.md",
}
for cid, filename in cited.items():
    row = rows.get(cid)
    check(f"{cid} exists in audit ledger",
          row is not None,
          detail=f"{filename}; effective_status={row.get('effective_status') if row else None!r}")

claim_row = rows.get(CLAIM_ID)
check(f"{CLAIM_ID} seeded by audit pipeline",
      claim_row is not None,
      detail="run docs/audit/scripts/run_pipeline.sh after editing the note")
if claim_row is not None:
    claim_deps = set(claim_row.get("deps", []))
    check(f"{CLAIM_ID} records all four declared dependencies",
          set(cited).issubset(claim_deps),
          detail=f"deps={sorted(claim_deps)}")
    check(f"{CLAIM_ID} remains effective-unaudited before independent audit",
          claim_row.get("effective_status") == "unaudited",
          detail=f"effective_status={claim_row.get('effective_status')!r}")

# Verify generation_axiom_boundary_note is NOT cited
check("generation_axiom_boundary_note NOT cited as declared dependency (correctly excluded)",
      "generation_axiom_boundary_note" in note_text and
      "audited_conditional" in note_text and
      ("not** cited" in note_text or "not cited" in note_text or "is **not** cited" in note_text or
       "explicit narrowing" in note_text))


print(f"\n{'='*88}\n  TOTAL: PASS={PASS}, FAIL={FAIL}\n{'='*88}")
sys.exit(1 if FAIL > 0 else 0)
