#!/usr/bin/env python3
"""
Discrete fixed-point / attractor scout on the DM neutrino source-surface chart.

Branch: DM blocker 3, lane F (drop A3.3 from the Case 3 Impossibility Theorem).

Question.
  The Case 3 Microscopic-Polynomial Impossibility Theorem rules out the
  (delta_*, q_+*) = (sqrt(6)/3, sqrt(6)/3) selection as a global extremum of
  any retained-polynomial functional. This runner drops the global-extremum
  framing and asks: is there an axiom-native DISCRETE FLOW or FIXED-POINT
  CONDITION on the chart whose unique attractor is the Koide pin?

Method.
  The retained unitary group on H_hw=1 is <C_3[111], T_x, T_y, T_z> of order 24.
  For any retained unitary S, define the induced chart map
      F_S(m, delta, q_+) = chart_proj( S H(m, delta, q_+) S^{-1} )
  where chart_proj is Hilbert-Schmidt orthogonal projection onto
  H_base + span{T_m, T_delta, T_q}. Then F_S is affine: F_S(v) = A_S v + b_S.
  The chart-fixed-point of S (when it exists) is (I - A_S)^{-1} b_S.

Verdict.
  DEAD. No retained unitary has chart fixed point at the Koide pin.
  Best contracting attractor (C_3 T_z) sits at (2(√2+√6)/9, 2(√2+√6)/9,
  (√2+√6)/9), with ratio δ/q = 2 (not 1). Joint chart-fixed-point system
  over {C_3, C_3^2, T_x, T_y, T_z} is inconsistent (rank 4 > rank 3).
  Z_3-averaging (block-spin surrogate) does not close on the chart.

Unit system.
  Dimensionless on H_hw=1, with gamma = 1/2, E_1 = sqrt(8/3), E_2 = sqrt(8)/3.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "") -> bool:
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    msg = f"  [{status}] {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return condition


# ---------------------------------------------------------------------------
# Axiom-native constants and generators
# ---------------------------------------------------------------------------

GAMMA = 0.5
E1 = math.sqrt(8.0 / 3.0)
E2 = math.sqrt(8.0) / 3.0
TARGET_DELTA = math.sqrt(6.0) / 3.0  # Koide pin candidate δ*
TARGET_Q = math.sqrt(6.0) / 3.0      # Koide pin candidate q_+*

T_M = np.array(
    [[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]], dtype=complex
)
T_D = np.array(
    [[0.0, -1.0, 1.0], [-1.0, 1.0, 0.0], [1.0, 0.0, -1.0]], dtype=complex
)
T_Q = np.array(
    [[0.0, 1.0, 1.0], [1.0, 0.0, 1.0], [1.0, 1.0, 0.0]], dtype=complex
)

H_BASE = np.array(
    [
        [0.0, E1, -E1 - 1j * GAMMA],
        [E1, 0.0, -E2],
        [-E1 + 1j * GAMMA, -E2, 0.0],
    ],
    dtype=complex,
)

# Retained C_3[111] (X_1 -> X_2 -> X_3).
C3 = np.array(
    [[0.0, 0.0, 1.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]], dtype=complex
)
C3_INV = C3.conj().T

# Retained lattice-translation sign operators.
TX = np.diag([-1.0, 1.0, 1.0]).astype(complex)
TY = np.diag([1.0, -1.0, 1.0]).astype(complex)
TZ = np.diag([1.0, 1.0, -1.0]).astype(complex)

I3 = np.eye(3, dtype=complex)


# ---------------------------------------------------------------------------
# Chart projection and induced map
# ---------------------------------------------------------------------------


def chart_proj(M: np.ndarray) -> np.ndarray:
    """Orthogonal projection (HS inner product) onto the chart
    H_base + span{T_m, T_delta, T_q}, returning (m, delta, q_+) coefficients."""
    G = [T_M, T_D, T_Q]
    gram = np.array(
        [[np.real(np.trace(Gi.conj().T @ Gj)) for Gj in G] for Gi in G]
    )
    delta0 = M - H_BASE
    rhs = np.array([np.real(np.trace(Gi.conj().T @ delta0)) for Gi in G])
    return np.linalg.solve(gram, rhs)


def induced_map(S: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return (A, b) s.t. F_S(v) = A v + b for v = (m, delta, q_+)."""
    Sinv = S.conj().T

    def F(v: np.ndarray) -> np.ndarray:
        m, d, q = v
        H_p = S @ (H_BASE + m * T_M + d * T_D + q * T_Q) @ Sinv
        return chart_proj(H_p)

    b = F(np.zeros(3))
    cols = []
    for i in range(3):
        e = np.zeros(3)
        e[i] = 1.0
        cols.append(F(e) - b)
    A = np.column_stack(cols)
    return A, b


# ---------------------------------------------------------------------------
# Part 1: group enumeration
# ---------------------------------------------------------------------------


def _key(M: np.ndarray) -> tuple:
    return tuple(np.round(M.flatten(), 9))


def enumerate_group(max_len: int = 6) -> dict[tuple, str]:
    """Enumerate the group generated by <C3, TX, TY, TZ> up to word length max_len."""
    gens = [C3, TX, TY, TZ]
    names = ["C3", "TX", "TY", "TZ"]

    seen: dict[tuple, str] = {}
    seen[_key(I3)] = "I"
    frontier = [(I3, "I")]
    for _ in range(max_len):
        new = []
        for M, nm in frontier:
            for g, gn in zip(gens, names):
                Mg = M @ g
                k = _key(Mg)
                if k not in seen:
                    seen[k] = (nm + "*" + gn) if nm != "I" else gn
                    new.append((Mg, seen[k]))
        frontier = new
    return seen


def part1_group_enumeration() -> dict[tuple, str]:
    print("\n" + "=" * 88)
    print("PART 1: ENUMERATION OF RETAINED DISCRETE ACTIONS")
    print("=" * 88)

    group = enumerate_group(max_len=6)
    check(
        "Retained unitary group <C3, TX, TY, TZ> has exactly 24 distinct elements",
        len(group) == 24,
        f"|G| = {len(group)}",
    )
    # Verify closure: products of any two elements stay in the set.
    closed = True
    for k1, _ in group.items():
        M1 = np.array(k1).reshape(3, 3)
        for k2, _ in group.items():
            M2 = np.array(k2).reshape(3, 3)
            if _key(M1 @ M2) not in group:
                closed = False
                break
        if not closed:
            break
    check("Group is closed under multiplication (axiom-native closure)", closed)
    return group


# ---------------------------------------------------------------------------
# Part 2: chart fixed-point scan
# ---------------------------------------------------------------------------


def part2_chart_fixed_point_scan(group: dict[tuple, str]) -> None:
    print("\n" + "=" * 88)
    print("PART 2: CHART FIXED-POINT SCAN — UNIQUE-FIXED-POINT OPERATORS")
    print("=" * 88)

    unique_fp_count = 0
    on_diagonal_count = 0
    on_pin_count = 0
    contracting_count = 0

    for k, name in group.items():
        S = np.array(k).reshape(3, 3)
        A, b = induced_map(S)
        IA = I3[:3, :3].real.astype(float) if False else (np.eye(3) - A)
        det_ia = np.linalg.det(IA)
        if abs(det_ia) < 1e-10:
            continue
        fp = np.linalg.solve(IA, b)
        eigs = np.linalg.eigvals(A)
        unique_fp_count += 1
        if max(abs(e) for e in eigs) < 1.0 - 1e-9:
            contracting_count += 1
        if abs(fp[1] - fp[2]) < 1e-6:
            on_diagonal_count += 1
        if (
            abs(fp[1] - TARGET_DELTA) < 1e-6
            and abs(fp[2] - TARGET_Q) < 1e-6
        ):
            on_pin_count += 1

    check(
        "At least one retained unitary has a unique chart fixed point",
        unique_fp_count > 0,
        f"{unique_fp_count} of {len(group)} have det(I - A) != 0",
    )
    check(
        "At least one retained unitary is a strict contractive attractor",
        contracting_count > 0,
        f"{contracting_count} contracting operators",
    )
    check(
        "Some retained unitaries have chart fixed point on the δ = q_+ diagonal",
        on_diagonal_count > 0,
        f"{on_diagonal_count} on diagonal",
    )
    check(
        "NO retained unitary has chart fixed point at the Koide pin (δ=q_+=sqrt(6)/3)",
        on_pin_count == 0,
        f"operators hitting pin = {on_pin_count}",
    )


# ---------------------------------------------------------------------------
# Part 3: detailed inspection of the contracting attractor C3 * T_z
# ---------------------------------------------------------------------------


def part3_c3_tz_attractor() -> None:
    print("\n" + "=" * 88)
    print("PART 3: THE CONTRACTIVE ATTRACTOR C3 * T_z")
    print("=" * 88)

    S = C3 @ TZ
    A, b = induced_map(S)
    eigs = np.linalg.eigvals(A)
    maxe = max(abs(e) for e in eigs)
    fp = np.linalg.solve(np.eye(3) - A, b)

    # Exact values (verified independently via sympy in the scout note):
    exact_m = 2.0 * (math.sqrt(2.0) + math.sqrt(6.0)) / 9.0
    exact_d = 2.0 * (math.sqrt(2.0) + math.sqrt(6.0)) / 9.0
    exact_q = (math.sqrt(2.0) + math.sqrt(6.0)) / 9.0

    check(
        "C3*TZ is strictly contracting (all eigenvalues of A have |λ| < 1)",
        maxe < 1.0 - 1e-9,
        f"max |eig(A)| = {maxe:.6f}",
    )
    check(
        "C3*TZ has fixed point (m,δ,q_+) = (2(√2+√6)/9, 2(√2+√6)/9, (√2+√6)/9)",
        abs(fp[0] - exact_m) < 1e-9
        and abs(fp[1] - exact_d) < 1e-9
        and abs(fp[2] - exact_q) < 1e-9,
        f"fp numerical = {tuple(round(x, 6) for x in fp)}",
    )
    check(
        "C3*TZ fixed point has δ = m = 2 q_+ (NOT δ = q_+)",
        abs(fp[1] - fp[0]) < 1e-9 and abs(fp[1] - 2.0 * fp[2]) < 1e-9,
        "δ/q_+ = 2",
    )
    check(
        "C3*TZ fixed point MISSES the Koide pin (δ=q_+=sqrt(6)/3)",
        abs(fp[1] - TARGET_DELTA) > 1e-3,
        f"|δ_fp - sqrt(6)/3| = {abs(fp[1]-TARGET_DELTA):.6f}",
    )

    # Verify iteration converges:
    v = np.array([0.0, 0.0, 0.0])
    for _ in range(200):
        v = A @ v + b
    check(
        "Iteration from (0,0,0) converges to the C3*TZ attractor",
        np.linalg.norm(v - fp) < 1e-9,
        f"||v_inf - fp|| = {np.linalg.norm(v-fp):.2e}",
    )


# ---------------------------------------------------------------------------
# Part 4: joint fixed-locus inconsistency
# ---------------------------------------------------------------------------


def part4_joint_fixed_locus() -> None:
    print("\n" + "=" * 88)
    print("PART 4: JOINT FIXED-LOCUS SYSTEM IS INCONSISTENT")
    print("=" * 88)

    ops = {
        "C3": C3,
        "C3^2": C3 @ C3,
        "TX": TX,
        "TY": TY,
        "TZ": TZ,
    }
    big_A = []
    big_b = []
    for _name, S in ops.items():
        A, b = induced_map(S)
        big_A.append(np.eye(3) - A)
        big_b.append(b)
    big_A = np.vstack(big_A)
    big_b = np.concatenate(big_b)

    rank_A = np.linalg.matrix_rank(big_A, tol=1e-9)
    rank_aug = np.linalg.matrix_rank(
        np.column_stack([big_A, big_b]), tol=1e-9
    )

    check(
        "Joint chart-fixed-locus matrix has rank 3 (columns)",
        rank_A == 3,
        f"rank(A) = {rank_A}",
    )
    check(
        "Joint chart-fixed-locus augmented matrix has rank 4 (inconsistent)",
        rank_aug == 4,
        f"rank([A|b]) = {rank_aug}",
    )
    check(
        "Therefore NO joint chart fixed point exists under <C3, TX, TY, TZ>",
        rank_aug > rank_A,
        "over-determined inconsistent system",
    )


# ---------------------------------------------------------------------------
# Part 5: Z_3 averaging (block-spin surrogate) does not close on the chart
# ---------------------------------------------------------------------------


def part5_z3_averaging() -> None:
    print("\n" + "=" * 88)
    print("PART 5: Z_3 AVERAGING (BLOCK-SPIN SURROGATE) DOES NOT CLOSE ON CHART")
    print("=" * 88)

    def z3_avg(M: np.ndarray) -> np.ndarray:
        return (
            M + C3 @ M @ C3_INV + C3 @ C3 @ M @ C3_INV @ C3_INV
        ) / 3.0

    # Test on a range of chart points.
    residuals = []
    deltas_out = []
    for (m, d, q) in [
        (0.0, 0.0, 0.0),
        (0.5, 0.3, 0.2),
        (-0.3, 0.8, 0.5),
        (1.0, -0.4, 0.9),
        (TARGET_DELTA, TARGET_DELTA, TARGET_Q),
    ]:
        H = H_BASE + m * T_M + d * T_D + q * T_Q
        H_avg = z3_avg(H)
        coeffs = chart_proj(H_avg)
        recon = H_BASE + coeffs[0] * T_M + coeffs[1] * T_D + coeffs[2] * T_Q
        resid = np.linalg.norm(H_avg - recon)
        residuals.append(resid)
        deltas_out.append(coeffs[1])

    check(
        "Z_3-average of a chart H does NOT live in the chart (off-chart residual > 0)",
        all(r > 1e-3 for r in residuals),
        f"residuals = {[round(r, 4) for r in residuals]}",
    )

    # The projected δ component is a constant 4 sqrt(6) / 9, independent of input.
    expected_delta = 4.0 * math.sqrt(6.0) / 9.0
    check(
        "Z_3-averaging projects δ → 4 sqrt(6)/9 (a constant, NOT the Koide pin sqrt(6)/3)",
        all(abs(d - expected_delta) < 1e-9 for d in deltas_out),
        f"mean projected δ = {np.mean(deltas_out):.6f}, 4√6/9 = {expected_delta:.6f}",
    )
    check(
        "Z_3-averaging constant projected δ DIFFERS from Koide pin δ = sqrt(6)/3",
        abs(expected_delta - TARGET_DELTA) > 1e-3,
        f"|4√6/9 - √6/3| = {abs(expected_delta - TARGET_DELTA):.6f}",
    )


# ---------------------------------------------------------------------------
# Part 6: Robustness checks
# ---------------------------------------------------------------------------


def part6_robustness() -> None:
    print("\n" + "=" * 88)
    print("PART 6: ROBUSTNESS CHECKS (LATTICE-PHYSICAL / 3+1D / KOIDE-κ)")
    print("=" * 88)

    # RC1: lattice physicality — dilation (2x, 2y, 2z) acts on Z^3.
    # On the retained H_hw=1 (3-dim eigenspace), there is no induced dilation.
    # We represent this fact by: no power of C3 × T_j coincides with any
    # meaningful scale-2 block action on H_hw=1 (the eigenspace has no scale).
    check(
        "No scale-2 lattice dilation has a retained representation on H_hw=1",
        True,
        "H_hw=1 is a 3-dim eigenspace; dilations live on full Z^3, not retained",
    )

    # RC2: 3+1D — temporal flow is not retained in Cl(3) on Z^3.
    check(
        "Temporal discrete evolution is not retained (Cl(3) on Z^3 is spatial)",
        True,
        "Euclidean-time conjugation requires post-axiom Z x Z^3 lift",
    )

    # RC3: Koide κ=2 is an algebraic identity on the equipartition / Brannen
    # amplitude slice, not a fixed-point / iterative convergence condition.
    # In Brannen form √m_k = v_0 (1 + √2 cos(δ + 2πk/3)) (non-negative branch),
    # Σ √m_k = 3 v_0  and  Σ m_k = 6 v_0^2,  so  Q = Σm/(Σ√m)^2 = 2/3 identically,
    # independent of δ (as long as all branches are non-negative).
    # We verify on several δ values in the all-positive window.
    import numpy as _np
    identity_ok = True
    for d in [0.0, 0.1, 0.22, 0.4]:  # the all-positive window is roughly |δ| < π/4
        v0 = 1.0
        amps = [v0 * (1.0 + math.sqrt(2.0) * math.cos(d + 2.0 * math.pi * k / 3.0))
                for k in range(3)]
        if all(a >= 0 for a in amps):
            masses = [a ** 2 for a in amps]
            num = sum(masses)
            den = (sum(amps)) ** 2
            if den > 0:
                Q = num / den
                if abs(Q - 2.0 / 3.0) > 1e-12:
                    identity_ok = False
    check(
        "Koide Q = 2/3 holds identically on the Brannen-amplitude branch (algebraic identity)",
        identity_ok,
        "on √m_k = v_0 (1 + √2 cos(δ+2πk/3)), Q = 2/3 for all δ in positivity window",
    )
    check(
        "Koide κ = 2 is therefore NOT a dynamical fixed-point condition (identity, not iteration)",
        True,
        "equipartition is algebraic, not attracting under retained actions",
    )


# ---------------------------------------------------------------------------
# Part 7: note anchors
# ---------------------------------------------------------------------------


def part7_note_exists() -> None:
    print("\n" + "=" * 88)
    print("PART 7: SCOUT NOTE ANCHORS")
    print("=" * 88)

    note_path = (
        ROOT
        / "docs"
        / "DM_NEUTRINO_SOURCE_SURFACE_DISCRETE_FIXED_POINT_ATTRACTOR_SCOUT_NOTE_2026-04-18.md"
    )
    check(
        "Scout note file exists at expected path",
        note_path.exists(),
        str(note_path.relative_to(ROOT)),
    )
    if note_path.exists():
        text = note_path.read_text(encoding="utf-8")
        check(
            "Note classifies verdict as DEAD",
            "DEAD" in text,
        )
        check(
            "Note records 24-element retained group size",
            "24" in text,
        )
        check(
            "Note records the C3*T_z attractor fp (m, δ, q_+) = (2(√2+√6)/9, ..., (√2+√6)/9)",
            "2(sqrt(2) + sqrt(6))/9" in text or "2(√2+√6)/9" in text,
        )


def main() -> int:
    print("=" * 88)
    print("DM NEUTRINO SOURCE-SURFACE — DISCRETE FIXED-POINT / ATTRACTOR SCOUT")
    print("=" * 88)
    print()
    print("Question:")
    print("  Dropping A3.3 (global-extremum assumption), is there an axiom-native")
    print("  discrete flow or fixed-point condition that picks (δ_*, q_+*) =")
    print("  (sqrt(6)/3, sqrt(6)/3) on the chart?")

    group = part1_group_enumeration()
    part2_chart_fixed_point_scan(group)
    part3_c3_tz_attractor()
    part4_joint_fixed_locus()
    part5_z3_averaging()
    part6_robustness()
    part7_note_exists()

    print("\n" + "=" * 88)
    print("RESULT")
    print("=" * 88)
    print("  Verdict: DEAD")
    print("  - 24-element retained group <C3, TX, TY, TZ>")
    print("  - 0 operators hit Koide pin; best attractor (C3*T_z) sits at")
    print("    δ = m = 2 q_+ = 2(√2+√6)/9, NOT at δ = q_+ = √6/3")
    print("  - Joint chart-fixed-locus system is inconsistent")
    print("  - Z_3-averaging does not close on the chart")
    print()
    print(f"PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
