#!/usr/bin/env python3
"""Pattern A narrow runner for
`CUBIC_INVARIANT_RANK_TWO_ISOTROPY_NARROW_THEOREM_NOTE_2026-05-10`.

Verifies the standalone cubic-group / linear-algebra identity that
the only `O_h`-invariant rank-2 tensor on `R^3` is proportional to
`delta_ij`, with rank-1 and rank-3 invariants both forced to zero.

NARROW THEOREM STATEMENT
========================

Let `O_h` denote the full cubic group acting on `R^3` (the symmetry
group of the cube, `|O_h| = 48`) generated by the three coordinate
sign-flips and any two of the three 90-degree axis rotations
`(x, y) -> (-y, x)`, `(y, z) -> (-z, y)`, `(z, x) -> (-x, z)`.

  Conclusion (T1) (rank-1 vanishing):
    The only `O_h`-invariant rank-1 tensor `v_i` on `R^3` is `v = 0`.

  Conclusion (T2) (rank-2 isotropy):
    Every `O_h`-invariant rank-2 tensor `T_ij` on `R^3` has the form
        T_ij  =  c * delta_ij,    c in R.
    In particular `T` is automatically isotropic (`SO(3)`-invariant).
    The free-parameter dimension of the `O_h`-invariant rank-2 tensor
    space is exactly `1`.

  Conclusion (T3) (rank-3 vanishing):
    The only `O_h`-invariant rank-3 tensor `T_ijk` on `R^3` is `T = 0`.

  Conclusion (T4) (corollary -- automatic transverse second-moment
                   isotropy of cubic-symmetric measures):
    Let `mu` be any probability measure on a finite `O_h`-stable subset
    `S` of `R^3` (or on a finite cubic-orbit-stable subset of `Z^3`,
    embedded into `R^3` via the standard inclusion). Define the
    second-moment matrix `M_ij := sum_{x in S} mu(x) x_i x_j`. Then
    cubic invariance of `mu` (i.e. `mu(g.x) = mu(x)` for every
    `g in O_h`) forces `M_ij = (1/3) <r^2> delta_ij`, where
    `<r^2> := sum_x mu(x) (x_1^2 + x_2^2 + x_3^2)`.
    Equivalently the diagonal moments `<x_1^2>`, `<x_2^2>`, `<x_3^2>`
    are pairwise equal and the off-diagonal moments `<x_i x_j>` for
    `i != j` all vanish.

This is pure cubic-group representation theory on real tensor spaces.
No directional path measure, no Wilson action, no continuum-limit
Lagrangian, no `beta` choice, no PDG / literature numerical comparator,
and no fitted parameter is consumed.

THIS RUNNER VERIFIES (PASS=N, FAIL=0):

  Part A: Cubic-group generator setup.
  Part B: Rank-1 (vector) cubic invariance forces zero.
  Part C: Rank-2 cubic invariance forces `c * delta_ij` (1 free
          scalar parameter).
  Part D: Rank-3 cubic invariance forces zero.
  Part E: Rank-4 cubic invariance has more than 1 free parameter
          (sharpens the boundary: T2 is special to rank 2).
  Part F: Corollary (T4) on cubic-symmetric measures: explicit finite
          subsets of `Z^3` (face-only, edge-only, corner-only,
          and the full {-1, 0, +1}^3 cube), each O_h-stable, each
          carries cubic-symmetric uniform measures whose second-moment
          matrix is exactly `c * I_3` with the correct trace.
  Part G: Negative control. A non-cubic-symmetric measure on the same
          {-1, 0, +1}^3 cube can have anisotropic second moments
          (i.e. T2 fails without cubic invariance).
"""

from __future__ import annotations

import sys
from itertools import product

import sympy as sp
from sympy import Rational, Matrix, eye, simplify, symbols, expand


PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "", kind: str = "EXACT") -> bool:
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    tag = f" [{kind}]" if kind != "EXACT" else ""
    msg = f"  [{status}]{tag} {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return condition


def section(title: str) -> None:
    print("\n" + "-" * 88 + f"\n{title}\n" + "-" * 88)


# ============================================================================
section("Part A: Cubic group O_h generators on R^3")
# ============================================================================

# Sign flips on each axis (3 generators); these together with axis-permutations
# generate the full cubic group O_h of order 48.
S1 = sp.diag(-1, 1, 1)
S2 = sp.diag(1, -1, 1)
S3 = sp.diag(1, 1, -1)
# 90-degree axis rotations
R_xy = Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 1]])
R_yz = Matrix([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
R_zx = Matrix([[0, 0, 1], [0, 1, 0], [-1, 0, 0]])

generators = [S1, S2, S3, R_xy, R_yz, R_zx]

# Verify: each generator is orthogonal (R^T R = I).
for idx, R in enumerate(generators):
    ok = simplify(R.T * R - eye(3)) == sp.zeros(3, 3)
    check(f"Generator {idx} is orthogonal (R^T R = I)", ok)

# Verify: each generator has determinant ±1 (i.e. is in O(3)).
for idx, R in enumerate(generators):
    d = R.det()
    check(f"Generator {idx} has det = ±1", d in (1, -1), detail=f"det = {d}")


# ============================================================================
section("Part B: Rank-1 (vector) cubic invariance forces zero")
# ============================================================================

v = sp.symarray("v", 3)
v_sym = Matrix(v.tolist())

constraints = []
for R in generators:
    diff = R * v_sym - v_sym
    for i in range(3):
        constraints.append(diff[i])

sol = sp.solve(constraints, list(v), dict=True)
all_zero = sol == [{v[0]: 0, v[1]: 0, v[2]: 0}]
check("Only O_h-invariant rank-1 tensor on R^3 is zero", all_zero,
      detail=f"sol = {sol}")


# ============================================================================
section("Part C: Rank-2 cubic invariance forces T = c * delta_ij (1 free param)")
# ============================================================================

t = sp.symarray("t", (3, 3))
T_sym = Matrix(t.tolist())

constraints = []
for R in generators:
    diff = simplify(R.T * T_sym * R - T_sym)
    for i in range(3):
        for j in range(3):
            constraints.append(diff[i, j])

free_syms = list(t.flatten())
sol2 = sp.solve(constraints, free_syms, dict=True)

# Expected: the only free parameter is the diagonal value (e.g. t_2_2),
# all other entries equal to it (on diagonal) or zero (off diagonal).
expected = {
    t[0, 0]: t[2, 2],
    t[0, 1]: 0,
    t[0, 2]: 0,
    t[1, 0]: 0,
    t[1, 1]: t[2, 2],
    t[1, 2]: 0,
    t[2, 0]: 0,
    t[2, 1]: 0,
}
got = sol2[0] if sol2 else {}

check("Rank-2 cubic-invariant solution sets all off-diagonals to zero",
      all(got.get(t[i, j], None) == 0 for i in range(3) for j in range(3) if i != j),
      detail=f"off-diagonals: {[got.get(t[i,j]) for i in range(3) for j in range(3) if i != j]}")

check("Rank-2 cubic-invariant solution forces t_00 = t_11 = t_22",
      got.get(t[0, 0]) == got.get(t[1, 1]) == t[2, 2],
      detail=f"t_00 -> {got.get(t[0,0])}, t_11 -> {got.get(t[1,1])}, t_22 free")

# Free-parameter count: count symbols on right side that are still free.
free_set = set()
for s in free_syms:
    rhs = got.get(s, s)  # if not solved, rhs == s itself
    if rhs == s:
        free_set.add(s)
    else:
        # rhs may itself contain free symbols
        for f in rhs.free_symbols:
            if f in free_syms:
                free_set.add(f)

check("Rank-2 cubic-invariant tensor has exactly 1 free parameter",
      len(free_set) == 1,
      detail=f"free params = {sorted(free_set, key=str)}")

# Reconstruct the symbolic invariant: should be c * I_3.
c = symbols("c")
T_inv = simplify(T_sym.subs({**got, t[2, 2]: c}))
check("Rank-2 invariant has the form c * I_3",
      simplify(T_inv - c * eye(3)) == sp.zeros(3, 3),
      detail=f"T_inv = {T_inv}")


# ============================================================================
section("Part D: Rank-3 cubic invariance forces zero")
# ============================================================================

# 27 symbols for the rank-3 tensor.
syms3 = sp.symbols("a0:27")

def get_rank3(syms):
    T = {}
    for idx, (i, j, k) in enumerate(product(range(3), repeat=3)):
        T[(i, j, k)] = syms[idx]
    return T

def conjugate_rank3(T, R):
    Tnew = {}
    for ip, jp, kp in product(range(3), repeat=3):
        s = 0
        for i, j, k in product(range(3), repeat=3):
            s += R[ip, i] * R[jp, j] * R[kp, k] * T[(i, j, k)]
        Tnew[(ip, jp, kp)] = s
    return Tnew

T3 = get_rank3(syms3)
constraints3 = []
for R in generators:
    Tnew = conjugate_rank3(T3, R)
    for key in T3:
        constraints3.append(simplify(Tnew[key] - T3[key]))

sol3 = sp.solve(constraints3, list(syms3), dict=True)
all_zero3 = all(sol3[0].get(s, s) == 0 for s in syms3)
check("Only O_h-invariant rank-3 tensor on R^3 is zero", all_zero3,
      detail=f"all 27 entries forced to 0: {all_zero3}")


# ============================================================================
section("Part E: Rank-4 cubic invariance has > 1 free parameter (sharpens T2)")
# ============================================================================

# 81 symbols for rank-4. (This tests that T2's "1 free parameter"
# uniqueness is special to rank 2; rank 4 has the well-known 4 cubic
# invariants, vs SO(3)'s 3 isotropic rank-4 invariants.)
syms4 = sp.symbols("b0:81")

def get_rank4(syms):
    T = {}
    for idx, (i, j, k, l) in enumerate(product(range(3), repeat=4)):
        T[(i, j, k, l)] = syms[idx]
    return T

def conjugate_rank4(T, R):
    Tnew = {}
    for ip, jp, kp, lp in product(range(3), repeat=4):
        s = 0
        for i, j, k, l in product(range(3), repeat=4):
            s += (R[ip, i] * R[jp, j] * R[kp, k] * R[lp, l]
                  * T[(i, j, k, l)])
        Tnew[(ip, jp, kp, lp)] = s
    return Tnew

T4 = get_rank4(syms4)
constraints4 = []
for R in generators:
    Tnew = conjugate_rank4(T4, R)
    for key in T4:
        constraints4.append(simplify(Tnew[key] - T4[key]))

sol4 = sp.solve(constraints4, list(syms4), dict=True)
free4 = set()
for s in syms4:
    rhs = sol4[0].get(s, s)
    if rhs == s:
        free4.add(s)
    else:
        for f in rhs.free_symbols:
            if f in syms4:
                free4.add(f)

# Standard cubic representation theory: 4 cubic-invariant rank-4 tensors.
check("Rank-4 cubic-invariant tensor has exactly 4 free parameters",
      len(free4) == 4,
      detail=f"|free| = {len(free4)} (expected 4)")

check("Rank-4 free-parameter count strictly exceeds rank-2 (1)",
      len(free4) > 1,
      detail="confirms T2 is special to rank 2")


# ============================================================================
section("Part F: Corollary T4 -- cubic-symmetric finite measures on Z^3")
# ============================================================================

# Build several O_h-stable finite subsets S of Z^3 and verify that the uniform
# measure on each yields a second-moment matrix M_ij = c * I_3.

def second_moment_matrix(weights):
    """Compute M_ij = sum_x mu(x) x_i x_j over a dict weights: tuple -> Rational."""
    M = sp.zeros(3, 3)
    for x, w in weights.items():
        for i in range(3):
            for j in range(3):
                M[i, j] += w * x[i] * x[j]
    return simplify(M)


def is_orbit_stable(S, generators):
    """Check that S (a set of integer 3-tuples) is closed under the cubic group."""
    S_set = set(tuple(int(c) for c in x) for x in S)
    for x in S_set:
        v = Matrix([Rational(x[0]), Rational(x[1]), Rational(x[2])])
        for R in generators:
            y = R * v
            t = (int(y[0]), int(y[1]), int(y[2]))
            if t not in S_set:
                return False, (x, t)
    return True, None


# Cubic-symmetric subsets of Z^3 (small):
cubic_subsets = {
    "face_neighbours_only": [(1, 0, 0), (-1, 0, 0),
                             (0, 1, 0), (0, -1, 0),
                             (0, 0, 1), (0, 0, -1)],
    "edge_neighbours_only": [(a, b, 0) for a in (1, -1) for b in (1, -1)]
                          + [(a, 0, b) for a in (1, -1) for b in (1, -1)]
                          + [(0, a, b) for a in (1, -1) for b in (1, -1)],
    "corner_neighbours_only": [(a, b, c) for a in (1, -1)
                                          for b in (1, -1)
                                          for c in (1, -1)],
    "full_unit_cube": [(a, b, c) for a in (-1, 0, 1)
                                  for b in (-1, 0, 1)
                                  for c in (-1, 0, 1)],
}

for name, S in cubic_subsets.items():
    ok, witness = is_orbit_stable(S, generators)
    check(f"Subset '{name}' is O_h-orbit-stable", ok,
          detail=("closed under all 6 generators" if ok else f"missing image: {witness}"))

    # Uniform probability measure
    mu = {tuple(x): Rational(1, len(S)) for x in S}
    M = second_moment_matrix(mu)
    # M should equal a scalar times I_3.
    diag_vals = [M[0, 0], M[1, 1], M[2, 2]]
    off_diag = [M[i, j] for i in range(3) for j in range(3) if i != j]

    check(f"'{name}': diagonals equal (<x_1^2> = <x_2^2> = <x_3^2>)",
          diag_vals[0] == diag_vals[1] == diag_vals[2],
          detail=f"diag = {diag_vals}")
    check(f"'{name}': off-diagonal moments all zero",
          all(v == 0 for v in off_diag),
          detail=f"off-diag = {set(off_diag)}")

    # Trace and explicit (1/3) <r^2> form
    trace = sum(diag_vals)
    avg_r2 = sum(mu[tuple(x)] * (x[0] ** 2 + x[1] ** 2 + x[2] ** 2) for x in S)
    check(f"'{name}': trace M = <r^2>",
          simplify(trace - avg_r2) == 0,
          detail=f"trace = {trace}, <r^2> = {avg_r2}")
    check(f"'{name}': M = (1/3) <r^2> I_3",
          simplify(M - Rational(1, 3) * avg_r2 * eye(3)) == sp.zeros(3, 3),
          detail=f"M = {M}, <r^2> = {avg_r2}")


# ============================================================================
section("Part G: Negative control -- non-cubic-symmetric measure can be anisotropic")
# ============================================================================

# On the same full unit cube {-1, 0, +1}^3, a NON-cubic-symmetric weighting
# (concentrate weight on the x-axis points only) can produce anisotropic
# second moments along the diagonal.
S_full = cubic_subsets["full_unit_cube"]
mu_anis = {}
total = Rational(0)
for x in S_full:
    # Weight x-axis offsets heavily, all others equally low: this breaks the
    # axis-permutation subgroup of O_h and produces <x_1^2> > <x_2^2>.
    on_x_axis = (x[1] == 0 and x[2] == 0 and x[0] != 0)
    w = Rational(10) if on_x_axis else Rational(1)
    mu_anis[tuple(x)] = w
    total += w

mu_anis = {k: v / total for k, v in mu_anis.items()}
M_anis = second_moment_matrix(mu_anis)

check("Anisotropic (non-cubic) measure has <x_1^2> != <x_2^2>",
      M_anis[0, 0] != M_anis[1, 1],
      detail=f"<x_1^2> = {M_anis[0,0]}, <x_2^2> = {M_anis[1,1]}")

# Also check the measure is genuinely NOT cubic invariant: there should be a
# witness x in S_full and g in generators with mu(g.x) != mu(x).
mu_witness_violation = False
for x in S_full:
    v = Matrix([Rational(x[0]), Rational(x[1]), Rational(x[2])])
    for R in generators:
        y = R * v
        gx = (int(y[0]), int(y[1]), int(y[2]))
        if gx in mu_anis and mu_anis[gx] != mu_anis[tuple(x)]:
            mu_witness_violation = True
            break
    if mu_witness_violation:
        break

check("Anisotropic measure is NOT O_h-invariant (witness violation exists)",
      mu_witness_violation,
      detail="boosting +x but not -x breaks the sign-flip symmetry S1")


# ============================================================================
section("Narrow theorem summary")
# ============================================================================

print("""
  Narrow Pattern A theorem statement:

  HYPOTHESIS:
    Let O_h be the cubic group acting on R^3 (generated by axis sign-flips
    and 90-degree axis rotations). Let T be a real tensor on R^3 of rank
    1, 2, 3, or 4.

  CONCLUSION:
    (T1)  rank-1 O_h-invariant tensors:  T = 0 only.
    (T2)  rank-2 O_h-invariant tensors:  T_ij = c * delta_ij,  c in R
                                          (1 free real parameter).
    (T3)  rank-3 O_h-invariant tensors:  T = 0 only.
    (T4)  rank-4 O_h-invariant tensors:  4-parameter family
                                          (strictly more than rank-2).

  COROLLARY (T4 -> automatic transverse second-moment isotropy):
    Any cubic-symmetric probability measure mu on a finite O_h-stable
    subset of Z^3 has second-moment matrix M_ij = (1/3) <r^2> delta_ij.
    Equivalently <x_1^2> = <x_2^2> = <x_3^2> and <x_i x_j> = 0 for i != j,
    automatically.

  Audit-lane class:
    (A) -- pure cubic-group representation theory on real tensor spaces
    plus elementary finite-set polynomial-moment computations. No
    directional path measure, no Wilson action, no kernel choice (no
    `beta`), no fitted parameter, no PDG / literature numerical comparator.

  This narrow theorem isolates the rank-2 cubic-invariant uniqueness
  identity from any directional-path-measure framing, and makes the
  underlying claim "leading-order transverse second-moment isotropy is
  automatic from cubic symmetry" stand on group-theoretic ground.
""")


# ============================================================================
print(f"\n{'='*88}\n  TOTAL: PASS={PASS_COUNT}, FAIL={FAIL_COUNT}\n{'='*88}")
sys.exit(1 if FAIL_COUNT > 0 else 0)
