#!/usr/bin/env python3
"""
Koide circulant Wilson-target runner
===================================

STATUS: constructive target reduction on the charged-lepton Koide lane

Question:
  If we stop treating the charged-lepton Wilson target as a generic Herm(3)
  object, what is the smallest structured Hermitian family that could realize
  the Koide spectral lane?

Safe answer:
  The generic Wilson-side Hermitian target is 9 real dimensions, but the
  C_3-covariant Hermitian subfamily is only 3 real dimensions:

      H = a I + b C + b* C^2
        = a I + x (C + C^2) + y i (C - C^2)

  and the Koide condition cuts that to a 2-real family:

      3 a^2 = 6 |b|^2  <=>  a^2 = 2 (x^2 + y^2).

  This 3-real circulant family already sits inside the adjacent-chain path
  algebra used by the new Wilson-side constructive DM notes.
"""

from __future__ import annotations

import math
import sys

import numpy as np
import sympy as sp

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "", kind: str = "EXACT") -> bool:
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    tag = f" [{kind}]" if kind != "EXACT" else ""
    msg = f"  [{status}]{tag} {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return condition


def matrix_unit(i: int, j: int) -> sp.Matrix:
    M = sp.zeros(3)
    M[i, j] = 1
    return M


def build_cycle_objects():
    C = sp.Matrix([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
    Cd = C.T
    I3 = sp.eye(3)
    X = C + Cd
    Y = sp.I * (C - Cd)
    return I3, C, Cd, X, Y


def part1_c3_covariant_hermitian_target():
    print("=" * 88)
    print("PART 1: the C_3-covariant Hermitian target is 3-real-dimensional")
    print("=" * 88)

    I3, C, Cd, X, Y = build_cycle_objects()

    d1, d2, d3 = sp.symbols("d1 d2 d3", real=True)
    x12, x13, x23 = sp.symbols("x12 x13 x23", real=True)
    y12, y13, y23 = sp.symbols("y12 y13 y23", real=True)
    unknowns = [d1, d2, d3, x12, x13, x23, y12, y13, y23]
    H = sp.Matrix(
        [
            [d1, x12 + sp.I * y12, x13 + sp.I * y13],
            [x12 - sp.I * y12, d2, x23 + sp.I * y23],
            [x13 - sp.I * y13, x23 - sp.I * y23, d3],
        ]
    )
    eqs = list((H * C - C * H).reshape(9, 1))
    A, _ = sp.linear_eq_to_matrix(eqs, unknowns)
    dim_comm = len(unknowns) - A.rank()

    flat_basis = sp.Matrix.hstack(*(M.reshape(9, 1) for M in [I3, X, Y]))
    rank_basis = flat_basis.rank()

    a, x, y = sp.symbols("a x y", real=True)
    H_cyc = sp.simplify(a * I3 + x * X + y * Y)

    check(
        "Herm(3) has 9 real dimensions",
        len(unknowns) == 9,
    )
    check(
        "The Hermitian commutant of the retained 3-cycle has real dimension 3",
        dim_comm == 3,
        detail=f"rank={A.rank()}",
    )
    check(
        "I, C + C^2, and i(C - C^2) are real-linearly independent",
        rank_basis == 3,
    )
    check(
        "The displayed 3-generator family is Hermitian",
        sp.simplify(H_cyc - H_cyc.H) == sp.zeros(3),
    )
    check(
        "The displayed 3-generator family commutes with the retained 3-cycle",
        sp.simplify(H_cyc * C - C * H_cyc) == sp.zeros(3),
    )


def part2_chain_algebra_contains_cycle():
    print()
    print("=" * 88)
    print("PART 2: the adjacent-chain path algebra already contains the cycle generators")
    print("=" * 88)

    I3, C, Cd, X, Y = build_cycle_objects()

    E11 = matrix_unit(0, 0)
    E12 = matrix_unit(0, 1)
    E21 = matrix_unit(1, 0)
    E22 = matrix_unit(1, 1)
    E23 = matrix_unit(1, 2)
    E32 = matrix_unit(2, 1)
    E33 = matrix_unit(2, 2)
    E13 = matrix_unit(0, 2)
    E31 = matrix_unit(2, 0)

    C_chain = E21 + E32 + E13
    Cd_chain = E12 + E23 + E31

    check(
        "The long corner E_13 is generated by the adjacent two-edge chain",
        E12 * E23 == E13,
    )
    check(
        "The long corner E_31 is generated by the adjoint chain",
        E32 * E21 == E31,
    )
    check(
        "The forward cycle C lies in the adjacent-chain algebra",
        C_chain == C,
    )
    check(
        "The backward cycle C^2 = C^dagger lies in the adjacent-chain algebra",
        Cd_chain == Cd,
    )
    check(
        "The Hermitian cyclic generators X and Y therefore already lie in the same local path algebra",
        X == C_chain + Cd_chain and Y == sp.I * (C_chain - Cd_chain),
    )
    check(
        "The diagonal identity generator is also in the chain algebra",
        E11 + E22 + E33 == I3,
    )


def part3_koide_target_size():
    print()
    print("=" * 88)
    print("PART 3: the Koide condition cuts the 3-real cyclic target down to 2 real parameters")
    print("=" * 88)

    I3, C, Cd, _, _ = build_cycle_objects()
    a, x, y = sp.symbols("a x y", real=True)
    b = x + sp.I * y
    H = sp.simplify(a * I3 + b * C + sp.conjugate(b) * Cd)

    abs_b_sq = sp.simplify(b * sp.conjugate(b))
    a0 = sp.sqrt(3) * a
    z = sp.sqrt(3) * b

    check(
        "The 3-real cyclic family is exactly H = a I + b C + b* C^2",
        sp.simplify(H - (a * I3 + x * (C + Cd) + y * sp.I * (C - Cd))) == sp.zeros(3),
    )
    check(
        "|b|^2 = x^2 + y^2 in the real cyclic coordinates",
        sp.simplify(abs_b_sq - (x**2 + y**2)) == 0,
    )
    check(
        "The Koide bridge inside the cyclic family is a_0^2 - 2|z|^2 = 3 a^2 - 6 |b|^2",
        sp.simplify((a0**2 - 2 * z * sp.conjugate(z)) - (3 * a**2 - 6 * abs_b_sq)) == 0,
    )
    check(
        "So the Koide condition is the single real equation a^2 = 2(x^2 + y^2)",
        sp.simplify((3 * a**2 - 6 * abs_b_sq) - 3 * (a**2 - 2 * (x**2 + y**2))) == 0,
    )
    check(
        "Target size collapses from 9 generic real channels to 3 cyclic channels and then to a 2-real Koide family",
        True,
        detail="Herm(3): 9 real -> Herm(3)^{C3}: 3 real -> Koide cone: 2 real",
    )


def part4_observed_target():
    print()
    print("=" * 88)
    print("PART 4: the observed charged-lepton amplitude triple lies on that 2-real family")
    print("=" * 88)

    masses = np.array([0.51099895, 105.6583755, 1776.86], dtype=float)
    amps = np.sqrt(masses)
    w = np.exp(2j * np.pi / 3)

    a = float(np.mean(amps))
    b = (amps[0] + np.conjugate(w) * amps[1] + w * amps[2]) / 3.0
    ratio = (a * a) / (2.0 * abs(b) ** 2)
    recon = np.array(
        [
            a + b + np.conjugate(b),
            a + b * w + np.conjugate(b) * np.conjugate(w),
            a + b * np.conjugate(w) + np.conjugate(b) * w,
        ],
        dtype=complex,
    )
    phase = math.atan2(b.imag, b.real)

    check(
        "The observed sqrt(m) triple is reconstructed exactly by one cyclic pair (a, b)",
        np.max(np.abs(recon.real - amps)) < 1e-9 and np.max(np.abs(recon.imag)) < 1e-9,
        detail=f"a={a:.9f}, b={b.real:.9f}{b.imag:+.9f}i",
        kind="NUMERIC",
    )
    check(
        "Observed charged leptons satisfy a^2 = 2|b|^2 to Koide precision",
        abs(ratio - 1.0) < 1e-4,
        detail=f"ratio={ratio:.10f}",
        kind="NUMERIC",
    )
    check(
        "So the observed amplitude target is one scale plus one phase inside the cyclic Koide family",
        True,
        detail=f"scale=a={a:.6f}, phase(arg(b))={phase:.6f} rad",
        kind="NUMERIC",
    )


def main() -> int:
    part1_c3_covariant_hermitian_target()
    part2_chain_algebra_contains_cycle()
    part3_koide_target_size()
    part4_observed_target()

    print()
    print("Interpretation:")
    print("  The constructive Koide target is much smaller than a generic 9-channel")
    print("  Hermitian reconstruction problem. One local adjacent-chain embedding")
    print("  already contains the full 3-real C_3-covariant Hermitian family, and")
    print("  the Koide condition cuts that to a 2-real scale-plus-phase target.")
    print("  So the positive next attack is not 'derive an arbitrary Herm(3) block',")
    print("  but 'derive a cyclic 3-channel Wilson descendant, then the one-equation")
    print("  selector that lands it on the Koide cone.'")
    print()
    print(f"PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
