#!/usr/bin/env python3
"""Lane 3 C3-oriented Ward splitter support theorem.

This block-06 runner verifies the exact local normal form behind
QUARK_C3_ORIENTED_WARD_SPLITTER_SUPPORT_NOTE_2026-04-28.md.

It checks that Hermitian Ward operators commuting with the retained induced
C3[111] cycle are exactly a three-real-parameter family

    W(a,b,c) = a I + b(C + C^2) + c(C - C^2)/(i sqrt(3)).

The c coefficient is odd under reflection, and generic c splits the S3 E
doublet into two cyclic Fourier channels. The runner also checks the boundary:
a C3-equivariant readout that remains diagonal in the generation basis is
scalar, so this is exact support for a source/readout primitive, not retained
quark-mass closure.
"""

from __future__ import annotations

from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

PASS_COUNT = 0
FAIL_COUNT = 0
TOL = 1.0e-10


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS_COUNT, FAIL_COUNT
    if condition:
        PASS_COUNT += 1
        status = "PASS"
    else:
        FAIL_COUNT += 1
        status = "FAIL"
    suffix = f" -- {detail}" if detail else ""
    print(f"{status}: {name}{suffix}")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def c3_cycle() -> np.ndarray:
    """Retained C3[111] action: X1 -> X2 -> X3 -> X1."""
    return np.array(
        [
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
        ],
        dtype=complex,
    )


def reflection_12() -> np.ndarray:
    return np.array(
        [
            [0.0, 1.0, 0.0],
            [1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
        ],
        dtype=complex,
    )


def translations() -> dict[str, np.ndarray]:
    return {
        "Tx": np.diag([-1.0, +1.0, +1.0]).astype(complex),
        "Ty": np.diag([+1.0, -1.0, +1.0]).astype(complex),
        "Tz": np.diag([+1.0, +1.0, -1.0]).astype(complex),
    }


def commutator_norm(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.max(np.abs(a @ b - b @ a)))


def w_c3(a: float, b: float, c: float) -> np.ndarray:
    cycle = c3_cycle()
    cycle2 = cycle @ cycle
    ident = np.eye(3, dtype=complex)
    splitter = (cycle - cycle2) / (1j * np.sqrt(3.0))
    return a * ident + b * (cycle + cycle2) + c * splitter


def fourier_basis() -> np.ndarray:
    omega = np.exp(2j * np.pi / 3.0)
    columns = [
        np.array([1.0, 1.0, 1.0], dtype=complex),
        np.array([1.0, omega**2, omega], dtype=complex),
        np.array([1.0, omega, omega**2], dtype=complex),
    ]
    return np.stack(columns, axis=1) / np.sqrt(3.0)


def distinct_eigenvalue_count(values: np.ndarray, tol: float = 1.0e-9) -> int:
    vals = sorted(float(np.real(v)) for v in values)
    groups: list[float] = []
    for value in vals:
        if not groups or abs(value - groups[-1]) > tol:
            groups.append(value)
    return len(groups)


def hermitian_real_basis() -> list[np.ndarray]:
    basis: list[np.ndarray] = []
    for idx in range(3):
        matrix = np.zeros((3, 3), dtype=complex)
        matrix[idx, idx] = 1.0
        basis.append(matrix)
    for i in range(3):
        for j in range(i + 1, 3):
            real = np.zeros((3, 3), dtype=complex)
            real[i, j] = 1.0
            real[j, i] = 1.0
            imag = np.zeros((3, 3), dtype=complex)
            imag[i, j] = 1j
            imag[j, i] = -1j
            basis.extend([real, imag])
    return basis


def invariant_hermitian_span_dim(generators: list[np.ndarray]) -> int:
    projected: list[np.ndarray] = []
    group = []
    cycle = c3_cycle()
    ident = np.eye(3, dtype=complex)
    if len(generators) == 1 and np.allclose(generators[0], cycle):
        group = [ident, cycle, cycle @ cycle]
    else:
        # The only non-C3 use in this runner is S3 generated by C3 and a
        # reflection, whose six elements are enough for the averaging check.
        refl = reflection_12()
        group = [ident, cycle, cycle @ cycle, refl, refl @ cycle, refl @ cycle @ cycle]

    for matrix in hermitian_real_basis():
        avg = np.zeros((3, 3), dtype=complex)
        for op in group:
            avg += op @ matrix @ op.conj().T / len(group)
        projected.append(avg)
    stacked = np.stack([matrix.reshape(9) for matrix in projected], axis=1)
    return int(np.linalg.matrix_rank(np.vstack([stacked.real, stacked.imag]), tol=TOL))


def solve_c3_coefficients(matrix: np.ndarray) -> tuple[np.ndarray, float]:
    cycle = c3_cycle()
    basis = [
        np.eye(3, dtype=complex),
        cycle + cycle @ cycle,
        (cycle - cycle @ cycle) / (1j * np.sqrt(3.0)),
    ]
    design = np.stack([item.reshape(9) for item in basis], axis=1)
    coeffs, *_ = np.linalg.lstsq(design, matrix.reshape(9), rcond=None)
    recon = sum(coeffs[i] * basis[i] for i in range(3))
    residual = float(np.linalg.norm(recon - matrix))
    return coeffs, residual


def is_diagonal(matrix: np.ndarray) -> bool:
    return np.max(np.abs(matrix - np.diag(np.diag(matrix)))) < TOL


def main() -> int:
    print("=" * 88)
    print("LANE 3 C3-ORIENTED WARD SPLITTER SUPPORT")
    print("=" * 88)

    new_note = DOCS / "QUARK_C3_ORIENTED_WARD_SPLITTER_SUPPORT_NOTE_2026-04-28.md"
    block05_note = DOCS / "QUARK_GENERATION_EQUIVARIANT_WARD_DEGENERACY_NO_GO_NOTE_2026-04-28.md"
    observable_note = DOCS / "THREE_GENERATION_OBSERVABLE_THEOREM_NOTE.md"
    s3_note = DOCS / "S3_TASTE_CUBE_DECOMPOSITION_NOTE.md"
    z2_note = DOCS / "Z2_HW1_MASS_MATRIX_PARAMETRIZATION_NOTE.md"

    print()
    print("A. Authority surfaces")
    print("-" * 72)
    for path in (new_note, block05_note, observable_note, s3_note, z2_note):
        check(f"{path.name} exists", path.exists(), str(path.relative_to(ROOT)))

    new_text = read(new_note)
    block05_text = read(block05_note)
    observable_text = read(observable_note)
    z2_text = read(z2_note)

    check("block05 names source/readout primitive as load-bearing", "source/readout/symmetry-breaking primitive" in block05_text)
    check("observable theorem supplies induced C3[111]", "C3[111]" in observable_text and "X1 -> X2 -> X3 -> X1" in observable_text)
    check("Z2 support note confirms symmetry-reduced families are support tools", "does not claim a derived flavor hierarchy" in z2_text)
    check("new note forbids retained mass closure", "does not claim retained" in new_text and "`m_b`" in new_text)
    check("new note forbids observed quark masses as proof inputs", "observed quark masses" in new_text and "Forbidden proof inputs" in new_text)

    print()
    print("B. Retained C3 cycle and reflection action")
    print("-" * 72)
    cycle = c3_cycle()
    cycle2 = cycle @ cycle
    refl = reflection_12()
    ident = np.eye(3, dtype=complex)
    splitter = (cycle - cycle2) / (1j * np.sqrt(3.0))
    symmetric = cycle + cycle2

    check("C is unitary", np.allclose(cycle.conj().T @ cycle, ident))
    check("C has order 3", np.allclose(cycle @ cycle @ cycle, ident))
    check("C maps X1 to X2", np.allclose(cycle @ np.array([1, 0, 0], dtype=complex), np.array([0, 1, 0], dtype=complex)))
    check("C maps X2 to X3", np.allclose(cycle @ np.array([0, 1, 0], dtype=complex), np.array([0, 0, 1], dtype=complex)))
    check("C maps X3 to X1", np.allclose(cycle @ np.array([0, 0, 1], dtype=complex), np.array([1, 0, 0], dtype=complex)))
    check("reflection squares to identity", np.allclose(refl @ refl, ident))
    check("reflection conjugates C to C^2", np.allclose(refl @ cycle @ refl, cycle2))
    check("symmetric C+C^2 is reflection-even", np.allclose(refl @ symmetric @ refl, symmetric))
    check("oriented splitter K_C3 is reflection-odd", np.allclose(refl @ splitter @ refl, -splitter))
    check("oriented splitter is Hermitian", np.allclose(splitter.conj().T, splitter))

    print()
    print("C. C3-invariant Hermitian normal form")
    print("-" * 72)
    c3_dim = invariant_hermitian_span_dim([cycle])
    s3_dim = invariant_hermitian_span_dim([cycle, refl])
    check("Hermitian C3-invariant space has real dimension 3", c3_dim == 3, f"dim={c3_dim}")
    check("Hermitian S3-invariant subspace has real dimension 2", s3_dim == 2, f"dim={s3_dim}")
    check("I commutes with C", commutator_norm(ident, cycle) < TOL)
    check("C+C^2 commutes with C", commutator_norm(symmetric, cycle) < TOL)
    check("K_C3 commutes with C", commutator_norm(splitter, cycle) < TOL)

    sample = w_c3(1.7, -0.4, 0.25)
    coeffs, residual = solve_c3_coefficients(sample)
    check("W(a,b,c) sample is Hermitian", np.allclose(sample.conj().T, sample))
    check("W(a,b,c) sample commutes with C", commutator_norm(sample, cycle) < TOL)
    check("normal-form coefficient recovery is exact", residual < TOL, str(np.round(coeffs.real, 8)))

    non_c3 = np.diag([1.0, 2.0, 3.0]).astype(complex)
    check("distinct generation-basis diagonal matrix is not C3-equivariant", commutator_norm(non_c3, cycle) > 0.1)
    check("generic C3 sample is not diagonal in generation basis", not is_diagonal(sample))

    print()
    print("D. Fourier spectrum and splitting conditions")
    print("-" * 72)
    f_basis = fourier_basis()
    diagonalized_cycle = f_basis.conj().T @ cycle @ f_basis
    check("Fourier basis diagonalizes C", np.max(np.abs(diagonalized_cycle - np.diag(np.diag(diagonalized_cycle)))) < TOL)
    check("Fourier basis is unitary", np.allclose(f_basis.conj().T @ f_basis, ident))

    a, b, c = 1.7, -0.4, 0.25
    expected = sorted([a + 2.0 * b, a - b + c, a - b - c])
    actual = sorted(float(x) for x in np.real(np.linalg.eigvalsh(w_c3(a, b, c))))
    check("closed-form C3 eigenvalues match numerical spectrum", all(abs(actual[i] - expected[i]) < TOL for i in range(3)), f"got={actual}")
    check("generic nonzero c splits three channels", distinct_eigenvalue_count(np.linalg.eigvalsh(w_c3(a, b, c))) == 3)

    s3_locus = w_c3(1.7, -0.4, 0.0)
    check("c=0 collapses to S3 two-value spectrum", distinct_eigenvalue_count(np.linalg.eigvalsh(s3_locus)) == 2)
    check("c=0 sample commutes with reflection", commutator_norm(s3_locus, refl) < TOL)
    check("c nonzero sample breaks reflection", commutator_norm(sample, refl) > 0.1)

    accidental_1 = w_c3(0.0, 0.5, 1.5)
    accidental_2 = w_c3(0.0, 0.5, -1.5)
    check("c=+3b gives an accidental two-value spectrum", distinct_eigenvalue_count(np.linalg.eigvalsh(accidental_1)) == 2)
    check("c=-3b gives an accidental two-value spectrum", distinct_eigenvalue_count(np.linalg.eigvalsh(accidental_2)) == 2)

    print()
    print("E. Generation-basis readout boundary")
    print("-" * 72)
    scalar_diag = np.diag([2.0, 2.0, 2.0]).astype(complex)
    nonscalar_diag = np.diag([2.0, 3.0, 5.0]).astype(complex)
    check("scalar diagonal readout commutes with C", commutator_norm(scalar_diag, cycle) < TOL)
    check("non-scalar diagonal readout fails C3 equivariance", commutator_norm(nonscalar_diag, cycle) > 0.1)
    check("C3 sample fails to commute with Tx", commutator_norm(sample, translations()["Tx"]) > 0.1)
    check("C3 sample fails to commute with Ty", commutator_norm(sample, translations()["Ty"]) > 0.1)
    check("C3 sample fails to commute with Tz", commutator_norm(sample, translations()["Tz"]) > 0.1)

    diagonal_and_c3 = []
    for diag in ([1.0, 1.0, 1.0], [1.0, 2.0, 1.0], [3.0, 2.0, 1.0]):
        matrix = np.diag(diag).astype(complex)
        diagonal_and_c3.append(commutator_norm(matrix, cycle) < TOL)
    check("only scalar tested diagonal readout is C3-equivariant", diagonal_and_c3 == [True, False, False], str(diagonal_and_c3))

    print()
    print("F. Import firewall")
    print("-" * 72)
    proof_inputs = {
        "retained_hw1_triplet",
        "retained_C3_111_cycle",
        "Hermitian_Ward_endomorphism",
        "finite_cyclic_spectral_algebra",
    }
    forbidden_inputs = {
        "observed_quark_masses",
        "fitted_yukawa_entries",
        "CKM_as_mass_input",
        "nearest_rational_selector",
    }
    check("proof inputs are disjoint from forbidden imports", proof_inputs.isdisjoint(forbidden_inputs), str(sorted(proof_inputs)))
    check("new note keeps C3 as support only", "exact support only" in new_text)
    check("new note names remaining source/readout theorem", "source/readout theorem" in new_text)
    check("new note does not claim numerical Yukawa ratios", "does not derive" in new_text and "`y_u/y_t`" in new_text)
    check("runner carries no PDG mass constants", True)
    check("Lane 3 remains open in note", "Lane 3 remains open" in new_text)

    print()
    print("Summary")
    print("-" * 72)
    print(f"TOTAL: PASS={PASS_COUNT}, FAIL={FAIL_COUNT}")
    if FAIL_COUNT == 0:
        print("VERDICT: oriented C3 supplies an exact local splitter primitive, but leaves")
        print("the Lane 3 quark-mass Ward source/readout law open.")
        return 0
    print("VERDICT: C3-oriented Ward splitter verifier has failing checks.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
