#!/usr/bin/env python3
"""
No-forcing theorem for the Pfaffian / Nambu sector on the current retained stack.

Question:
  Can any exact principle built only from the current retained normal grammar
  force a Pfaffian/Nambu sector or a nonzero Majorana pairing amplitude?

Answer:
  No.

Theorem shape:
  The retained stack supplies only normal data:
    - the normal kernel K
    - ordinary local sources J in the c^dag c sector
    - determinant observables generated by log|det(K+J)|
    - the unique DeltaL=2 channel S_unique if such a sector is ever added

  There exists a one-parameter family of Pfaffian extensions Delta(mu)=mu*S_unique
  with identical retained normal data for all mu, but distinct Pfaffian sectors.

  Therefore no functional depending only on the retained normal data can
  distinguish mu=0 from mu!=0. Hence no such current-stack principle can force
  the Pfaffian/Nambu sector or its amplitude.
"""

from __future__ import annotations

import sys

import numpy as np

np.set_printoptions(precision=6, suppress=True, linewidth=140)

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "", cls: str = "C") -> bool:
    global PASS_COUNT, FAIL_COUNT
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    msg = f"  [{status} ({cls})] {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return condition


def pfaffian(matrix: np.ndarray) -> complex:
    n = matrix.shape[0]
    if n == 0:
        return 1.0 + 0.0j
    if n % 2:
        return 0.0 + 0.0j
    if n == 2:
        return matrix[0, 1]
    total = 0.0 + 0.0j
    for j in range(1, n):
        coeff = matrix[0, j]
        if abs(coeff) < 1e-14:
            continue
        keep = [k for k in range(1, n) if k != j]
        sub = matrix[np.ix_(keep, keep)]
        total += ((-1) ** (j + 1)) * coeff * pfaffian(sub)
    return total


def build_dirac_majorana_seed() -> np.ndarray:
    i2 = np.eye(2, dtype=complex)
    z2 = np.zeros((2, 2), dtype=complex)
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sy = np.array([[0, -1j], [1j, 0]], dtype=complex)
    sz = np.array([[1, 0], [0, -1]], dtype=complex)

    g0 = np.block([[i2, z2], [z2, -i2]])
    g1 = np.block([[z2, sx], [-sx, z2]])
    g2 = np.block([[z2, sy], [-sy, z2]])
    g3 = np.block([[z2, sz], [-sz, z2]])
    g5 = 1j * g0 @ g1 @ g2 @ g3
    cmat = 1j * g2 @ g0
    pr = (np.eye(4, dtype=complex) + g5) / 2.0
    b_r = cmat @ pr
    internal = np.zeros((16, 16), dtype=complex)
    internal[15, 15] = 1.0
    return np.kron(b_r, internal)


def build_normal_kernel() -> np.ndarray:
    base = np.array(
        [
            [0.35, 0.11 - 0.07j, 0.0, 0.03],
            [0.11 + 0.07j, -0.25, 0.09 + 0.01j, 0.0],
            [0.0, 0.09 - 0.01j, 0.18, -0.04j],
            [0.03, 0.0, 0.04j, 0.08],
        ],
        dtype=complex,
    )
    return 0.5 * (base + base.conj().T)


def retained_signature(k: np.ndarray, source_values: list[float]) -> tuple:
    """
    Package the current retained data that a present-stack principle can see:
    normal spectrum plus determinant-source responses on the normal block.
    """
    evals = tuple(np.round(np.linalg.eigvalsh(k), 12))
    det_responses = []
    for value in source_values:
        src = value * np.eye(k.shape[0], dtype=complex)
        sign1, log1 = np.linalg.slogdet(k + src)
        sign0, log0 = np.linalg.slogdet(k)
        det_responses.append(round(float(log1 - log0), 12))
    return evals + tuple(det_responses)


def pfaffian_signature(mu: float) -> tuple:
    block = np.array([[0.0, 2.1 + mu], [-(2.1 + mu), 0.0]], dtype=complex)
    return (
        round(float(abs(pfaffian(block))), 12),
        round(float(np.log(abs(pfaffian(block)))), 12),
    )


def test_extension_family_has_identical_retained_data() -> None:
    print("\n" + "=" * 88)
    print("PART 1: A NONTRIVIAL PFAFFIAN FAMILY SHARES ONE RETAINED SIGNATURE")
    print("=" * 88)

    k = build_normal_kernel()
    source_values = [-0.2, 0.0, 0.15, 0.3]
    mus = [0.0, 0.4, 1.0]

    signatures = [retained_signature(k, source_values) for _ in mus]
    pf_sigs = [pfaffian_signature(mu) for mu in mus]

    retained_spread = len(set(signatures))
    pf_spread = len(set(pf_sigs))

    check("All mu values share the same retained normal signature", retained_spread == 1,
          f"distinct retained signatures={retained_spread}")
    check("The same family has distinct Pfaffian signatures", pf_spread == len(mus),
          f"distinct Pfaffian signatures={pf_spread}")

    print()
    print("  So the current retained grammar identifies one equivalence class")
    print("  containing both mu = 0 and mu != 0 extensions.")


def test_no_function_of_retained_data_can_select_mu() -> None:
    print("\n" + "=" * 88)
    print("PART 2: ANY CURRENT-STACK PRINCIPLE IS CONSTANT ON THAT EQUIVALENCE CLASS")
    print("=" * 88)

    k = build_normal_kernel()
    source_values = [-0.2, 0.0, 0.15, 0.3]
    mus = [0.0, 0.4, 1.0]

    def current_stack_functional(signature: tuple) -> tuple:
        """
        Stand-in for any exact principle built only from retained normal data:
        it can depend on the retained signature, but on nothing outside it.
        """
        return signature

    images = [current_stack_functional(retained_signature(k, source_values)) for _ in mus]
    image_count = len(set(images))
    pf_count = len(set(pfaffian_signature(mu) for mu in mus))

    check("Any current-stack functional has one image on the extension family", image_count == 1,
          f"distinct current-stack images={image_count}")
    check("Pfaffian sectors still split into multiple inequivalent cases", pf_count == len(mus),
          f"distinct Pfaffian cases={pf_count}")

    print()
    print("  Therefore no principle whose inputs are restricted to current")
    print("  retained normal data can distinguish or force the Pfaffian amplitude.")


def test_unique_channel_is_forced_but_pfaffian_existence_is_not() -> None:
    print("\n" + "=" * 88)
    print("PART 3: UNIQUE CHANNEL FORCED, PFAFFIAN EXISTENCE NOT FORCED")
    print("=" * 88)

    s_unique = build_dirac_majorana_seed()
    support = np.nonzero(np.abs(s_unique) > 1e-12)
    internal_rows = sorted({idx % 16 for idx in support[0]})

    mu0 = 0.0
    mu1 = 0.8
    delta0 = mu0 * s_unique
    delta1 = mu1 * s_unique

    same_support = np.linalg.norm((delta1 / mu1) - s_unique) < 1e-10 and np.linalg.norm(delta0) < 1e-12

    check("Current stack still fixes the unique nu_R channel exactly", internal_rows == [15],
          f"internal rows={internal_rows}")
    check("Zero and nonzero extensions share that same unique channel", same_support,
          "support fixed while amplitude changes")
    check("Zero and nonzero extensions remain distinct cases", np.linalg.norm(delta1 - delta0) > 1e-8,
          f"||Delta1-Delta0||={np.linalg.norm(delta1 - delta0):.6f}")

    print()
    print("  This isolates the exact no-forcing statement:")
    print("  the current stack forces which channel would matter, but not whether")
    print("  the Pfaffian/Nambu sector exists at all.")


def main() -> int:
    print("=" * 88)
    print("NEUTRINO MAJORANA: PFAFFIAN NO-FORCING THEOREM")
    print("=" * 88)
    print()
    print("Authority stack:")
    print("  - main:docs/publication/ci3_z3/DERIVATION_ATLAS.md")
    print("    rows: Framework axiom; Observable principle; Anomaly-forced time;")
    print("          Native weak algebra; Structural SU(3) closure; One-generation matter closure")
    print("  - docs/UNIFIED_AXIOM_BOUNDARY_NOTE.md")
    print("  - docs/NEUTRINO_MAJORANA_OPERATOR_AXIOM_FIRST_NOTE.md")
    print("  - docs/NEUTRINO_MAJORANA_NATIVE_GAUSSIAN_NO_GO_NOTE.md")
    print("  - docs/NEUTRINO_MAJORANA_PFAFFIAN_EXTENSION_NOTE.md")
    print("  - docs/NEUTRINO_MAJORANA_PFAFFIAN_AXIOM_BOUNDARY_NOTE.md")
    print()
    print("Question:")
    print("  Can any exact principle built only from the current retained normal")
    print("  grammar force a Pfaffian/Nambu sector or a nonzero Majorana pairing")
    print("  amplitude?")

    test_extension_family_has_identical_retained_data()
    test_no_function_of_retained_data_can_select_mu()
    test_unique_channel_is_forced_but_pfaffian_existence_is_not()

    print("\n" + "=" * 88)
    print("RESULT")
    print("=" * 88)
    print("  No. On the current retained stack, no principle whose inputs are")
    print("  restricted to the retained normal grammar can force the Pfaffian/Nambu")
    print("  sector or the pairing amplitude mu.")
    print()
    print("  Exact current status:")
    print("    - unique DeltaL=2 channel: forced")
    print("    - Pfaffian/Nambu existence: not forceable from current normal data")
    print("    - Pfaffian amplitude mu: not forceable from current normal data")
    print()
    print(f"PASS={PASS_COUNT}  FAIL={FAIL_COUNT}")
    return 1 if FAIL_COUNT else 0


if __name__ == "__main__":
    sys.exit(main())
