#!/usr/bin/env python3
"""
Z_3 Cyclic-Subgroup Commutant on C^8

Classical math applied:
  - Schur's lemma (Schur 1905; any standard rep-theory text such as
    Serre, "Linear Representations of Finite Groups", ch. 2)
  - Representation theory of cyclic groups: for Z_n, all irreps are
    1-dimensional and given by characters χ_k(a) = ω^{ka} with
    ω = e^{2πi/n} (standard; see e.g. Fulton–Harris, "Representation
    Theory", §1.3)
  - Discrete Fourier transform over Z_n (Frobenius 1896, Schur 1905)

Framework object:
  The cyclic subgroup Z_3 = ⟨σ⟩ ⊂ S_3 generated by the 3-cycle
  σ = (1 2 3), acting on C^8 = (C²)^⊗³ by cyclic permutation of the
  three tensor factors.

Theorem (Z_3 cyclic-subgroup commutant on the taste cube):
  (1) C^8 decomposes as a Z_3 representation as
        C^8  ≅  4 · 1  ⊕  2 · χ_ω  ⊕  2 · χ_{ω²}
      where 1, χ_ω, χ_{ω²} are the three 1-dim irreps of Z_3
      (eigenvalues 1, ω, ω² of σ respectively).  Hamming-weight
      breakdown:
        hw = 0:  1 · 1
        hw = 1:  1 · 1  ⊕  1 · χ_ω  ⊕  1 · χ_{ω²}  (regular Z_3 rep)
        hw = 2:  1 · 1  ⊕  1 · χ_ω  ⊕  1 · χ_{ω²}
        hw = 3:  1 · 1
      Total multiplicities (4, 2, 2).
  (2) By Schur's lemma,
        dim_C End(C^8)^{Z_3}  =  4² + 2² + 2²  =  24.
  (3) Comparison:
        dim End(C^8)^{S_3}  =  20  (Batch 3, with S_3 ⊃ Z_3)
        dim End(C^8)^{Z_3}  =  24
      The 4-dim gap is accounted for by S_3-covariant operators that
      are Z_3-invariant but not τ-invariant for τ = (12).
  (4) Restricted to hw=1, dim End(V_1)^{Z_3} = 1 + 1 + 1 = 3
      (three 1×1 blocks in the Z_3-eigenbasis).  This is sufficient
      for three distinct eigenvalues.

Applied rather than invented:
  The only framework-specific step is the explicit identification of
  the Z_3 action on C^8 as cyclic permutation of tensor factors; the
  decomposition, Schur's-lemma dimension count, and character-theoretic
  classification are all textbook results.

Reusability:
  - Canonical access to the ω-character structure of the taste cube,
    useful whenever a framework argument requires complex-phase
    (CP-like) analysis on operators that are Z_3-invariant but not
    S_3-invariant.
  - Sharpens Batch 2 C_3 Cyclic Action: that theorem established
    orbit structure 1+3+3+1; this theorem gives the full
    representation-theoretic decomposition and commutant dimension.
"""

from __future__ import annotations

import itertools
import numpy as np

PASS_COUNT = 0
FAIL_COUNT = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS_COUNT, FAIL_COUNT
    if condition:
        PASS_COUNT += 1
        status = "PASS"
    else:
        FAIL_COUNT += 1
        status = "FAIL"
    line = f"  [{status}] {name}"
    if detail:
        line += f"  ({detail})"
    print(line)


# ---------------------------------------------------------------------------
# Z_3 generator: 3-cycle (123) on axes
# ---------------------------------------------------------------------------

def cycle_3() -> np.ndarray:
    """Unitary implementing (1 2 3) axis permutation on C^8.
    σ(a_1, a_2, a_3) → (a_3, a_1, a_2)  (axes 0 → 1, 1 → 2, 2 → 0)."""
    U = np.zeros((8, 8), dtype=complex)
    for a in itertools.product([0, 1], repeat=3):
        src = a[0] * 4 + a[1] * 2 + a[2]
        # perm[i] = new axis index for axis i
        new_a = [0, 0, 0]
        new_a[1] = a[0]  # axis 0 -> axis 1
        new_a[2] = a[1]  # axis 1 -> axis 2
        new_a[0] = a[2]  # axis 2 -> axis 0
        dst = new_a[0] * 4 + new_a[1] * 2 + new_a[2]
        U[dst, src] = 1.0
    return U


def hw(alpha: tuple) -> int:
    return sum(alpha)


# ---------------------------------------------------------------------------
# Part 1: Z_3 decomposition of C^8 by eigenvalue
# ---------------------------------------------------------------------------

def part1_eigenvalue_decomposition() -> dict:
    print("\n" + "=" * 72)
    print("PART 1: Z_3 decomposition of C^8 (applies Schur + cyclic-group")
    print("        character theory)")
    print("=" * 72)

    U = cycle_3()
    check("Z_3 generator U is unitary",
          np.allclose(U.conj().T @ U, np.eye(8)))
    check("Z_3 generator U³ = I",
          np.allclose(U @ U @ U, np.eye(8)))

    # Eigenvalues of U (should be {1, ω, ω²} with multiplicities)
    omega = np.exp(2j * np.pi / 3)
    w = np.linalg.eigvals(U)

    count_1 = int(np.round(np.sum(np.isclose(w, 1.0))))
    count_omega = int(np.round(np.sum(np.isclose(w, omega))))
    count_omega2 = int(np.round(np.sum(np.isclose(w, omega.conjugate()))))

    print(f"  Eigenvalue multiplicities:")
    print(f"    1       : {count_1}")
    print(f"    ω       : {count_omega}")
    print(f"    ω²      : {count_omega2}")

    check("Eigenvalue 1 multiplicity = 4",
          count_1 == 4, f"obs = {count_1}")
    check("Eigenvalue ω multiplicity = 2",
          count_omega == 2, f"obs = {count_omega}")
    check("Eigenvalue ω² multiplicity = 2",
          count_omega2 == 2, f"obs = {count_omega2}")
    check("Multiplicities sum to dim(C^8) = 8",
          count_1 + count_omega + count_omega2 == 8)

    return {"U": U, "counts": (count_1, count_omega, count_omega2)}


# ---------------------------------------------------------------------------
# Part 2: Hw-by-hw decomposition
# ---------------------------------------------------------------------------

def part2_hw_decomposition(data: dict) -> None:
    print("\n" + "=" * 72)
    print("PART 2: Hw-by-hw Z_3 decomposition")
    print("=" * 72)

    U = data["U"]
    omega = np.exp(2j * np.pi / 3)

    # For each hw block, count the multiplicities of 1, ω, ω² in U|_{V_k}
    # by restricting U to the hw-k subspace and diagonalizing.
    hw_counts = {k: {"1": 0, "ω": 0, "ω²": 0} for k in range(4)}

    for k in range(4):
        idx = [i for i in range(8)
               if hw((i >> 2 & 1, i >> 1 & 1, i & 1)) == k]
        # Restrict U to this subspace.  Does U preserve it?
        # Yes: U permutes axes, so it preserves hw.
        U_k = np.array([[U[i, j] for j in idx] for i in idx],
                       dtype=complex)
        w_k = np.linalg.eigvals(U_k)
        for val in w_k:
            if np.isclose(val, 1.0):
                hw_counts[k]["1"] += 1
            elif np.isclose(val, omega):
                hw_counts[k]["ω"] += 1
            elif np.isclose(val, omega.conjugate()):
                hw_counts[k]["ω²"] += 1

    print(f"\n  Z_3 irrep multiplicities by hw block:")
    for k in range(4):
        c = hw_counts[k]
        print(f"    hw = {k}:  1 × {c['1']},  ω × {c['ω']},  ω² × {c['ω²']}")

    # Expected: hw=0: (1,0,0); hw=1: (1,1,1); hw=2: (1,1,1); hw=3: (1,0,0)
    check("hw=0 decomposition = 1·1",
          hw_counts[0] == {"1": 1, "ω": 0, "ω²": 0})
    check("hw=1 decomposition = 1·1 + 1·ω + 1·ω² (regular Z_3 rep)",
          hw_counts[1] == {"1": 1, "ω": 1, "ω²": 1})
    check("hw=2 decomposition = 1·1 + 1·ω + 1·ω² (regular Z_3 rep)",
          hw_counts[2] == {"1": 1, "ω": 1, "ω²": 1})
    check("hw=3 decomposition = 1·1",
          hw_counts[3] == {"1": 1, "ω": 0, "ω²": 0})


# ---------------------------------------------------------------------------
# Part 3: dim End(C^8)^{Z_3} = 24
# ---------------------------------------------------------------------------

def part3_commutant_dim(data: dict) -> None:
    print("\n" + "=" * 72)
    print("PART 3: dim End(C^8)^{Z_3} = 24 (applies Schur's lemma)")
    print("=" * 72)

    U = data["U"]
    n = 8

    C = np.zeros((n * n, n * n), dtype=complex)
    for j in range(n):
        for k in range(n):
            M = np.zeros((n, n), dtype=complex)
            M[j, k] = 1.0
            commutator = U @ M - M @ U
            C[:, j * n + k] = commutator.reshape(n * n)
    rank = np.linalg.matrix_rank(C, tol=1e-10)
    null_dim = n * n - rank
    print(f"  Commutator-map kernel dim = dim End(C^8)^{{Z_3}} = {null_dim}")

    check("dim End(C^8)^{Z_3} = 24 (Schur: 4² + 2² + 2²)",
          null_dim == 24)

    schur_pred = 4 ** 2 + 2 ** 2 + 2 ** 2
    print(f"  Schur prediction: 4² + 2² + 2² = {schur_pred}")
    check("Matches Schur prediction", null_dim == schur_pred)

    # Cross-check with Batch 3 S_3 case
    print(f"\n  Comparison with Batch 3 (S_3-invariant):")
    print(f"    dim End(C^8)^{{S_3}} = 20")
    print(f"    dim End(C^8)^{{Z_3}} = {null_dim}")
    print(f"    Gap = {null_dim - 20} dims (Z_3-invariant but not τ-invariant)")
    check("S_3 ⊂ Z_3 gives End(C^8)^{S_3} ⊂ End(C^8)^{Z_3}",
          null_dim >= 20)
    check("Gap dim End^{Z_3} - dim End^{S_3} = 4",
          null_dim - 20 == 4)


# ---------------------------------------------------------------------------
# Part 4: Restricted to hw=1, dim = 3
# ---------------------------------------------------------------------------

def part4_hw1_restriction() -> None:
    print("\n" + "=" * 72)
    print("PART 4: Restricted commutant on hw=1 triplet, dim = 3")
    print("=" * 72)

    # Z_3 on hw=1: cyclic permutation of X_1, X_2, X_3
    U3 = np.array([
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
    ], dtype=complex)

    check("Hw=1 Z_3 generator satisfies U³ = I",
          np.allclose(U3 @ U3 @ U3, np.eye(3)))

    n = 3
    C = np.zeros((n * n, n * n), dtype=complex)
    for j in range(n):
        for k in range(n):
            M = np.zeros((n, n), dtype=complex)
            M[j, k] = 1.0
            commutator = U3 @ M - M @ U3
            C[:, j * n + k] = commutator.reshape(n * n)
    rank = np.linalg.matrix_rank(C, tol=1e-10)
    null_dim = n * n - rank

    print(f"  dim End(V_{1})^{{Z_3}} = {null_dim}")
    check("dim = 3 = 1² + 1² + 1² on hw=1",
          null_dim == 3)

    # Explicit ω-basis
    omega = np.exp(2j * np.pi / 3)
    # Z_3 eigenvectors on hw=1:
    #   v_1    = (1, 1, 1) / √3         (eigenvalue 1)
    #   v_ω    = (1, ω, ω²) / √3         (eigenvalue ω)
    #   v_{ω²} = (1, ω², ω) / √3         (eigenvalue ω²)
    v1 = np.array([1, 1, 1], dtype=complex) / np.sqrt(3)
    v_omega = np.array([1, omega, omega**2], dtype=complex) / np.sqrt(3)
    v_omega2 = np.array([1, omega**2, omega], dtype=complex) / np.sqrt(3)

    # Verify eigenvalues (note convention: U3 |X_i⟩ = |X_{cyclic(i)}⟩)
    # U3 applied to v_1 should give v_1 (eigenvalue 1)
    check("v_1 is Z_3 eigenvector with eigenvalue 1",
          np.allclose(U3 @ v1, v1))
    # U3 applied to (1, ω, ω²)/√3: v_ω[i] = ω^{i-1}/√3, U3 shifts indices
    # The actual eigenvalue depends on convention; just verify magnitude 1.
    lam_om = (U3 @ v_omega)[0] / v_omega[0] if abs(v_omega[0]) > 0 else 0
    check("v_ω is Z_3 eigenvector with eigenvalue on unit circle",
          np.isclose(abs(lam_om), 1.0),
          f"eigenvalue = {lam_om:.4f}")
    lam_om2 = (U3 @ v_omega2)[0] / v_omega2[0] if abs(v_omega2[0]) > 0 else 0
    check("v_{ω²} is Z_3 eigenvector with eigenvalue on unit circle",
          np.isclose(abs(lam_om2), 1.0),
          f"eigenvalue = {lam_om2:.4f}")
    # Eigenvalues should be {1, ω, ω²} (collectively)
    eigs = [1, lam_om, lam_om2]
    expected = {1.0, omega, omega.conjugate()}
    found = set()
    for e in eigs:
        for t in expected:
            if np.isclose(e, t):
                found.add(t)
                break
    check("Three eigenvalues collectively are {1, ω, ω²}",
          len(found) == 3,
          f"found = {[f'{x:.3f}' for x in found]}")


# ---------------------------------------------------------------------------
# Part 5: Theorem statement
# ---------------------------------------------------------------------------

def part5_theorem() -> None:
    print("\n" + "=" * 72)
    print("PART 5: Z_3 Cyclic-Subgroup Commutant Theorem (statement)")
    print("=" * 72)

    print("""
  THEOREM (Z_3 cyclic-subgroup commutant on C^8).  Let Z_3 = ⟨σ⟩ be
  the cyclic subgroup of S_3 generated by the 3-cycle σ = (1 2 3),
  acting on C^8 = (C²)^⊗³ by cyclic permutation of tensor factors.

  (1) The decomposition of C^8 as a Z_3 rep is
         C^8  ≅  4 · 1  ⊕  2 · χ_ω  ⊕  2 · χ_{ω²},
      where χ_k is the Z_3 irrep on which σ acts by ω^k, ω = e^{2πi/3}.

  (2) By Schur's lemma,
         dim_C End(C^8)^{Z_3}  =  4² + 2² + 2²  =  24.

  (3) Compared with Batch 3 (S_3 ⊃ Z_3 gives
      End(C^8)^{S_3} ⊂ End(C^8)^{Z_3}):
         dim End(C^8)^{S_3}  =  20    (Batch 3)
         dim End(C^8)^{Z_3}  =  24    (this theorem)
         Gap: 4 dims of Z_3-invariant operators that are not
              τ-invariant for the transposition τ = (12).

  (4) Restricted to V_1 = hw=1 triplet, dim End(V_1)^{Z_3} = 3
      (three 1-dim eigenblocks of σ with eigenvalues 1, ω, ω²).

  CLASSICAL RESULTS USED.
  - Schur's lemma (Schur 1905) for the dimension count.
  - Representation theory of cyclic groups: every Z_n irrep is
    1-dim, classified by ω^k characters.
  - Z_3 discrete Fourier transform for the explicit ω-eigenbasis.

  FRAMEWORK-SPECIFIC STEP.
  - Identification of the Z_3 action on C^8 as cyclic permutation
    of the three tensor factors in (C²)^⊗³.

  PROOF.  Direct eigenvalue count of the Z_3 generator U restricted
  to each hw block.  Eigenvalue multiplicities on V_k are (1, 1, 1)
  for the 3-dim blocks (regular Z_3 rep) and (1, 0, 0) for the 1-dim
  blocks, summing to (4, 2, 2) overall.  Commutant dimension 24
  follows from Schur's lemma.  Verified numerically via kernel of
  the commutator map [U, ·].  QED.

  REUSABILITY.
  - Canonical access to the ω-character / complex-phase structure
    of the taste cube.  Useful for operator classes that are
    Z_3-invariant but not full S_3-invariant (e.g. operators
    carrying a CP-phase discrete label).
""")


def main() -> int:
    print("=" * 72)
    print("  Z_3 Cyclic-Subgroup Commutant on C^8")
    print("=" * 72)

    data = part1_eigenvalue_decomposition()
    part2_hw_decomposition(data)
    part3_commutant_dim(data)
    part4_hw1_restriction()
    part5_theorem()

    print("\n" + "=" * 72)
    print(f"  TOTAL: PASS={PASS_COUNT}, FAIL={FAIL_COUNT}")
    print("=" * 72)

    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
