"""Pauli group P_1 generated by σ_i has order 16.

By axiom_first_cl3_per_site_uniqueness (retained), per-site Cl(3) acts
on H_x ≅ C² via Pauli matrices σ_i. The multiplicative subgroup generated
by σ_i (closing under products with the inevitable phase factors ±1 and
±i from σ_iσ_j = δ_{ij} I + i ε_{ijk} σ_k) is the **single-qubit Pauli
group**

    P_1  =  {±I, ±i I, ±σ_1, ±i σ_1, ±σ_2, ±i σ_2, ±σ_3, ±i σ_3}

with **|P_1| = 16** elements. Structurally:

    P_1  =  Z_4 × Z_2^2  /  (cyclic 4 phases × Pauli sign-flips × generator choice)

This is the fundamental finite group structure of Cl(3) at the per-site
operator level, used throughout quantum information theory (stabilizer
formalism, Clifford-circuit theory, Pauli-frame analysis).

Tests:
  (T1) Pauli multiplication table σ_a σ_b = δ_{ab} I + i ε_{abc} σ_c
  (T2) Generators σ_i alone don't form a group (need phase closure)
  (T3) Multiplicative group ⟨σ_1, σ_2, σ_3⟩ has exactly 16 elements
  (T4) The group is non-abelian (verified by [σ_1, σ_2] ≠ 0)
  (T5) Center Z(P_1) = {±I, ±iI} of order 4
  (T6) Quotient P_1 / Z(P_1) ≅ Z_2 × Z_2 (Klein four-group)
  (T7) Every element has order dividing 4 (since (i)^4 = 1 and σ_i² = I)
"""
from __future__ import annotations

import numpy as np


def main() -> None:
    print("=" * 72)
    print("PAULI GROUP P_1 GENERATED BY σ_i HAS ORDER 16")
    print("=" * 72)
    print()

    s1 = np.array([[0, 1], [1, 0]], dtype=complex)
    s2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
    s3 = np.array([[1, 0], [0, -1]], dtype=complex)
    I2 = np.eye(2, dtype=complex)
    sigmas = [s1, s2, s3]

    # ----- Test 1: Pauli multiplication table -----
    print("-" * 72)
    print("TEST 1: σ_a σ_b = δ_{ab} I + i ε_{abc} σ_c (Pauli identity)")
    print("-" * 72)
    eps = np.zeros((3, 3, 3))
    eps[0, 1, 2] = eps[1, 2, 0] = eps[2, 0, 1] = 1.0
    eps[0, 2, 1] = eps[2, 1, 0] = eps[1, 0, 2] = -1.0
    max_table_dev = 0.0
    for a in range(3):
        for b in range(3):
            prod = sigmas[a] @ sigmas[b]
            target = (1.0 if a == b else 0.0) * I2 + sum(
                1j * eps[a, b, c] * sigmas[c] for c in range(3)
            )
            d = np.linalg.norm(prod - target)
            max_table_dev = max(max_table_dev, d)
    print(f"  max ||σ_a σ_b - (δ_{{ab}} I + i ε_{{abc}} σ_c)|| = {max_table_dev:.3e}")
    t1_ok = max_table_dev < 1e-12
    print(f"  STATUS: {'PASS' if t1_ok else 'FAIL'}")
    print()

    # ----- Test 2: σ_i alone don't close as a group -----
    print("-" * 72)
    print("TEST 2: {σ_1, σ_2, σ_3} alone is NOT a closed multiplicative set")
    print("        (σ_1 σ_2 = i σ_3 requires phase closure)")
    print("-" * 72)
    s1s2 = s1 @ s2
    target = 1j * s3
    print(f"  σ_1 σ_2 = i σ_3 (sample)")
    print(f"  ||σ_1 σ_2 - i σ_3|| = {np.linalg.norm(s1s2 - target):.3e}")
    # The set {σ_1, σ_2, σ_3} doesn't contain ±I or ±i I, so not closed
    print("  ⇒ σ_1 σ_2 is not in {σ_1, σ_2, σ_3}; closure forces ±I, ±iI elements.")
    t2_ok = np.linalg.norm(s1s2 - target) < 1e-12
    print(f"  STATUS: {'PASS' if t2_ok else 'FAIL'}")
    print()

    # ----- Test 3: ⟨σ_1, σ_2, σ_3⟩ has exactly 16 elements -----
    print("-" * 72)
    print("TEST 3: Multiplicative group ⟨σ_i⟩ has exactly 16 elements")
    print("-" * 72)
    # Generate the group via BFS
    generators = sigmas
    elements = [I2.copy()]  # start with identity

    def matrix_in_set(M: np.ndarray, set_: list[np.ndarray]) -> bool:
        for E in set_:
            if np.linalg.norm(M - E) < 1e-10:
                return True
        return False

    new = True
    iter_count = 0
    while new and iter_count < 100:
        new = False
        for E in elements[:]:
            for g in generators:
                product = E @ g
                if not matrix_in_set(product, elements):
                    elements.append(product)
                    new = True
        iter_count += 1
    n_elements = len(elements)
    print(f"  Generated group has {n_elements} elements")
    print(f"  Expected: 16")
    t3_ok = n_elements == 16
    print(f"  STATUS: {'PASS' if t3_ok else 'FAIL'}")
    print()

    # ----- Test 4: Group is non-abelian -----
    print("-" * 72)
    print("TEST 4: P_1 is non-abelian: [σ_1, σ_2] ≠ 0")
    print("-" * 72)
    comm = s1 @ s2 - s2 @ s1
    print(f"  ||[σ_1, σ_2]|| = {np.linalg.norm(comm):.3e}  (should be > 0)")
    t4_ok = np.linalg.norm(comm) > 1.0
    print(f"  STATUS: {'PASS' if t4_ok else 'FAIL'}")
    print()

    # ----- Test 5: Center Z(P_1) = {±I, ±iI} of order 4 -----
    print("-" * 72)
    print("TEST 5: Center Z(P_1) = {+I, -I, +i I, -i I} has order 4")
    print("-" * 72)
    center = []
    for E in elements:
        is_central = all(np.linalg.norm(E @ g - g @ E) < 1e-10 for g in elements)
        if is_central:
            center.append(E)
    print(f"  |Z(P_1)| = {len(center)}")
    expected_center = [I2, -I2, 1j * I2, -1j * I2]
    # Verify the center contains exactly these
    center_correct = all(matrix_in_set(C, expected_center) for C in center) and \
                     all(matrix_in_set(E, center) for E in expected_center)
    print(f"  Z(P_1) = {{±I, ±iI}} match: {center_correct}")
    t5_ok = len(center) == 4 and center_correct
    print(f"  STATUS: {'PASS' if t5_ok else 'FAIL'}")
    print()

    # ----- Test 6: P_1 / Z(P_1) ≅ Z_2 × Z_2 (Klein 4) -----
    print("-" * 72)
    print("TEST 6: P_1 / Z(P_1) has order 16 / 4 = 4 (Klein four-group Z_2 × Z_2)")
    print("-" * 72)
    quotient_order = len(elements) // len(center)
    print(f"  |P_1 / Z(P_1)| = {len(elements)} / {len(center)} = {quotient_order}")
    # Klein 4: every non-identity element squares to identity (in quotient)
    # In P_1: σ_i^2 = I ∈ Z(P_1), so σ_i has order 2 mod center
    t6_ok = quotient_order == 4
    print(f"  STATUS: {'PASS' if t6_ok else 'FAIL'}")
    print()

    # ----- Test 7: Every element has order dividing 4 -----
    print("-" * 72)
    print("TEST 7: Every element of P_1 has order dividing 4 (since i^4 = 1, σ^2 = I)")
    print("-" * 72)
    all_div_4 = True
    for E in elements:
        E2 = E @ E
        E4 = E2 @ E2
        if not np.linalg.norm(E4 - I2) < 1e-10:
            all_div_4 = False
    print(f"  All 16 elements satisfy E^4 = I: {all_div_4}")
    t7_ok = all_div_4
    print(f"  STATUS: {'PASS' if t7_ok else 'FAIL'}")
    print()

    print("=" * 72)
    print(f"  Test 1 (Pauli multiplication table):              {'PASS' if t1_ok else 'FAIL'}")
    print(f"  Test 2 (closure forces ±I, ±iI):                  {'PASS' if t2_ok else 'FAIL'}")
    print(f"  Test 3 (|⟨σ_i⟩| = 16):                              {'PASS' if t3_ok else 'FAIL'}")
    print(f"  Test 4 (non-abelian):                             {'PASS' if t4_ok else 'FAIL'}")
    print(f"  Test 5 (Z(P_1) = {{±I, ±iI}}, order 4):              {'PASS' if t5_ok else 'FAIL'}")
    print(f"  Test 6 (|P_1/Z| = 4 ≅ Klein 4):                    {'PASS' if t6_ok else 'FAIL'}")
    print(f"  Test 7 (every elt has order dividing 4):          {'PASS' if t7_ok else 'FAIL'}")
    all_ok = all([t1_ok, t2_ok, t3_ok, t4_ok, t5_ok, t6_ok, t7_ok])
    print(f"  OVERALL: {'PASS' if all_ok else 'FAIL'}")
    if not all_ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
