#!/usr/bin/env python3
"""Scan the structured mirror geometry family for a Born-safe linear lane.

This script searches the structured mirror growth family using the strictly
linear propagator from the branch Born audit. The question is deliberately
narrow:

  - does any structured-mirror parameter set stay Born-clean on the corrected
    three-slit Sorkin harness?
  - if so, does it still show meaningful decoherence and gravity?

The search is bounded to the 3D structured-mirror family generated by
`grow_structured_mirror(..., d_growth=2)`.
"""

from __future__ import annotations

import argparse
import math
import os
import sys
from collections import defaultdict
from itertools import product

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from scripts.mirror_born_audit import propagate_LINEAR
from scripts.structured_mirror_growth import compute_field, grow_structured_mirror

LAM = 10.0
DEFAULT_N_LAYERS = [25, 30, 40]
DEFAULT_NPL_HALF = [8, 12, 16, 20]
DEFAULT_CONNECT_RADIUS = [2.5, 3.0, 3.5, 4.0, 4.5]
DEFAULT_GRID_SPACING = [1.0, 1.25, 1.5]
DEFAULT_LAYER_JITTER = [0.0, 0.15, 0.3]


def mean_se(vals: list[float]) -> tuple[float, float]:
    vals = [v for v in vals if v is not None and not math.isnan(v)]
    if not vals:
        return math.nan, math.nan
    mean = sum(vals) / len(vals)
    if len(vals) < 2:
        return mean, 0.0
    var = sum((v - mean) ** 2 for v in vals) / (len(vals) - 1)
    return mean, math.sqrt(var / len(vals))


def by_layer(positions):
    layers = defaultdict(list)
    for idx, pos in enumerate(positions):
        layers[round(pos[0])].append(idx)
    ordered = sorted(layers.keys())
    return layers, ordered


def select_slits(positions, barrier_nodes, center_y, slit_gap):
    upper = sorted(
        [i for i in barrier_nodes if positions[i][1] > center_y + slit_gap],
        key=lambda i: positions[i][1],
    )
    lower = sorted(
        [i for i in barrier_nodes if positions[i][1] < center_y - slit_gap],
        key=lambda i: -positions[i][1],
    )
    middle = sorted(
        [i for i in barrier_nodes if abs(positions[i][1] - center_y) <= slit_gap],
        key=lambda i: abs(positions[i][1] - center_y),
    )
    return upper, lower, middle


def detector_bin_probs(positions, det_list, amps, y_extent, n_bins=8):
    probs = [0.0] * n_bins
    if not det_list:
        return None
    max_abs_y = max((abs(positions[d][1]) for d in det_list), default=y_extent)
    extent = max(y_extent, max_abs_y, 1e-9)
    bin_width = (2.0 * extent) / n_bins
    for d in det_list:
        y = positions[d][1]
        bin_idx = int((y + extent) / bin_width)
        bin_idx = max(0, min(n_bins - 1, bin_idx))
        probs[bin_idx] += abs(amps[d]) ** 2
    norm = sum(probs)
    if norm <= 1e-30:
        return None
    return [p / norm for p in probs]


def sorkin_born(positions, adj, src, k, barrier_nodes, slit_a, slit_b, slit_c, det_list, field):
    all_slits = set(slit_a + slit_b + slit_c)
    other = set(barrier_nodes) - all_slits
    combos = {
        "abc": set(slit_a + slit_b + slit_c),
        "ab": set(slit_a + slit_b),
        "ac": set(slit_a + slit_c),
        "bc": set(slit_b + slit_c),
        "a": set(slit_a),
        "b": set(slit_b),
        "c": set(slit_c),
    }

    i3 = 0.0
    p_abc = 0.0
    for key, open_set in combos.items():
        blocked = other | (all_slits - open_set)
        amps = propagate_LINEAR(positions, adj, field, src, k, blocked)
        for d in det_list:
            p = abs(amps[d]) ** 2
            if key == "abc":
                p_abc += p
                i3 += p
            elif key in ("ab", "ac", "bc"):
                i3 -= p
            else:
                i3 += p
    return abs(i3) / p_abc if p_abc > 1e-30 else math.nan


def measure_config(n_layers, npl_half, connect_radius, grid_spacing, layer_jitter, seed, k, slit_gap):
    positions, adj = grow_structured_mirror(
        n_layers=n_layers,
        npl_half=npl_half,
        d_growth=2,
        grid_spacing=grid_spacing,
        connect_radius=connect_radius,
        layer_jitter=layer_jitter,
        rng_seed=seed,
    )
    n = len(positions)
    layer_map, layers = by_layer(positions)
    if len(layers) < 7:
        return None

    src = layer_map[layers[0]]
    det_list = list(layer_map[layers[-1]])
    if not det_list:
        return None

    barrier_idx = layers[len(layers) // 3]
    barrier_nodes = layer_map[barrier_idx]
    if len(barrier_nodes) < 6:
        return None

    center_y = sum(pos[1] for pos in positions) / len(positions)
    slit_a, slit_b, slit_c = select_slits(positions, barrier_nodes, center_y, slit_gap)
    if not slit_a or not slit_b or not slit_c:
        return None
    slit_a = slit_a[:3]
    slit_b = slit_b[:3]
    slit_c = slit_c[:3]
    if not slit_a or not slit_b or not slit_c:
        return None

    blocked = set(barrier_nodes) - set(slit_a + slit_b + slit_c)

    grav_layer = layers[2 * len(layers) // 3]
    mass_nodes = [i for i in layer_map[grav_layer] if positions[i][1] > center_y + 1.0]
    if not mass_nodes:
        return None

    field_m = compute_field(positions, mass_nodes)
    field_f = [0.0] * n

    psi_a = propagate_LINEAR(positions, adj, field_m, src, k, blocked | set(slit_b))
    psi_b = propagate_LINEAR(positions, adj, field_m, src, k, blocked | set(slit_a))

    pa = {d: abs(psi_a[d]) ** 2 for d in det_list}
    pb = {d: abs(psi_b[d]) ** 2 for d in det_list}
    na = sum(pa.values())
    nb = sum(pb.values())
    if na < 1e-30 or nb < 1e-30:
        return None
    dtv = 0.5 * sum(abs(pa[d] / na - pb[d] / nb) for d in det_list)

    env_depth = max(1, round(len(layers) / 6))
    start = len(layers) // 3 + 1
    stop = min(len(layers) - 1, start + env_depth)
    mid_nodes = []
    for layer in layers[start:stop]:
        mid_nodes.extend(layer_map[layer])

    y_extent = max((abs(pos[1]) for pos in positions), default=1.0)
    bins_a = detector_bin_probs(positions, mid_nodes, psi_a, y_extent)
    bins_b = detector_bin_probs(positions, mid_nodes, psi_b, y_extent)
    if bins_a is None or bins_b is None:
        sn = 0.0
    else:
        sn_num = sum((a - b) ** 2 for a, b in zip(bins_a, bins_b))
        na2 = sum(a * a for a in bins_a)
        nb2 = sum(b * b for b in bins_b)
        sn = sn_num / (na2 + nb2) if (na2 + nb2) > 0 else 0.0
    d_cl = math.exp(-LAM * LAM * sn)

    rho = {}
    for d1 in det_list:
        for d2 in det_list:
            rho[(d1, d2)] = (
                psi_a[d1].conjugate() * psi_a[d2]
                + psi_b[d1].conjugate() * psi_b[d2]
                + d_cl * psi_a[d1].conjugate() * psi_b[d2]
                + d_cl * psi_b[d1].conjugate() * psi_a[d2]
            )
    tr = sum(rho[(d, d)] for d in det_list).real
    if tr < 1e-30:
        return None
    for key in rho:
        rho[key] /= tr
    pur_cl = sum(abs(v) ** 2 for v in rho.values()).real

    am = propagate_LINEAR(positions, adj, field_m, src, k, blocked)
    af = propagate_LINEAR(positions, adj, field_f, src, k, blocked)
    pm = sum(abs(am[d]) ** 2 for d in det_list)
    pf = sum(abs(af[d]) ** 2 for d in det_list)
    gravity = math.nan
    if pm > 1e-30 and pf > 1e-30:
        ym = sum(abs(am[d]) ** 2 * positions[d][1] for d in det_list) / pm
        yf = sum(abs(af[d]) ** 2 * positions[d][1] for d in det_list) / pf
        gravity = ym - yf

    am0 = propagate_LINEAR(positions, adj, field_m, src, 0.0, blocked)
    af0 = propagate_LINEAR(positions, adj, field_f, src, 0.0, blocked)
    pm0 = sum(abs(am0[d]) ** 2 for d in det_list)
    pf0 = sum(abs(af0[d]) ** 2 for d in det_list)
    grav_k0 = math.nan
    if pm0 > 1e-30 and pf0 > 1e-30:
        ym0 = sum(abs(am0[d]) ** 2 * positions[d][1] for d in det_list) / pm0
        yf0 = sum(abs(af0[d]) ** 2 * positions[d][1] for d in det_list) / pf0
        grav_k0 = ym0 - yf0

    born = sorkin_born(positions, adj, src, k, barrier_nodes, slit_a, slit_b, slit_c, det_list, field_f)
    return {
        "dtv": dtv,
        "pur_cl": pur_cl,
        "s_norm": sn,
        "gravity": gravity,
        "born": born,
        "grav_k0": grav_k0,
    }


def parse_int_list(values):
    return [int(v) for v in values]


def parse_float_list(values):
    return [float(v) for v in values]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n-layers", nargs="+", type=int, default=DEFAULT_N_LAYERS)
    parser.add_argument("--npl-half", nargs="+", type=int, default=DEFAULT_NPL_HALF)
    parser.add_argument("--connect-radius", nargs="+", type=float, default=DEFAULT_CONNECT_RADIUS)
    parser.add_argument("--grid-spacing", nargs="+", type=float, default=DEFAULT_GRID_SPACING)
    parser.add_argument("--layer-jitter", nargs="+", type=float, default=DEFAULT_LAYER_JITTER)
    parser.add_argument("--slit-gap", type=float, default=2.0)
    parser.add_argument("--k", type=float, default=5.0)
    parser.add_argument("--n-seeds", type=int, default=6)
    parser.add_argument("--born-threshold", type=float, default=1e-10)
    args = parser.parse_args()

    seeds = [s * 7 + 3 for s in range(args.n_seeds)]

    print("=" * 108)
    print("STRUCTURED MIRROR BORNSAFE SCAN")
    print("  linear propagator on the structured mirror growth family")
    print(
        f"  grid_spacing={args.grid_spacing}, layer_jitter={args.layer_jitter}, "
        f"slit_gap={args.slit_gap:g}"
    )
    print(f"  k={args.k}, seeds={args.n_seeds}, Born threshold={args.born_threshold:.1e}")
    print("=" * 108)
    print()
    print(
        f"  {'N':>4s}  {'npl':>4s}  {'r':>4s}  {'d_TV':>8s}  {'pur_cl':>8s}  {'S_norm':>8s}  "
        f"{'gravity':>10s}  {'Born':>10s}  {'k=0':>10s}  {'ok':>3s}"
    )
    print("  " + "-" * 96)

    rows = []
    for n_layers, npl_half, connect_radius, grid_spacing, layer_jitter in product(
        args.n_layers, args.npl_half, args.connect_radius, args.grid_spacing, args.layer_jitter
    ):
        dtv_all = []
        pur_all = []
        sn_all = []
        grav_all = []
        born_all = []
        k0_all = []
        ok = 0
        for seed in seeds:
            row = measure_config(
                n_layers=n_layers,
                npl_half=npl_half,
                connect_radius=connect_radius,
                grid_spacing=grid_spacing,
                layer_jitter=layer_jitter,
                seed=seed,
                k=args.k,
                slit_gap=args.slit_gap,
            )
            if row is None:
                continue
            ok += 1
            dtv_all.append(row["dtv"])
            pur_all.append(row["pur_cl"])
            sn_all.append(row["s_norm"])
            grav_all.append(row["gravity"])
            born_all.append(row["born"])
            k0_all.append(row["grav_k0"])

        if not ok:
            print(
                f"  {n_layers:4d}  {npl_half:4d}  {connect_radius:4.1f}  "
                f"g={grid_spacing:>4.2f}  j={layer_jitter:>4.2f}  FAIL"
            )
            continue

        dtv_mean, dtv_se = mean_se(dtv_all)
        pur_mean, pur_se = mean_se(pur_all)
        sn_mean, sn_se = mean_se(sn_all)
        grav_mean, grav_se = mean_se(grav_all)
        born_mean, born_se = mean_se(born_all)
        k0_mean, k0_se = mean_se(k0_all)

        rows.append(
            {
                "n_layers": n_layers,
                "npl_half": npl_half,
                "connect_radius": connect_radius,
                "grid_spacing": grid_spacing,
                "layer_jitter": layer_jitter,
                "ok": ok,
                "dtv": dtv_mean,
                "pur_cl": pur_mean,
                "sn": sn_mean,
                "gravity": grav_mean,
                "born": born_mean,
                "born_se": born_se,
                "k0": k0_mean,
            }
        )

        born_str = f"{born_mean:10.2e}" if not math.isnan(born_mean) else f"{'nan':>10s}"
        print(
            f"  {n_layers:4d}  {npl_half:4d}  {connect_radius:4.1f}  "
            f"g={grid_spacing:>4.2f}  j={layer_jitter:>4.2f}  "
            f"{dtv_mean:8.4f}  {pur_mean:7.4f}±{pur_se:.02f}  {sn_mean:8.4f}  "
            f"{grav_mean:+7.4f}±{grav_se:.3f}  {born_str}  {k0_mean:+10.2e}  {ok:3d}"
        )

    print()
    retained = [
        r for r in rows
        if not math.isnan(r["born"])
        and r["born"] < args.born_threshold
        and r["gravity"] > 0.0
        and r["pur_cl"] < 0.95
    ]
    retained.sort(key=lambda r: (r["born"], r["pur_cl"], -r["gravity"]))

    if retained:
        best = retained[0]
        print("RETAINED POCKET:")
        print(
            f"  N={best['n_layers']}, npl_half={best['npl_half']}, r={best['connect_radius']:g}, "
            f"grid_spacing={best['grid_spacing']:g}, jitter={best['layer_jitter']:g} -> "
            f"pur_cl={best['pur_cl']:.4f}, gravity={best['gravity']:+.4f}, Born={best['born']:.2e}, "
            f"d_TV={best['dtv']:.4f}, S_norm={best['sn']:.4f}, k=0={best['k0']:+.2e}"
        )
    else:
        print("RETAINED POCKET: none found in this scan.")
        print("  Best read is negative: structured mirror growth does not retain a")
        print("  Born-safe linear pocket under the scanned parameters.")


if __name__ == "__main__":
    main()
